In [2]:
import pandas as pd

In [2]:
import pandas as pd

print("Pandas version:", pd.__version__)

Pandas version: 2.2.2

In [10]:
#read data from CSV file into a dataframe
# df= pd.read_csv('sales_data_sample.csv',encoding="latin1" )

# df= pd.read_json('sample_Data.json')

In [17]:
data={
    "Name":['Ram','Shyam','Ganshyam'],
    "age":[10,20,30],
    "City":['Mumbai','Punjab','Delhi']
}
df= pd.DataFrame(data)
# df.to_csv("output.csv",index=False) # to save in folder or convert in csv
# df

In [25]:
# to excel
# df.to_excel("output.xlsx")
# to json
# df.to_json("output.json")

In [26]:
# df

       Name  age    City
0       Ram   10  Mumbai
1     Shyam   20  Punjab
2  Ganshyam   30   Delhi

In [40]:
# how to see rows in data
# head(), tail() - these are method to see rows 
# head() - starting 5
# tail() - bottom 5
# df= pd.read_json('sample_Data.json')

print("Display 10 rows of first")
# print(df.head()) # if not given num it will take defalut 5 from and bottom

print("Displat 10 rows of last")
# print(df.tail())

Display 10 rows of first
Displat 10 rows of last

In [46]:
df= pd.read_json('sample_Data.json')
print("Displaying the info of data set")
print(df.info()) # info()

Displaying the info of data set
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           20 non-null     int64
 1   name         20 non-null     object
 2   description  20 non-null     object
 3   price        20 non-null     float64
 4   category     20 non-null     object
 5   image        20 non-null     object
dtypes: float64(1), int64(1), object(4)
memory usage: 1.1+ KB
None

In [50]:
data={
    "Name":['Ram','Shyam','Ganshyam'],
    "age":[10,20,30],
    "City":['Mumbai','Punjab','Delhi']
}
# df1= pd.DataFrame(data)
# print(df1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   age     3 non-null      int64
 2   City    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes
None

# describe

In [22]:
data1={
     "Name":['Ram','Shyam','Ganshyam','dhanshyam','asha','komal','rehan','Prateek'],
    "age":[10,20,30,40,20,21,23,22],
    "Salary":[5000,7000,9000,5000,35000,25000,40000,30000],
    "Performance score":[20,30,40,20,80,60,70,82],
    "City":['Mumbai','Punjab','Delhi','agra','Delhi','Delhi','Madhyapradsh','noida']
}
df = pd.DataFrame(data1)
print("sample dataframe:")
print(df)
#describe show numeric table-- summary
print("Descriptive stats")
print(df.describe())

sample dataframe:
        Name  age  Salary  Performance score          City
0        Ram   10    5000                 20        Mumbai
1      Shyam   20    7000                 30        Punjab
2   Ganshyam   30    9000                 40         Delhi
3  dhanshyam   40    5000                 20          agra
4       asha   20   35000                 80         Delhi
5      komal   21   25000                 60         Delhi
6      rehan   23   40000                 70  Madhyapradsh
7    Prateek   22   30000                 82         noida
Descriptive stats
            age        Salary  Performance score
count   8.00000      8.000000           8.000000
mean   23.25000  19500.000000          50.250000
std     8.69729  14579.829511          25.976638
min    10.00000   5000.000000          20.000000
25%    20.00000   6500.000000          27.500000
50%    21.50000  17000.000000          50.000000
75%    24.75000  31250.000000          72.500000
max    40.00000  40000.000000          82.000000

In [8]:
# shape and column
print(df)
print(df.shape)
print(df.columns)

        Name  age  Salary  Performance score          City
0        Ram   10    5000                 20        Mumbai
1      Shyam   20    7000                 30        Punjab
2   Ganshyam   30    9000                 40         Delhi
3  dhanshyam   40    5000                 20          agra
4       asha   20   35000                 80         Delhi
5      komal   21   25000                 60         Delhi
6      rehan   23   40000                 70  Madhyapradsh
7    Prateek   22   30000                 82         noida
(8, 5)
Index(['Name', 'age', 'Salary', 'Performance score', 'City'], dtype='object')

In [9]:
# specific selected column manuplation ---- use square bracketes[]
# filter rows ---- use boolen - 0,1 true false
# combine multipke condition
# selecticing columns
# 1.- a series
# 2. - dataframe multiple columns of data
#  column df["column name"]
# subset = df['col1', 'col2']..multiple

        # filter rows:
# boolean indexing 
# base on single cond
#  filteres_rows= df[df["salary"]>50000
# multiple rows
# filtered_rows=df[(df["salry"]>50000) & (df["sal"]<80000)]

In [23]:
print("sample data frame:")
print(df)
# single col
# print("Names (Single col return series)")
name=df["Name"]
# print(name)
# multi col
subset= df[["Salary","City"]]
print("Names (multi col return series)")
print(subset)

sample data frame:
        Name  age  Salary  Performance score          City
0        Ram   10    5000                 20        Mumbai
1      Shyam   20    7000                 30        Punjab
2   Ganshyam   30    9000                 40         Delhi
3  dhanshyam   40    5000                 20          agra
4       asha   20   35000                 80         Delhi
5      komal   21   25000                 60         Delhi
6      rehan   23   40000                 70  Madhyapradsh
7    Prateek   22   30000                 82         noida
Names (multi col return series)
   Salary          City
0    5000        Mumbai
1    7000        Punjab
2    9000         Delhi
3    5000          agra
4   35000         Delhi
5   25000         Delhi
6   40000  Madhyapradsh
7   30000         noida

In [3]:
#  single condition use
data2={
     "Name":['Ram','Shyam','Ganshyam','dhanshyam','asha','komal','rehan','Prateek'],
    "age":[10,20,30,40,20,21,23,22],
    "Salary":[5000,7000,9000,5000,35000,25000,40000,30000],
    "Performance score":[20,30,40,20,80,60,70,82],
    "City":['Mumbai','Punjab','Delhi','agra','Delhi','Delhi','Madhyapradsh','noida']
}
df8= pd.DataFrame(data2)
print(df8)
high_sal = df8[df8['Salary']>20000]
print("employe with salary >20000")
print(high_sal)

        Name  age  Salary  Performance score          City
0        Ram   10    5000                 20        Mumbai
1      Shyam   20    7000                 30        Punjab
2   Ganshyam   30    9000                 40         Delhi
3  dhanshyam   40    5000                 20          agra
4       asha   20   35000                 80         Delhi
5      komal   21   25000                 60         Delhi
6      rehan   23   40000                 70  Madhyapradsh
7    Prateek   22   30000                 82         noida
employe with salary >20000
      Name  age  Salary  Performance score          City
4     asha   20   35000                 80         Delhi
5    komal   21   25000                 60         Delhi
6    rehan   23   40000                 70  Madhyapradsh
7  Prateek   22   30000                 82         noida

In [35]:
#multicondition
# filtering rows sal --->20k and age>20
filtered= df[(df['age']>20) & (df['Salary']>20000)]
print("Employee with more than 25k sal & age is above 25")
print(filtered)

Employee with more than 25k sal & age is above 25
      Name  age  Salary  Performance score          City
5    komal   21   25000                 60         Delhi
6    rehan   23   40000                 70  Madhyapradsh
7  Prateek   22   30000                 82         noida

In [ ]:
# OR CON
filtered_or = df[(df['Salary'])or ()]

# adding column

In [5]:
Data6={
     "Name":['Ram','Shyam','Ganshyam','dhanshyam','asha','komal','rehan','Prateek'],
    "age":[10,20,30,40,20,21,23,22],
    "Salary":[5000,7000,9000,5000,35000,25000,40000,30000],
    "Performance score":[20,30,40,20,80,60,70,82],
    "City":['Mumbai','Punjab','Delhi','agra','Delhi','Delhi','Madhyapradsh','noida']
}
df9 = pd.DataFrame(Data6)

In [6]:
df9

        Name  age  Salary  Performance score          City
0        Ram   10    5000                 20        Mumbai
1      Shyam   20    7000                 30        Punjab
2   Ganshyam   30    9000                 40         Delhi
3  dhanshyam   40    5000                 20          agra
4       asha   20   35000                 80         Delhi
5      komal   21   25000                 60         Delhi
6      rehan   23   40000                 70  Madhyapradsh
7    Prateek   22   30000                 82         noida

In [7]:
# adding column via assig
# square brackets df["column_name"]= some_data
# lets add bonus a new column that is 10% of sal

df9["Bonus"]=df9["Salary"]*0.1 
print(df9)

        Name  age  Salary  Performance score          City   Bonus
0        Ram   10    5000                 20        Mumbai   500.0
1      Shyam   20    7000                 30        Punjab   700.0
2   Ganshyam   30    9000                 40         Delhi   900.0
3  dhanshyam   40    5000                 20          agra   500.0
4       asha   20   35000                 80         Delhi  3500.0
5      komal   21   25000                 60         Delhi  2500.0
6      rehan   23   40000                 70  Madhyapradsh  4000.0
7    Prateek   22   30000                 82         noida  3000.0

In [9]:
# using insert method for adding new column in your data at specific index and specific column
# using insert()
# df.insert(loc,"column name", some_data)

df9.insert(0,"Employee ID",[10,20,30,40,50,60,70,80])
print(df9)

   Employee ID       Name  age  Salary  Performance score          City  \
0           10        Ram   10    5000                 20        Mumbai
1           20      Shyam   20    7000                 30        Punjab
2           30   Ganshyam   30    9000                 40         Delhi
3           40  dhanshyam   40    5000                 20          agra
4           50       asha   20   35000                 80         Delhi
5           60      komal   21   25000                 60         Delhi
6           70      rehan   23   40000                 70  Madhyapradsh
7           80    Prateek   22   30000                 82         noida

    Bonus
0   500.0
1   700.0
2   900.0
3   500.0
4  3500.0
5  2500.0
6  4000.0
7  3000.0

### UPDATING VALUE

In [11]:
# .loc[]-for accesing specific value and updating the value
# df.loc[row_index,"Column Namee"]= new_value
#  updating ram's salary
df9.loc[0,"Salary"]=7000
df9

,Employee ID,Name,age,Salary,Performance score,City,Bonus
0,10,Ram,10,7000,20,Mumbai,500.0
1,20,Shyam,20,7000,30,Punjab,700.0
2,30,Ganshyam,30,9000,40,Delhi,900.0
3,40,dhanshyam,40,5000,20,agra,500.0
4,50,asha,20,35000,80,Delhi,3500.0
5,60,komal,21,25000,60,Delhi,2500.0
6,70,rehan,23,40000,70,Madhyapradsh,4000.0
7,80,Prateek,22,30000,82,noida,3000.0

In [13]:
# increasing value by 5%
df9.loc[0:,"Salary"]= df9['Salary']*1.05
df9

,Employee ID,Name,age,Salary,Performance score,City,Bonus
0,10,Ram,10,3675,20,Mumbai,500.0
1,20,Shyam,20,3675,30,Punjab,700.0
2,30,Ganshyam,30,4725,40,Delhi,900.0
3,40,dhanshyam,40,2625,20,agra,500.0
4,50,asha,20,18375,80,Delhi,3500.0
5,60,komal,21,13125,60,Delhi,2500.0
6,70,rehan,23,21000,70,Madhyapradsh,4000.0
7,80,Prateek,22,15750,82,noida,3000.0

## removing columns

In [ ]:
## drop method --
# df.drop(columns =["columnName"],inplace=True)

## Practice

# concat() — Combine DataFrames by stacking

In [ ]:
# concat() is used to combine multiple DataFrames.
# It can stack them vertically (row-wise) or horizontally (column-wise)

#         pd.concat([df1, df2], axis=0)

#         axis=0 → stack rows (default)

#         axis=1 → stack columns

In [2]:
import pandas as pd

In [11]:
# Vertical stacking (row wise)
df1 = pd.DataFrame({
    'ID':[1,2],
    'Name':['Asha','Priya']
})
print(df1)
df2= pd.DataFrame({
    'ID':[3,4],
    'Name':['Komal','Jahanvi']
})
print(df2)
combined = pd.concat([df1,df2], ignore_index=True)
print(combined)

   ID   Name
0   1   Asha
1   2  Priya
   ID     Name
0   3    Komal
1   4  Jahanvi
   ID     Name
0   1     Asha
1   2    Priya
2   3    Komal
3   4  Jahanvi

In [13]:
# Horizontal stacking( column wise)
df1=pd.DataFrame({
    'Name':['Asha','Priya']
})
print(df1)
df2= pd.DataFrame({
    'Marks':[90,85]
})
print(df2)
combined = pd.concat([df1,df2], axis=1)
print(combined)

    Name
0   Asha
1  Priya
   Marks
0     90
1     85
    Name  Marks
0   Asha     90
1  Priya     85

# merge() — Like SQL JOIN

In [ ]:
# merge() is used to combine two DataFrames based on a common column (key).

# It works just like SQL joins (e.g., inner, left, right, outer joins).

In [ ]:
# syntax
# pd.merge(left_df, right_df, on='key_column', how='type_of_join')
# on → the column name to join on

# how → type of join: 'inner', 'left', 'right', 'outer'

In [24]:
# merge() (Inner Join
students= pd.DataFrame({
    'ID':[1,2,3,4],
    'Name':['Asha','Komal','Jahanvi','Prateek']
})
print(students)
marks=pd.DataFrame({
    'ID':[1,2,3],
    'Marks':[90,85,88]
})
print(marks)
merged= pd.merge(students,marks,on='ID')
print(merged)

   ID     Name
0   1     Asha
1   2    Komal
2   3  Jahanvi
3   4  Prateek
   ID  Marks
0   1     90
1   2     85
2   3     88
   ID     Name  Marks
0   1     Asha     90
1   2    Komal     85
2   3  Jahanvi     88

In [25]:
# Example — Left Join
left_joined = pd.merge(students, marks,on='ID', how='left')
print(left_joined)

   ID     Name  Marks
0   1     Asha   90.0
1   2    Komal   85.0
2   3  Jahanvi   88.0
3   4  Prateek    NaN

#Example — Outer Join
outer_joined = pd.merge(students, marks,on='ID', how='outer')
print(outer_joined)

In [27]:
#Example — inner Join
inner_joined = pd.merge(students, marks,on='ID', how='inner')
print(inner_joined)

   ID     Name  Marks
0   1     Asha     90
1   2    Komal     85
2   3  Jahanvi     88

In [28]:
#Example — right Join
right_joined = pd.merge(students, marks,on='ID', how='right')
print(right_joined)

   ID     Name  Marks
0   1     Asha     90
1   2    Komal     85
2   3  Jahanvi     88

## Grouping and aggregating (gruopby)

In [ ]:
# Syntax
# df.groupby('column_name').agg_function()
# df.groupby('column_name')['target_column'].agg_function()

In [2]:
import pandas as pd

data=pd.DataFrame({
    'Department':['IT','HR','IT','HR','IT'],
    'Salary':[50000,60000,52000,61000,51000]
})
grouped= data.groupby('Department')['Salary'].sum()
print(grouped) #It grouped by Department and summed the Salary.

Department
HR    121000
IT    153000
Name: Salary, dtype: int64

# Multiple Aggregations

In [6]:
print(data)
data.groupby('Department')['Salary'].agg(['mean','max','count'])

  Department  Salary
0         IT   50000
1         HR   60000
2         IT   52000
3         HR   61000
4         IT   51000

               mean    max  count
Department
HR          60500.0  61000      2
IT          51000.0  52000      3

# Group by multiple columns

In [9]:
data=pd.DataFrame({
    'Department':['IT','HR','IT','HR','IT'],
    'Gender':['F','F','M','M','F'],
    'Salary':[50000,60000,52000,61000,51000]
})
result=data.groupby(['Department','Gender'])['Salary'].mean()
print(result)

Department  Gender
HR          F         60000.0
            M         61000.0
IT          F         50500.0
            M         52000.0
Name: Salary, dtype: float64

In [10]:
result.reset_index()

  Department Gender   Salary
0         HR      F  60000.0
1         HR      M  61000.0
2         IT      F  50500.0
3         IT      M  52000.0

# sort_values()

In [ ]:
# Syntax
# df.sort_values(by='column_name', ascending=True)

In [2]:
import pandas as pd
df= pd.DataFrame({
    'Name':['Asha','Riya','Neha'],
    'Marks':[85,92,78]
})
sorted_df= df.sort_values(by='Marks')
print(sorted_df)

   Name  Marks
2  Neha     78
0  Asha     85
1  Riya     92

# Sort in descending order

In [3]:
df.sort_values(by='Marks', ascending = False)

   Name  Marks
1  Riya     92
0  Asha     85
2  Neha     78

# Sort by multiple columns

In [4]:
df= pd.DataFrame({
    'Name':['Asha','Riya','Neha','Asha'],
    'Marks':[85,92,85,92]
})
df.sort_values(by=['Marks','Name'],ascending=[False,True])

   Name  Marks
3  Asha     92
1  Riya     92
0  Asha     85
2  Neha     85

In [7]:
# Slicing rows by index position (iloc)
df.iloc[0]
df.iloc[0:2]

   Name  Marks
0  Asha     85
1  Riya     92

In [10]:
# slicing rows by index label(loc)
df.loc[0]
df.loc[0:2]

   Name  Marks
0  Asha     85
1  Riya     92
2  Neha     85

In [12]:
# slicing rows & columns together
df.iloc[0:2,0:1] # row 0-1 column 0
df.loc[0:2,['Name','Marks']]

   Name  Marks
0  Asha     85
1  Riya     92
2  Neha     85