# Pandas Operation
---

## Importing Required Modules 
1. importing numpy for mathematical operation on arrays and dataframe.
2. importing pandas for reading data and data manipualtion.

In [52]:
import numpy as np
import pandas as pd

## Reading dadaset

In [53]:
df=pd.read_csv('pokemon.csv')

In [54]:
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [55]:
df.shape

(800, 12)

## To read 5 rows from starting

In [27]:
df.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

## To read last 5 rows

In [28]:
df.tail()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

### Short Description abot the Dataset
- Pokedex entry number of the Pokemon

pokedex is an  catalog that provide information regarding the various species of Pokémon featured in the Pokémon video game, anime and manga series.)
- Name = name of the Pokemon
- Type 1 = each Pokemon has a type, this determines weakness/resistance to attacks [referred to as the primary type]
- Type 2 = some Pokemon are dual type and have 2 [referred to as the secondary type]
- Total sum of all stats that come after this, a general guide to how strong a Pokemon is
- HP = hit points, or health, defines how much damage a Pokemon can withstand before fainting
- Attack =  the base modifier for normal attacks
- Defense = the base damage resistance against normal attacks
- Sp. Atk = special attack, the base modifier for special attacks
- Sp. Def = the base damage resistance against special attacks
- Speed = determines which Pokemon attacks first each round
- Generation = refers to which grouping/game series the Pokemon was released in
- Legendary = a boolean that identifies whether the Pokemon is legendary

## To check the rows and columns in a data

In [10]:
df.shape

(800, 12)

## To see all the columns in a data

In [11]:
df.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

## To check the datatypes of a column

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   #           800 non-null    int64
 1   Name        800 non-null    object
 2   Type 1      800 non-null    object
 3   Type 2      359 non-null    object
 4   HP          800 non-null    int64
 5   Attack      800 non-null    int64
 6   Defense     800 non-null    int64
 7   Sp. Atk     800 non-null    int64
 8   Sp. Def     800 non-null    int64
 9   Speed       800 non-null    int64
 10  Generation  800 non-null    int64
 11  Legendary   800 non-null    bool
dtypes: bool(1), int64(8), object(3)
memory usage: 69.7+ KB

## To see the stats of the data

In [13]:
df.describe() # numeric cols

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [14]:
df.describe(include='object') # non numeric

             Name Type 1  Type 2
count         800    800     359
unique        800     18      18
top     Bulbasaur  Water  Flying
freq            1    112      81

## To check the missing values in data

In [15]:
df.isnull().sum()

#               0
Name            0
Type 1          0
Type 2        441
HP              0
Attack          0
Defense         0
Sp. Atk         0
Sp. Def         0
Speed           0
Generation      0
Legendary       0
dtype: int64

In [16]:
df.isnull().sum()/df.shape[0]*100

#              0.000
Name           0.000
Type 1         0.000
Type 2        55.125
HP             0.000
Attack         0.000
Defense        0.000
Sp. Atk        0.000
Sp. Def        0.000
Speed          0.000
Generation     0.000
Legendary      0.000
dtype: float64

## To drop the any column in a data

In [56]:
df.drop(columns=['Type 2', '#'],inplace=True)

In [57]:
df

,Name,Type 1,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,60,62,63,80,80,60,1,False
2,Venusaur,Grass,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,80,100,123,122,120,80,1,False
4,Charmander,Fire,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,50,100,150,100,150,50,6,True
796,DiancieMega Diancie,Rock,50,160,110,160,110,110,6,True
797,HoopaHoopa Confined,Psychic,80,110,60,150,130,70,6,True
798,HoopaHoopa Unbound,Psychic,80,160,60,170,130,80,6,True
799,Volcanion,Fire,80,110,120,130,90,70,6,True

In [19]:
df

,Name,Type 1,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,60,62,63,80,80,60,1,False
2,Venusaur,Grass,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,80,100,123,122,120,80,1,False
4,Charmander,Fire,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,50,100,150,100,150,50,6,True
796,DiancieMega Diancie,Rock,50,160,110,160,110,110,6,True
797,HoopaHoopa Confined,Psychic,80,110,60,150,130,70,6,True
798,HoopaHoopa Unbound,Psychic,80,160,60,170,130,80,6,True
799,Volcanion,Fire,80,110,120,130,90,70,6,True

## To read each column

In [20]:
df

,Name,Type 1,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,60,62,63,80,80,60,1,False
2,Venusaur,Grass,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,80,100,123,122,120,80,1,False
4,Charmander,Fire,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,50,100,150,100,150,50,6,True
796,DiancieMega Diancie,Rock,50,160,110,160,110,110,6,True
797,HoopaHoopa Confined,Psychic,80,110,60,150,130,70,6,True
798,HoopaHoopa Unbound,Psychic,80,160,60,170,130,80,6,True
799,Volcanion,Fire,80,110,120,130,90,70,6,True

In [7]:
df.shape

(800, 10)

In [21]:
df['Name']

0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: object

In [22]:
for i in df['Name']:       
    print(i)

Bulbasaur
Ivysaur
Venusaur
VenusaurMega Venusaur
Charmander
Charmeleon
Charizard
CharizardMega Charizard X
CharizardMega Charizard Y
Squirtle
Wartortle
Blastoise
BlastoiseMega Blastoise
Caterpie
Metapod
Butterfree
Weedle
Kakuna
Beedrill
BeedrillMega Beedrill
Pidgey
Pidgeotto
Pidgeot
PidgeotMega Pidgeot
Rattata
Raticate
Spearow
Fearow
Ekans
Arbok
Pikachu
Raichu
Sandshrew
Sandslash
Nidoran (Female)
Nidorina
Nidoqueen
Nidoran (Male)
Nidorino
Nidoking
Clefairy
Clefable
Vulpix
Ninetales
Jigglypuff
Wigglytuff
Zubat
Golbat
Oddish
Gloom
Vileplume
Paras
Parasect
Venonat
Venomoth
Diglett
Dugtrio
Meowth
Persian
Psyduck
Golduck
Mankey
Primeape
Growlithe
Arcanine
Poliwag
Poliwhirl
Poliwrath
Abra
Kadabra
Alakazam
AlakazamMega Alakazam
Machop
Machoke
Machamp
Bellsprout
Weepinbell
Victreebel
Tentacool
Tentacruel
Geodude
Graveler
Golem
Ponyta
Rapidash
Slowpoke
Slowbro
SlowbroMega Slowbro
Magnemite
Magneton
Farfetch'd
Doduo
Dodrio
Seel
Dewgong
Grimer
Muk
Shellder
Cloyster
Gastly
Haunter
Gengar
GengarMega Gengar
Onix
Drowzee
Hypno
Krabby
Kingler
Voltorb
Electrode
Exeggcute
Exeggutor
Cubone
Marowak
Hitmonlee
Hitmonchan
Lickitung
Koffing
Weezing
Rhyhorn
Rhydon
Chansey
Tangela
Kangaskhan
KangaskhanMega Kangaskhan
Horsea
Seadra
Goldeen
Seaking
Staryu
Starmie
Mr. Mime
Scyther
Jynx
Electabuzz
Magmar
Pinsir
PinsirMega Pinsir
Tauros
Magikarp
Gyarados
GyaradosMega Gyarados
Lapras
Ditto
Eevee
Vaporeon
Jolteon
Flareon
Porygon
Omanyte
Omastar
Kabuto
Kabutops
Aerodactyl
AerodactylMega Aerodactyl
Snorlax
Articuno
Zapdos
Moltres
Dratini
Dragonair
Dragonite
Mewtwo
MewtwoMega Mewtwo X
MewtwoMega Mewtwo Y
Mew
Chikorita
Bayleef
Meganium
Cyndaquil
Quilava
Typhlosion
Totodile
Croconaw
Feraligatr
Sentret
Furret
Hoothoot
Noctowl
Ledyba
Ledian
Spinarak
Ariados
Crobat
Chinchou
Lanturn
Pichu
Cleffa
Igglybuff
Togepi
Togetic
Natu
Xatu
Mareep
Flaaffy
Ampharos
AmpharosMega Ampharos
Bellossom
Marill
Azumarill
Sudowoodo
Politoed
Hoppip
Skiploom
Jumpluff
Aipom
Sunkern
Sunflora
Yanma
Wooper
Quagsire
Espeon
Umbreon
Murkrow
Slowking
Misdreavus
Unown
Wobbuffet
Girafarig
Pineco
Forretress
Dunsparce
Gligar
Steelix
SteelixMega Steelix
Snubbull
Granbull
Qwilfish
Scizor
ScizorMega Scizor
Shuckle
Heracross
HeracrossMega Heracross
Sneasel
Teddiursa
Ursaring
Slugma
Magcargo
Swinub
Piloswine
Corsola
Remoraid
Octillery
Delibird
Mantine
Skarmory
Houndour
Houndoom
HoundoomMega Houndoom
Kingdra
Phanpy
Donphan
Porygon2
Stantler
Smeargle
Tyrogue
Hitmontop
Smoochum
Elekid
Magby
Miltank
Blissey
Raikou
Entei
Suicune
Larvitar
Pupitar
Tyranitar
TyranitarMega Tyranitar
Lugia
Ho-oh
Celebi
Treecko
Grovyle
Sceptile
SceptileMega Sceptile
Torchic
Combusken
Blaziken
BlazikenMega Blaziken
Mudkip
Marshtomp
Swampert
SwampertMega Swampert
Poochyena
Mightyena
Zigzagoon
Linoone
Wurmple
Silcoon
Beautifly
Cascoon
Dustox
Lotad
Lombre
Ludicolo
Seedot
Nuzleaf
Shiftry
Taillow
Swellow
Wingull
Pelipper
Ralts
Kirlia
Gardevoir
GardevoirMega Gardevoir
Surskit
Masquerain
Shroomish
Breloom
Slakoth
Vigoroth
Slaking
Nincada
Ninjask
Shedinja
Whismur
Loudred
Exploud
Makuhita
Hariyama
Azurill
Nosepass
Skitty
Delcatty
Sableye
SableyeMega Sableye
Mawile
MawileMega Mawile
Aron
Lairon
Aggron
AggronMega Aggron
Meditite
Medicham
MedichamMega Medicham
Electrike
Manectric
ManectricMega Manectric
Plusle
Minun
Volbeat
Illumise
Roselia
Gulpin
Swalot
Carvanha
Sharpedo
SharpedoMega Sharpedo
Wailmer
Wailord
Numel
Camerupt
CameruptMega Camerupt
Torkoal
Spoink
Grumpig
Spinda
Trapinch
Vibrava
Flygon
Cacnea
Cacturne
Swablu
Altaria
AltariaMega Altaria
Zangoose
Seviper
Lunatone
Solrock
Barboach
Whiscash
Corphish
Crawdaunt
Baltoy
Claydol
Lileep
Cradily
Anorith
Armaldo
Feebas
Milotic
Castform
Kecleon
Shuppet
Banette
BanetteMega Banette
Duskull
Dusclops
Tropius
Chimecho
Absol
AbsolMega Absol
Wynaut
Snorunt
Glalie
GlalieMega Glalie
Spheal
Sealeo
Walrein
Clamperl
Huntail
Gorebyss
Relicanth
Luvdisc
Bagon
Shelgon
Salamence
SalamenceMega Salamence
Beldum
Metang
Metagross
MetagrossMega Metagross
Regirock
Regice
Registeel
Latias
LatiasMega Latias
Latios
LatiosMega Latios
Kyogre
KyogrePrimal Kyogre
Groudon
GroudonPrimal Groudon
Rayquaza
RayquazaMega Rayquaza
Jirachi
DeoxysNormal Forme
DeoxysAttack Forme
DeoxysDefense Forme
DeoxysSpeed Forme
Turtwig
Grotle
Torterra
Chimchar
Monferno
Infernape
Piplup
Prinplup
Empoleon
Starly
Staravia
Staraptor
Bidoof
Bibarel
Kricketot
Kricketune
Shinx
Luxio
Luxray
Budew
Roserade
Cranidos
Rampardos
Shieldon
Bastiodon
Burmy
WormadamPlant Cloak
WormadamSandy Cloak
WormadamTrash Cloak
Mothim
Combee
Vespiquen
Pachirisu
Buizel
Floatzel
Cherubi
Cherrim
Shellos
Gastrodon
Ambipom
Drifloon
Drifblim
Buneary
Lopunny
LopunnyMega Lopunny
Mismagius
Honchkrow
Glameow
Purugly
Chingling
Stunky
Skuntank
Bronzor
Bronzong
Bonsly
Mime Jr.
Happiny
Chatot
Spiritomb
Gible
Gabite
Garchomp
GarchompMega Garchomp
Munchlax
Riolu
Lucario
LucarioMega Lucario
Hippopotas
Hippowdon
Skorupi
Drapion
Croagunk
Toxicroak
Carnivine
Finneon
Lumineon
Mantyke
Snover
Abomasnow
AbomasnowMega Abomasnow
Weavile
Magnezone
Lickilicky
Rhyperior
Tangrowth
Electivire
Magmortar
Togekiss
Yanmega
Leafeon
Glaceon
Gliscor
Mamoswine
Porygon-Z
Gallade
GalladeMega Gallade
Probopass
Dusknoir
Froslass
Rotom
RotomHeat Rotom
RotomWash Rotom
RotomFrost Rotom
RotomFan Rotom
RotomMow Rotom
Uxie
Mesprit
Azelf
Dialga
Palkia
Heatran
Regigigas
GiratinaAltered Forme
GiratinaOrigin Forme
Cresselia
Phione
Manaphy
Darkrai
ShayminLand Forme
ShayminSky Forme
Arceus
Victini
Snivy
Servine
Serperior
Tepig
Pignite
Emboar
Oshawott
Dewott
Samurott
Patrat
Watchog
Lillipup
Herdier
Stoutland
Purrloin
Liepard
Pansage
Simisage
Pansear
Simisear
Panpour
Simipour
Munna
Musharna
Pidove
Tranquill
Unfezant
Blitzle
Zebstrika
Roggenrola
Boldore
Gigalith
Woobat
Swoobat
Drilbur
Excadrill
Audino
AudinoMega Audino
Timburr
Gurdurr
Conkeldurr
Tympole
Palpitoad
Seismitoad
Throh
Sawk
Sewaddle
Swadloon
Leavanny
Venipede
Whirlipede
Scolipede
Cottonee
Whimsicott
Petilil
Lilligant
Basculin
Sandile
Krokorok
Krookodile
Darumaka
DarmanitanStandard Mode
DarmanitanZen Mode
Maractus
Dwebble
Crustle
Scraggy
Scrafty
Sigilyph
Yamask
Cofagrigus
Tirtouga
Carracosta
Archen
Archeops
Trubbish
Garbodor
Zorua
Zoroark
Minccino
Cinccino
Gothita
Gothorita
Gothitelle
Solosis
Duosion
Reuniclus
Ducklett
Swanna
Vanillite
Vanillish
Vanilluxe
Deerling
Sawsbuck
Emolga
Karrablast
Escavalier
Foongus
Amoonguss
Frillish
Jellicent
Alomomola
Joltik
Galvantula
Ferroseed
Ferrothorn
Klink
Klang
Klinklang
Tynamo
Eelektrik
Eelektross
Elgyem
Beheeyem
Litwick
Lampent
Chandelure
Axew
Fraxure
Haxorus
Cubchoo
Beartic
Cryogonal
Shelmet
Accelgor
Stunfisk
Mienfoo
Mienshao
Druddigon
Golett
Golurk
Pawniard
Bisharp
Bouffalant
Rufflet
Braviary
Vullaby
Mandibuzz
Heatmor
Durant
Deino
Zweilous
Hydreigon
Larvesta
Volcarona
Cobalion
Terrakion
Virizion
TornadusIncarnate Forme
TornadusTherian Forme
ThundurusIncarnate Forme
ThundurusTherian Forme
Reshiram
Zekrom
LandorusIncarnate Forme
LandorusTherian Forme
Kyurem
KyuremBlack Kyurem
KyuremWhite Kyurem
KeldeoOrdinary Forme
KeldeoResolute Forme
MeloettaAria Forme
MeloettaPirouette Forme
Genesect
Chespin
Quilladin
Chesnaught
Fennekin
Braixen
Delphox
Froakie
Frogadier
Greninja
Bunnelby
Diggersby
Fletchling
Fletchinder
Talonflame
Scatterbug
Spewpa
Vivillon
Litleo
Pyroar
Flabébé
Floette
Florges
Skiddo
Gogoat
Pancham
Pangoro
Furfrou
Espurr
MeowsticMale
MeowsticFemale
Honedge
Doublade
AegislashBlade Forme
AegislashShield Forme
Spritzee
Aromatisse
Swirlix
Slurpuff
Inkay
Malamar
Binacle
Barbaracle
Skrelp
Dragalge
Clauncher
Clawitzer
Helioptile
Heliolisk
Tyrunt
Tyrantrum
Amaura
Aurorus
Sylveon
Hawlucha
Dedenne
Carbink
Goomy
Sliggoo
Goodra
Klefki
Phantump
Trevenant
PumpkabooAverage Size
PumpkabooSmall Size
PumpkabooLarge Size
PumpkabooSuper Size
GourgeistAverage Size
GourgeistSmall Size
GourgeistLarge Size
GourgeistSuper Size
Bergmite
Avalugg
Noibat
Noivern
Xerneas
Yveltal
Zygarde50% Forme
Diancie
DiancieMega Diancie
HoopaHoopa Confined
HoopaHoopa Unbound
Volcanion

## To read multiple columns

In [8]:
df[['Name','Type 1','HP']]

                      Name   Type 1  HP
0                Bulbasaur    Grass  45
1                  Ivysaur    Grass  60
2                 Venusaur    Grass  80
3    VenusaurMega Venusaur    Grass  80
4               Charmander     Fire  39
..                     ...      ...  ..
795                Diancie     Rock  50
796    DiancieMega Diancie     Rock  50
797    HoopaHoopa Confined  Psychic  80
798     HoopaHoopa Unbound  Psychic  80
799              Volcanion     Fire  80

[800 rows x 3 columns]

## To read multiple columns with a certain rows

In [32]:
df[['Name','Type 1']][200:211]

          Name  Type 1
200  Sudowoodo    Rock
201   Politoed   Water
202     Hoppip   Grass
203   Skiploom   Grass
204   Jumpluff   Grass
205      Aipom  Normal
206    Sunkern   Grass
207   Sunflora   Grass
208      Yanma     Bug
209     Wooper   Water
210   Quagsire   Water

In [148]:
df.iloc[200:211,0:2]

          Name  Type 1
200  Sudowoodo    Rock
201   Politoed   Water
202     Hoppip   Grass
203   Skiploom   Grass
204   Jumpluff   Grass
205      Aipom  Normal
206    Sunkern   Grass
207   Sunflora   Grass
208      Yanma     Bug
209     Wooper   Water
210   Quagsire   Water

## To read each row

In [12]:
df.iloc[9]

Name          Squirtle
Type 1           Water
HP                  44
Attack              48
Defense             65
Sp. Atk             50
Sp. Def             64
Speed               43
Generation           1
Legendary        False
Name: 9, dtype: object

In [14]:
df.iloc[[9]]

,Name,Type 1,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
9,Squirtle,Water,44,48,65,50,64,43,1,False

## To read multiple rows

In [60]:
df.iloc[10:16]

,Name,Type 1,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
10,Wartortle,Water,59,63,80,65,80,58,1,False
11,Blastoise,Water,79,83,100,85,105,78,1,False
12,BlastoiseMega Blastoise,Water,79,103,120,135,115,78,1,False
13,Caterpie,Bug,45,30,35,20,20,45,1,False
14,Metapod,Bug,50,20,55,25,25,30,1,False
15,Butterfree,Bug,60,45,50,90,80,70,1,False

## To read a specific name, here 3 is a row index and 1 is a column index

In [155]:
df.head(2)

,Name,Type 1,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,60,62,63,80,80,60,1,False

In [156]:

df.iloc[11,0]

'Blastoise'

In [62]:
df.head()

,Name,Type 1,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,60,62,63,80,80,60,1,False
2,Venusaur,Grass,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,80,100,123,122,120,80,1,False
4,Charmander,Fire,39,52,43,60,50,65,1,False

## To see the unique values in a data

In [64]:
df['Type 1'].unique()

array(['Grass', 'Fire', 'Water', 'Bug', 'Normal', 'Poison', 'Electric',
       'Ground', 'Fairy', 'Fighting', 'Psychic', 'Rock', 'Ghost', 'Ice',
       'Dragon', 'Dark', 'Steel', 'Flying'], dtype=object)

# To see the number of unique categories

In [164]:
df['Type 1'].nunique()
        #OR

18

In [165]:
len(df['Type 1'].unique())

18

## To see the Counts of the category in a data

In [66]:
df['Type 1'].value_counts() # by default is shows the result in descending order

Type 1
Water       112
Normal       98
Grass        70
Bug          69
Psychic      57
Fire         52
Electric     44
Rock         44
Dragon       32
Ground       32
Ghost        32
Dark         31
Poison       28
Steel        27
Fighting     27
Ice          24
Fairy        17
Flying        4
Name: count, dtype: int64

In [68]:
df['Type 1'].mode()

0    Water
Name: Type 1, dtype: object

## To find the specific information in a data or to apply a condition in a data

# it is just like the specific rows it's based on textual information
df[df['Type 1']=='Fire'] #it print only the data of Fire type1 pokemons

In [9]:
df

,Name,Type 1,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,60,62,63,80,80,60,1,False
2,Venusaur,Grass,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,80,100,123,122,120,80,1,False
4,Charmander,Fire,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,50,100,150,100,150,50,6,True
796,DiancieMega Diancie,Rock,50,160,110,160,110,110,6,True
797,HoopaHoopa Confined,Psychic,80,110,60,150,130,70,6,True
798,HoopaHoopa Unbound,Psychic,80,160,60,170,130,80,6,True
799,Volcanion,Fire,80,110,120,130,90,70,6,True

In [10]:
df.sort_values(by='HP')

,Name,Type 1,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
316,Shedinja,Bug,1,90,45,30,30,40,3,False
55,Diglett,Ground,10,55,25,35,45,95,1,False
139,Magikarp,Water,20,10,55,15,20,80,1,False
388,Duskull,Ghost,20,40,90,30,90,25,3,False
487,Mime Jr.,Psychic,20,25,45,70,90,60,4,False
...,...,...,...,...,...,...,...,...,...,...
655,Alomomola,Water,165,75,80,40,45,65,5,False
351,Wailord,Water,170,90,45,90,45,60,3,False
217,Wobbuffet,Psychic,190,33,58,33,58,33,2,False
121,Chansey,Normal,250,5,5,35,105,50,1,False
261,Blissey,Normal,255,10,10,75,135,55,2,False

## it sort the values in ascending order

In [11]:
df.sort_values(by='HP',ascending=False)

,Name,Type 1,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
261,Blissey,Normal,255,10,10,75,135,55,2,False
121,Chansey,Normal,250,5,5,35,105,50,1,False
217,Wobbuffet,Psychic,190,33,58,33,58,33,2,False
351,Wailord,Water,170,90,45,90,45,60,3,False
655,Alomomola,Water,165,75,80,40,45,65,5,False
...,...,...,...,...,...,...,...,...,...,...
139,Magikarp,Water,20,10,55,15,20,80,1,False
381,Feebas,Water,20,15,20,10,55,80,3,False
388,Duskull,Ghost,20,40,90,30,90,25,3,False
55,Diglett,Ground,10,55,25,35,45,95,1,False
316,Shedinja,Bug,1,90,45,30,30,40,3,False

In [17]:
df.sort_values(by='HP',ascending=False)

,Name,Type 1,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
261,Blissey,Normal,255,10,10,75,135,55,2,False
121,Chansey,Normal,250,5,5,35,105,50,1,False
217,Wobbuffet,Psychic,190,33,58,33,58,33,2,False
351,Wailord,Water,170,90,45,90,45,60,3,False
655,Alomomola,Water,165,75,80,40,45,65,5,False
...,...,...,...,...,...,...,...,...,...,...
139,Magikarp,Water,20,10,55,15,20,80,1,False
381,Feebas,Water,20,15,20,10,55,80,3,False
388,Duskull,Ghost,20,40,90,30,90,25,3,False
55,Diglett,Ground,10,55,25,35,45,95,1,False
316,Shedinja,Bug,1,90,45,30,30,40,3,False

In [30]:
df.sort_values(by='HP')

,Name,Type 1,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
316,Shedinja,Bug,1,90,45,30,30,40,3,False
55,Diglett,Ground,10,55,25,35,45,95,1,False
139,Magikarp,Water,20,10,55,15,20,80,1,False
388,Duskull,Ghost,20,40,90,30,90,25,3,False
487,Mime Jr.,Psychic,20,25,45,70,90,60,4,False
...,...,...,...,...,...,...,...,...,...,...
655,Alomomola,Water,165,75,80,40,45,65,5,False
351,Wailord,Water,170,90,45,90,45,60,3,False
217,Wobbuffet,Psychic,190,33,58,33,58,33,2,False
121,Chansey,Normal,250,5,5,35,105,50,1,False
261,Blissey,Normal,255,10,10,75,135,55,2,False

In [31]:
df.sort_values(by='HP',ascending=False)

,Name,Type 1,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
261,Blissey,Normal,255,10,10,75,135,55,2,False
121,Chansey,Normal,250,5,5,35,105,50,1,False
217,Wobbuffet,Psychic,190,33,58,33,58,33,2,False
351,Wailord,Water,170,90,45,90,45,60,3,False
655,Alomomola,Water,165,75,80,40,45,65,5,False
...,...,...,...,...,...,...,...,...,...,...
139,Magikarp,Water,20,10,55,15,20,80,1,False
381,Feebas,Water,20,15,20,10,55,80,3,False
388,Duskull,Ghost,20,40,90,30,90,25,3,False
55,Diglett,Ground,10,55,25,35,45,95,1,False
316,Shedinja,Bug,1,90,45,30,30,40,3,False

In [32]:
df.sort_values(by=['Speed','HP'])

,Name,Type 1,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
230,Shuckle,Bug,20,10,230,10,230,5,2,False
495,Munchlax,Normal,135,85,40,40,85,5,4,False
658,Ferroseed,Grass,44,50,91,24,86,10,5,False
359,Trapinch,Ground,45,100,45,45,45,10,3,False
486,Bonsly,Rock,50,80,95,10,45,10,4,False
...,...,...,...,...,...,...,...,...,...,...
429,DeoxysAttack Forme,Psychic,50,180,20,180,20,150,3,True
71,AlakazamMega Alakazam,Psychic,55,50,65,175,95,150,1,False
154,AerodactylMega Aerodactyl,Rock,80,135,85,70,95,150,1,False
315,Ninjask,Bug,61,90,45,50,50,160,3,False
431,DeoxysSpeed Forme,Psychic,50,95,90,95,90,180,3,True

In [19]:
df.sort_values(by=['Speed','HP'],ascending=[False,False])

,Name,Type 1,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
431,DeoxysSpeed Forme,Psychic,50,95,90,95,90,180,3,True
315,Ninjask,Bug,61,90,45,50,50,160,3,False
154,AerodactylMega Aerodactyl,Rock,80,135,85,70,95,150,1,False
71,AlakazamMega Alakazam,Psychic,55,50,65,175,95,150,1,False
428,DeoxysNormal Forme,Psychic,50,150,50,150,50,150,3,True
...,...,...,...,...,...,...,...,...,...,...
486,Bonsly,Rock,50,80,95,10,45,10,4,False
359,Trapinch,Ground,45,100,45,45,45,10,3,False
658,Ferroseed,Grass,44,50,91,24,86,10,5,False
495,Munchlax,Normal,135,85,40,40,85,5,4,False
230,Shuckle,Bug,20,10,230,10,230,5,2,False

In [37]:
df.sort_values(by=['HP','Speed'],ascending=[False,True])

,Name,Type 1,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
261,Blissey,Normal,255,10,10,75,135,55,2,False
121,Chansey,Normal,250,5,5,35,105,50,1,False
217,Wobbuffet,Psychic,190,33,58,33,58,33,2,False
351,Wailord,Water,170,90,45,90,45,60,3,False
655,Alomomola,Water,165,75,80,40,45,65,5,False
...,...,...,...,...,...,...,...,...,...,...
487,Mime Jr.,Psychic,20,25,45,70,90,60,4,False
139,Magikarp,Water,20,10,55,15,20,80,1,False
381,Feebas,Water,20,15,20,10,55,80,3,False
55,Diglett,Ground,10,55,25,35,45,95,1,False
316,Shedinja,Bug,1,90,45,30,30,40,3,False

In [76]:
df.sort_values(by='Attack')

,Name,Type 1,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
488,Happiny,Normal,100,5,5,15,65,30,4,False
121,Chansey,Normal,250,5,5,35,105,50,1,False
230,Shuckle,Bug,20,10,230,10,230,5,2,False
261,Blissey,Normal,255,10,10,75,135,55,2,False
139,Magikarp,Water,20,10,55,15,20,80,1,False
...,...,...,...,...,...,...,...,...,...,...
429,DeoxysAttack Forme,Psychic,50,180,20,180,20,150,3,True
426,RayquazaMega Rayquaza,Dragon,105,180,100,180,100,115,3,True
424,GroudonPrimal Groudon,Ground,100,180,160,150,90,90,3,True
232,HeracrossMega Heracross,Bug,80,185,115,40,105,75,2,False
163,MewtwoMega Mewtwo X,Psychic,106,190,100,154,100,130,1,True

In [78]:
df.sort_values(by='Attack',ascending=False)

,Name,Type 1,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
163,MewtwoMega Mewtwo X,Psychic,106,190,100,154,100,130,1,True
232,HeracrossMega Heracross,Bug,80,185,115,40,105,75,2,False
424,GroudonPrimal Groudon,Ground,100,180,160,150,90,90,3,True
426,RayquazaMega Rayquaza,Dragon,105,180,100,180,100,115,3,True
429,DeoxysAttack Forme,Psychic,50,180,20,180,20,150,3,True
...,...,...,...,...,...,...,...,...,...,...
139,Magikarp,Water,20,10,55,15,20,80,1,False
261,Blissey,Normal,255,10,10,75,135,55,2,False
230,Shuckle,Bug,20,10,230,10,230,5,2,False
121,Chansey,Normal,250,5,5,35,105,50,1,False
488,Happiny,Normal,100,5,5,15,65,30,4,False

In [80]:
df.sort_values(by='Name')

,Name,Type 1,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
510,Abomasnow,Grass,90,92,75,92,85,60,4,False
511,AbomasnowMega Abomasnow,Grass,90,132,105,132,105,30,4,False
68,Abra,Psychic,25,20,15,105,55,90,1,False
392,Absol,Dark,65,130,60,75,60,75,3,False
393,AbsolMega Absol,Dark,65,150,60,115,60,115,3,False
...,...,...,...,...,...,...,...,...,...,...
632,Zoroark,Dark,60,105,60,120,60,105,5,False
631,Zorua,Dark,40,65,40,80,40,65,5,False
46,Zubat,Poison,40,45,35,30,40,55,1,False
695,Zweilous,Dark,72,85,70,65,70,58,5,False
794,Zygarde50% Forme,Dragon,108,100,121,81,95,95,6,True

In [90]:
df.sort_values(by='Name',ascending=False)

,Name,Type 1,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
794,Zygarde50% Forme,Dragon,108,100,121,81,95,95,6,True
695,Zweilous,Dark,72,85,70,65,70,58,5,False
46,Zubat,Poison,40,45,35,30,40,55,1,False
631,Zorua,Dark,40,65,40,80,40,65,5,False
632,Zoroark,Dark,60,105,60,120,60,105,5,False
...,...,...,...,...,...,...,...,...,...,...
393,AbsolMega Absol,Dark,65,150,60,115,60,115,3,False
392,Absol,Dark,65,130,60,75,60,75,3,False
68,Abra,Psychic,25,20,15,105,55,90,1,False
511,AbomasnowMega Abomasnow,Grass,90,132,105,132,105,30,4,False
510,Abomasnow,Grass,90,92,75,92,85,60,4,False

In [21]:
df.sort_values(by=['Attack','Defense'])

,Name,Type 1,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
121,Chansey,Normal,250,5,5,35,105,50,1,False
488,Happiny,Normal,100,5,5,15,65,30,4,False
261,Blissey,Normal,255,10,10,75,135,55,2,False
139,Magikarp,Water,20,10,55,15,20,80,1,False
230,Shuckle,Bug,20,10,230,10,230,5,2,False
...,...,...,...,...,...,...,...,...,...,...
429,DeoxysAttack Forme,Psychic,50,180,20,180,20,150,3,True
426,RayquazaMega Rayquaza,Dragon,105,180,100,180,100,115,3,True
424,GroudonPrimal Groudon,Ground,100,180,160,150,90,90,3,True
232,HeracrossMega Heracross,Bug,80,185,115,40,105,75,2,False
163,MewtwoMega Mewtwo X,Psychic,106,190,100,154,100,130,1,True

In [98]:
df.sort_values(by=['Defense','Attack'],ascending=[False,False])

,Name,Type 1,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
333,AggronMega Aggron,Steel,70,140,230,60,80,50,3,False
224,SteelixMega Steelix,Steel,75,125,230,55,95,30,2,False
230,Shuckle,Bug,20,10,230,10,230,5,2,False
414,Regirock,Rock,80,100,200,50,100,50,3,True
223,Steelix,Steel,75,85,200,55,65,30,2,False
...,...,...,...,...,...,...,...,...,...,...
257,Smoochum,Ice,45,30,15,85,65,65,2,False
68,Abra,Psychic,25,20,15,105,55,90,1,False
261,Blissey,Normal,255,10,10,75,135,55,2,False
121,Chansey,Normal,250,5,5,35,105,50,1,False
488,Happiny,Normal,100,5,5,15,65,30,4,False

In [100]:
df.sort_values(by=['Defense','Attack'],ascending=[True,False])

,Name,Type 1,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
121,Chansey,Normal,250,5,5,35,105,50,1,False
488,Happiny,Normal,100,5,5,15,65,30,4,False
261,Blissey,Normal,255,10,10,75,135,55,2,False
186,Pichu,Electric,20,40,15,35,35,60,2,False
188,Igglybuff,Normal,90,30,15,40,20,15,2,False
...,...,...,...,...,...,...,...,...,...,...
414,Regirock,Rock,80,100,200,50,100,50,3,True
223,Steelix,Steel,75,85,200,55,65,30,2,False
333,AggronMega Aggron,Steel,70,140,230,60,80,50,3,False
224,SteelixMega Steelix,Steel,75,125,230,55,95,30,2,False
230,Shuckle,Bug,20,10,230,10,230,5,2,False

In [37]:
df.sort_values(['Attack'])
#df.sort_values(by='Attack')

,Name,Type 1,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
488,Happiny,Normal,100,5,5,15,65,30,4,False
121,Chansey,Normal,250,5,5,35,105,50,1,False
230,Shuckle,Bug,20,10,230,10,230,5,2,False
261,Blissey,Normal,255,10,10,75,135,55,2,False
139,Magikarp,Water,20,10,55,15,20,80,1,False
...,...,...,...,...,...,...,...,...,...,...
429,DeoxysAttack Forme,Psychic,50,180,20,180,20,150,3,True
426,RayquazaMega Rayquaza,Dragon,105,180,100,180,100,115,3,True
424,GroudonPrimal Groudon,Ground,100,180,160,150,90,90,3,True
232,HeracrossMega Heracross,Bug,80,185,115,40,105,75,2,False
163,MewtwoMega Mewtwo X,Psychic,106,190,100,154,100,130,1,True

In [38]:
df['Attack'].min()

5

## it sort the values in descending order

In [115]:
df.sort_values(['Name'],ascending=False)

,Name,Type 1,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
794,zygarde50% forme,dragon,108,100,121,81,95,95,6,True
695,zweilous,dark,72,85,70,65,70,58,5,False
46,zubat,poison,40,45,35,30,40,55,1,False
631,zorua,dark,40,65,40,80,40,65,5,False
632,zoroark,dark,60,105,60,120,60,105,5,False
...,...,...,...,...,...,...,...,...,...,...
393,absolmega absol,dark,65,150,60,115,60,115,3,False
392,absol,dark,65,130,60,75,60,75,3,False
68,abra,psychic,25,20,15,105,55,90,1,False
511,abomasnowmega abomasnow,grass,90,132,105,132,105,30,4,False
510,abomasnow,grass,90,92,75,92,85,60,4,False

In [116]:
df.sort_values(['Attack'],ascending=False)

,Name,Type 1,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
163,mewtwomega mewtwo x,psychic,106,190,100,154,100,130,1,True
232,heracrossmega heracross,bug,80,185,115,40,105,75,2,False
424,groudonprimal groudon,ground,100,180,160,150,90,90,3,True
426,rayquazamega rayquaza,dragon,105,180,100,180,100,115,3,True
429,deoxysattack forme,psychic,50,180,20,180,20,150,3,True
...,...,...,...,...,...,...,...,...,...,...
139,magikarp,water,20,10,55,15,20,80,1,False
261,blissey,normal,255,10,10,75,135,55,2,False
230,shuckle,bug,20,10,230,10,230,5,2,False
121,chansey,normal,250,5,5,35,105,50,1,False
488,happiny,normal,100,5,5,15,65,30,4,False

## when two columns name is given then it sort the values according to the first column

In [69]:
df.sort_values(["Attack","Name"])

,Name,Type 1,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
121,Chansey,Normal,250,5,5,35,105,50,1,False
488,Happiny,Normal,100,5,5,15,65,30,4,False
261,Blissey,Normal,255,10,10,75,135,55,2,False
139,Magikarp,Water,20,10,55,15,20,80,1,False
230,Shuckle,Bug,20,10,230,10,230,5,2,False
...,...,...,...,...,...,...,...,...,...,...
429,DeoxysAttack Forme,Psychic,50,180,20,180,20,150,3,True
424,GroudonPrimal Groudon,Ground,100,180,160,150,90,90,3,True
426,RayquazaMega Rayquaza,Dragon,105,180,100,180,100,115,3,True
232,HeracrossMega Heracross,Bug,80,185,115,40,105,75,2,False
163,MewtwoMega Mewtwo X,Psychic,106,190,100,154,100,130,1,True

In [126]:
L=[5,5,10,10,10]
l2=[100,5,27,56,100]

In [128]:
d=pd.DataFrame({'x':L,'y':l2})
d

    x    y
0   5  100
1   5    5
2  10   27
3  10   56
4  10  100

In [130]:
d.sort_values(by=['x','y'],ascending=[True,True])

    x    y
1   5    5
0   5  100
2  10   27
3  10   56
4  10  100

In [131]:
d.sort_values(by=['x','y'],ascending=[False,False])

    x    y
4  10  100
3  10   56
2  10   27
0   5  100
1   5    5

In [132]:
d.sort_values(by=['x','y'],ascending=[True,False])

    x    y
0   5  100
1   5    5
4  10  100
3  10   56
2  10   27

In [133]:
d.sort_values(by=['x','y'],ascending=[False,True])

    x    y
2  10   27
3  10   56
4  10  100
1   5    5
0   5  100

In [17]:
df.iloc[0:,2:8]

     HP  Attack  Defense  Sp. Atk  Sp. Def  Speed
0    45      49       49       65       65     45
1    60      62       63       80       80     60
2    80      82       83      100      100     80
3    80     100      123      122      120     80
4    39      52       43       60       50     65
..   ..     ...      ...      ...      ...    ...
795  50     100      150      100      150     50
796  50     160      110      160      110    110
797  80     110       60      150      130     70
798  80     160       60      170      130     80
799  80     110      120      130       90     70

[800 rows x 6 columns]

In [60]:
df['Total']=df.iloc[0:,2:8].sum(axis=1)

In [61]:
df

,Name,Type 1,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,Bulbasaur,Grass,45,49,49,65,65,45,1,False,318
1,Ivysaur,Grass,60,62,63,80,80,60,1,False,405
2,Venusaur,Grass,80,82,83,100,100,80,1,False,525
3,VenusaurMega Venusaur,Grass,80,100,123,122,120,80,1,False,625
4,Charmander,Fire,39,52,43,60,50,65,1,False,309
...,...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,50,100,150,100,150,50,6,True,600
796,DiancieMega Diancie,Rock,50,160,110,160,110,110,6,True,700
797,HoopaHoopa Confined,Psychic,80,110,60,150,130,70,6,True,600
798,HoopaHoopa Unbound,Psychic,80,160,60,170,130,80,6,True,680
799,Volcanion,Fire,80,110,120,130,90,70,6,True,600

In [48]:
col=list(df.columns)
col

['Name',
 'Type 1',
 'HP',
 'Attack',
 'Defense',
 'Sp. Atk',
 'Sp. Def',
 'Speed',
 'Generation',
 'Legendary',
 'Total']

In [43]:
[col[-1]]

['Total']

In [50]:
df=df[col[0:2]+[col[-1]]+col[2:10]]

In [51]:
df

,Name,Type 1,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,318,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,405,60,62,63,80,80,60,1,False
2,Venusaur,Grass,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,600,50,100,150,100,150,50,6,True
796,DiancieMega Diancie,Rock,700,50,160,110,160,110,110,6,True
797,HoopaHoopa Confined,Psychic,600,80,110,60,150,130,70,6,True
798,HoopaHoopa Unbound,Psychic,680,80,160,60,170,130,80,6,True
799,Volcanion,Fire,600,80,110,120,130,90,70,6,True

In [58]:
df.columns

Index(['Name', 'Type 1', 'HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def',
       'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [63]:
df=df[['Name', 'Type 1',  'Total','HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def',
       'Speed', 'Generation', 'Legendary']]
df

,Name,Type 1,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,318,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,405,60,62,63,80,80,60,1,False
2,Venusaur,Grass,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,600,50,100,150,100,150,50,6,True
796,DiancieMega Diancie,Rock,700,50,160,110,160,110,110,6,True
797,HoopaHoopa Confined,Psychic,600,80,110,60,150,130,70,6,True
798,HoopaHoopa Unbound,Psychic,680,80,160,60,170,130,80,6,True
799,Volcanion,Fire,600,80,110,120,130,90,70,6,True

In [64]:
df

,Name,Type 1,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,318,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,405,60,62,63,80,80,60,1,False
2,Venusaur,Grass,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,600,50,100,150,100,150,50,6,True
796,DiancieMega Diancie,Rock,700,50,160,110,160,110,110,6,True
797,HoopaHoopa Confined,Psychic,600,80,110,60,150,130,70,6,True
798,HoopaHoopa Unbound,Psychic,680,80,160,60,170,130,80,6,True
799,Volcanion,Fire,600,80,110,120,130,90,70,6,True

In [77]:
df[df['Type 1']=='Rock']

,Name,Type 1,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
80,Geodude,Rock,300,40,80,100,30,30,20,1,False
81,Graveler,Rock,390,55,95,115,45,45,35,1,False
82,Golem,Rock,495,80,120,130,55,65,45,1,False
103,Onix,Rock,385,35,45,160,30,45,70,1,False
149,Omanyte,Rock,355,35,40,100,90,55,35,1,False
150,Omastar,Rock,495,70,60,125,115,70,55,1,False
151,Kabuto,Rock,355,30,80,90,55,45,55,1,False
152,Kabutops,Rock,495,60,115,105,65,70,80,1,False
153,Aerodactyl,Rock,515,80,105,65,60,75,130,1,False
154,AerodactylMega Aerodactyl,Rock,615,80,135,85,70,95,150,1,False
200,Sudowoodo,Rock,410,70,100,115,30,65,30,2,False
265,Larvitar,Rock,300,50,64,50,45,50,41,2,False
266,Pupitar,Rock,410,70,84,70,65,70,51,2,False
267,Tyranitar,Rock,600,100,134,110,95,100,61,2,False
268,TyranitarMega Tyranitar,Rock,700,100,164,150,95,120,71,2,False
323,Nosepass,Rock,375,30,45,135,45,90,30,3,False
369,Lunatone,Rock,440,70,55,65,95,85,70,3,False
370,Solrock,Rock,440,70,95,85,55,65,70,3,False
377,Lileep,Rock,355,66,41,77,61,87,23,3,False
378,Cradily,Rock,495,86,81,97,81,107,43,3,False
379,Anorith,Rock,355,45,95,50,40,50,75,3,False
380,Armaldo,Rock,495,75,125,100,70,80,45,3,False
414,Regirock,Rock,580,80,100,200,50,100,50,3,True
453,Cranidos,Rock,350,67,125,40,30,30,58,4,False
454,Rampardos,Rock,495,97,165,60,65,50,58,4,False
455,Shieldon,Rock,350,30,42,118,42,88,30,4,False
456,Bastiodon,Rock,495,60,52,168,47,138,30,4,False
486,Bonsly,Rock,290,50,80,95,10,45,10,4,False
528,Probopass,Rock,525,60,55,145,75,150,40,4,False
583,Roggenrola,Rock,280,55,75,85,25,25,15,5,False
584,Boldore,Rock,390,70,105,105,50,40,20,5,False
585,Gigalith,Rock,515,85,135,130,60,80,25,5,False
627,Archen,Rock,401,55,112,45,74,45,70,5,False
628,Archeops,Rock,567,75,140,65,112,65,110,5,False
700,Terrakion,Rock,580,91,129,90,72,90,108,5,True
758,Binacle,Rock,306,42,52,67,39,56,50,6,False
759,Barbaracle,Rock,500,72,105,115,54,86,68,6,False
766,Tyrunt,Rock,362,58,89,77,45,45,48,6,False
767,Tyrantrum,Rock,521,82,121,119,69,59,71,6,False
768,Amaura,Rock,362,77,59,50,67,63,46,6,False
769,Aurorus,Rock,521,123,77,72,99,92,58,6,False
773,Carbink,Rock,500,50,50,150,50,150,50,6,False
795,Diancie,Rock,600,50,100,150,100,150,50,6,True
796,DiancieMega Diancie,Rock,700,50,160,110,160,110,110,6,True

In [76]:
df[df['Attack']>160]

,Name,Type 1,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
163,MewtwoMega Mewtwo X,Psychic,780,106,190,100,154,100,130,1,True
232,HeracrossMega Heracross,Bug,600,80,185,115,40,105,75,2,False
268,TyranitarMega Tyranitar,Rock,700,100,164,150,95,120,71,2,False
387,BanetteMega Banette,Ghost,555,64,165,75,93,83,75,3,False
424,GroudonPrimal Groudon,Ground,770,100,180,160,150,90,90,3,True
426,RayquazaMega Rayquaza,Dragon,780,105,180,100,180,100,115,3,True
429,DeoxysAttack Forme,Psychic,600,50,180,20,180,20,150,3,True
454,Rampardos,Rock,495,97,165,60,65,50,58,4,False
494,GarchompMega Garchomp,Dragon,700,108,170,115,120,95,92,4,False
527,GalladeMega Gallade,Psychic,618,68,165,95,65,115,110,4,False
711,KyuremBlack Kyurem,Dragon,700,125,170,100,120,90,95,5,True

In [85]:
df[(df['Type 1']=='Flying') | (df['Type 1']=='Fairy')]

,Name,Type 1,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
40,Clefairy,Fairy,323,70,45,48,60,65,35,1,False
41,Clefable,Fairy,483,95,70,73,95,90,60,1,False
187,Cleffa,Fairy,218,50,25,28,45,55,15,2,False
189,Togepi,Fairy,245,35,20,65,40,65,20,2,False
190,Togetic,Fairy,405,55,40,85,80,105,40,2,False
225,Snubbull,Fairy,300,60,80,50,40,40,30,2,False
226,Granbull,Fairy,450,90,120,75,60,60,45,2,False
519,Togekiss,Fairy,545,85,50,95,120,115,80,4,False
702,TornadusIncarnate Forme,Flying,580,79,115,70,125,80,111,5,True
703,TornadusTherian Forme,Flying,580,79,100,80,110,90,121,5,True
737,Flabébé,Fairy,303,44,38,39,61,79,42,6,False
738,Floette,Fairy,371,54,45,47,75,98,52,6,False
739,Florges,Fairy,552,78,65,68,112,154,75,6,False
752,Spritzee,Fairy,341,78,52,60,63,65,23,6,False
753,Aromatisse,Fairy,462,101,72,72,99,89,29,6,False
754,Swirlix,Fairy,341,62,48,66,59,57,49,6,False
755,Slurpuff,Fairy,480,82,80,86,85,75,72,6,False
770,Sylveon,Fairy,525,95,65,65,110,130,60,6,False
790,Noibat,Flying,245,40,30,35,45,40,55,6,False
791,Noivern,Flying,535,85,70,80,97,80,123,6,False
792,Xerneas,Fairy,680,126,131,95,131,98,99,6,True

In [83]:
df[(df['Type 1']!='Rock') & (df['Total']!=500)]

,Name,Type 1,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,318,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,405,60,62,63,80,80,60,1,False
2,Venusaur,Grass,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
793,Yveltal,Dark,680,126,131,95,131,98,99,6,True
794,Zygarde50% Forme,Dragon,600,108,100,121,81,95,95,6,True
797,HoopaHoopa Confined,Psychic,600,80,110,60,150,130,70,6,True
798,HoopaHoopa Unbound,Psychic,680,80,160,60,170,130,80,6,True
799,Volcanion,Fire,600,80,110,120,130,90,70,6,True

## here it shows both column in descending order

In [108]:
df.sort_values(["Attack",'Name'],ascending=[True,False])

,Name,Type 1,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
488,Happiny,Normal,100,5,5,15,65,30,4,False
121,Chansey,Normal,250,5,5,35,105,50,1,False
230,Shuckle,Bug,20,10,230,10,230,5,2,False
139,Magikarp,Water,20,10,55,15,20,80,1,False
261,Blissey,Normal,255,10,10,75,135,55,2,False
...,...,...,...,...,...,...,...,...,...,...
426,RayquazaMega Rayquaza,Dragon,105,180,100,180,100,115,3,True
424,GroudonPrimal Groudon,Ground,100,180,160,150,90,90,3,True
429,DeoxysAttack Forme,Psychic,50,180,20,180,20,150,3,True
232,HeracrossMega Heracross,Bug,80,185,115,40,105,75,2,False
163,MewtwoMega Mewtwo X,Psychic,106,190,100,154,100,130,1,True

In [110]:
df.sort_values(["Attack",'Name'],ascending=[True,True])

,Name,Type 1,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
121,Chansey,Normal,250,5,5,35,105,50,1,False
488,Happiny,Normal,100,5,5,15,65,30,4,False
261,Blissey,Normal,255,10,10,75,135,55,2,False
139,Magikarp,Water,20,10,55,15,20,80,1,False
230,Shuckle,Bug,20,10,230,10,230,5,2,False
...,...,...,...,...,...,...,...,...,...,...
429,DeoxysAttack Forme,Psychic,50,180,20,180,20,150,3,True
424,GroudonPrimal Groudon,Ground,100,180,160,150,90,90,3,True
426,RayquazaMega Rayquaza,Dragon,105,180,100,180,100,115,3,True
232,HeracrossMega Heracross,Bug,80,185,115,40,105,75,2,False
163,MewtwoMega Mewtwo X,Psychic,106,190,100,154,100,130,1,True

## here it shows both column in ascending order¶

In [34]:
df.sort_values(["Type 1","Attack"])

,Name,Type 1,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
230,Shuckle,Bug,20,10,230,10,230,5,2,False
14,Metapod,Bug,50,20,55,25,25,30,1,False
179,Ledyba,Bug,40,20,30,40,80,55,2,False
733,Spewpa,Bug,45,22,60,27,30,29,6,False
17,Kakuna,Bug,45,25,50,25,25,35,1,False
...,...,...,...,...,...,...,...,...,...,...
107,Kingler,Water,55,130,115,50,50,75,1,False
349,SharpedoMega Sharpedo,Water,70,140,70,110,65,105,3,False
283,SwampertMega Swampert,Water,100,150,110,95,110,70,3,False
422,KyogrePrimal Kyogre,Water,100,150,90,180,160,90,3,True
141,GyaradosMega Gyarados,Water,95,155,109,70,130,81,1,False

In [25]:
df['total'] = df.iloc[:,2:-2].sum(axis=1)

In [26]:
df

,Name,Type 1,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,total
0,Bulbasaur,Grass,45,49,49,65,65,45,1,False,318
1,Ivysaur,Grass,60,62,63,80,80,60,1,False,405
2,Venusaur,Grass,80,82,83,100,100,80,1,False,525
3,VenusaurMega Venusaur,Grass,80,100,123,122,120,80,1,False,625
4,Charmander,Fire,39,52,43,60,50,65,1,False,309
...,...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,50,100,150,100,150,50,6,True,600
796,DiancieMega Diancie,Rock,50,160,110,160,110,110,6,True,700
797,HoopaHoopa Confined,Psychic,80,110,60,150,130,70,6,True,600
798,HoopaHoopa Unbound,Psychic,80,160,60,170,130,80,6,True,680
799,Volcanion,Fire,80,110,120,130,90,70,6,True,600

In [27]:
df.columns

Index(['Name', 'Type 1', 'HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def',
       'Speed', 'Generation', 'Legendary', 'total'],
      dtype='object')

In [31]:
df=df[['Name', 'Type 1','total', 'HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def',
       'Speed', 'Generation', 'Legendary', ]]
df

,Name,Type 1,total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,318,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,405,60,62,63,80,80,60,1,False
2,Venusaur,Grass,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,600,50,100,150,100,150,50,6,True
796,DiancieMega Diancie,Rock,700,50,160,110,160,110,110,6,True
797,HoopaHoopa Confined,Psychic,600,80,110,60,150,130,70,6,True
798,HoopaHoopa Unbound,Psychic,680,80,160,60,170,130,80,6,True
799,Volcanion,Fire,600,80,110,120,130,90,70,6,True

In [44]:
df[(df['Type 1']=='Fairy') & (df['Attack']>100)]

,Name,Type 1,total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
226,Granbull,Fairy,450,90,120,75,60,60,45,2,False
792,Xerneas,Fairy,680,126,131,95,131,98,99,6,True

In [41]:
df['total']=df.iloc[:,2:8].sum(axis=1)
df

,Name,Type 1,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,total
0,Bulbasaur,Grass,45,49,49,65,65,45,1,False,318
1,Ivysaur,Grass,60,62,63,80,80,60,1,False,405
2,Venusaur,Grass,80,82,83,100,100,80,1,False,525
3,VenusaurMega Venusaur,Grass,80,100,123,122,120,80,1,False,625
4,Charmander,Fire,39,52,43,60,50,65,1,False,309
...,...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,50,100,150,100,150,50,6,True,600
796,DiancieMega Diancie,Rock,50,160,110,160,110,110,6,True,700
797,HoopaHoopa Confined,Psychic,80,110,60,150,130,70,6,True,600
798,HoopaHoopa Unbound,Psychic,80,160,60,170,130,80,6,True,680
799,Volcanion,Fire,80,110,120,130,90,70,6,True,600

In [139]:
df

,Name,Type 1,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,60,62,63,80,80,60,1,False
2,Venusaur,Grass,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,80,100,123,122,120,80,1,False
4,Charmander,Fire,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,50,100,150,100,150,50,6,True
796,DiancieMega Diancie,Rock,50,160,110,160,110,110,6,True
797,HoopaHoopa Confined,Psychic,80,110,60,150,130,70,6,True
798,HoopaHoopa Unbound,Psychic,80,160,60,170,130,80,6,True
799,Volcanion,Fire,80,110,120,130,90,70,6,True

In [42]:
df.columns

Index(['Name', 'Type 1', 'HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def',
       'Speed', 'Generation', 'Legendary', 'total'],
      dtype='object')

In [45]:
df=df[['Name', 'Type 1', 'total','HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def',
       'Speed', 'Generation', 'Legendary']]
df

,Name,Type 1,total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,318,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,405,60,62,63,80,80,60,1,False
2,Venusaur,Grass,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,600,50,100,150,100,150,50,6,True
796,DiancieMega Diancie,Rock,700,50,160,110,160,110,110,6,True
797,HoopaHoopa Confined,Psychic,600,80,110,60,150,130,70,6,True
798,HoopaHoopa Unbound,Psychic,680,80,160,60,170,130,80,6,True
799,Volcanion,Fire,600,80,110,120,130,90,70,6,True

In [50]:
df[df['Type 1']=='Flying']

,Name,Type 1,total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
702,TornadusIncarnate Forme,Flying,580,79,115,70,125,80,111,5,True
703,TornadusTherian Forme,Flying,580,79,100,80,110,90,121,5,True
790,Noibat,Flying,245,40,30,35,45,40,55,6,False
791,Noivern,Flying,535,85,70,80,97,80,123,6,False

In [54]:
df[df['Attack']>180]

,Name,Type 1,total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
163,MewtwoMega Mewtwo X,Psychic,780,106,190,100,154,100,130,1,True
232,HeracrossMega Heracross,Bug,600,80,185,115,40,105,75,2,False

In [60]:
df[(df['Type 1']=='Fire') & (df['Attack']>100)]

,Name,Type 1,total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
7,CharizardMega Charizard X,Fire,634,78,130,111,130,85,100,1,False
8,CharizardMega Charizard Y,Fire,634,78,104,78,159,115,100,1,False
64,Arcanine,Fire,555,90,110,80,100,80,95,1,False
147,Flareon,Fire,525,65,130,60,95,110,65,1,False
263,Entei,Fire,580,115,115,85,90,75,100,2,True
270,Ho-oh,Fire,680,106,130,90,110,154,90,2,True
278,Blaziken,Fire,530,80,120,70,110,70,80,3,False
279,BlazikenMega Blaziken,Fire,630,80,160,80,130,80,100,3,False
354,CameruptMega Camerupt,Fire,560,70,120,100,145,105,20,3,False
437,Infernape,Fire,534,76,104,71,104,71,108,4,False
559,Emboar,Fire,528,110,123,65,100,65,65,5,False
615,DarmanitanStandard Mode,Fire,480,105,140,55,30,55,95,5,False
799,Volcanion,Fire,600,80,110,120,130,90,70,6,True

In [151]:
df['total']=df.iloc[:,2:8].sum(axis=1)

In [153]:
df

,Name,Type 1,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,total
0,Bulbasaur,Grass,45,49,49,65,65,45,1,False,318
1,Ivysaur,Grass,60,62,63,80,80,60,1,False,405
2,Venusaur,Grass,80,82,83,100,100,80,1,False,525
3,VenusaurMega Venusaur,Grass,80,100,123,122,120,80,1,False,625
4,Charmander,Fire,39,52,43,60,50,65,1,False,309
...,...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,50,100,150,100,150,50,6,True,600
796,DiancieMega Diancie,Rock,50,160,110,160,110,110,6,True,700
797,HoopaHoopa Confined,Psychic,80,110,60,150,130,70,6,True,600
798,HoopaHoopa Unbound,Psychic,80,160,60,170,130,80,6,True,680
799,Volcanion,Fire,80,110,120,130,90,70,6,True,600

In [159]:
col=list(df.columns)
print(col)

['Name', 'Type 1', 'HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary', 'total']

In [201]:
col[2:-1]

['HP',
 'Attack',
 'Defense',
 'Sp. Atk',
 'Sp. Def',
 'Speed',
 'Generation',
 'Legendary']

In [205]:
df[col[0:2]+[col[-1]]+col[2:-1]]

,Name,Type 1,total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,318,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,405,60,62,63,80,80,60,1,False
2,Venusaur,Grass,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,600,50,100,150,100,150,50,6,True
796,DiancieMega Diancie,Rock,700,50,160,110,160,110,110,6,True
797,HoopaHoopa Confined,Psychic,600,80,110,60,150,130,70,6,True
798,HoopaHoopa Unbound,Psychic,680,80,160,60,170,130,80,6,True
799,Volcanion,Fire,600,80,110,120,130,90,70,6,True

In [197]:
[col[-1]]

['total']

In [184]:
df1=df[col[0:2]+[col[-1]]+col[2:-1]]
df1

,Name,Type 1,total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,318,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,405,60,62,63,80,80,60,1,False
2,Venusaur,Grass,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,600,50,100,150,100,150,50,6,True
796,DiancieMega Diancie,Rock,700,50,160,110,160,110,110,6,True
797,HoopaHoopa Confined,Psychic,600,80,110,60,150,130,70,6,True
798,HoopaHoopa Unbound,Psychic,680,80,160,60,170,130,80,6,True
799,Volcanion,Fire,600,80,110,120,130,90,70,6,True

# Making changes to  the Data

In [119]:
# import warnings
# warnings.filterwarnings('ignore')

In [7]:
#Here i am added the columns HP, Attack, Defense, Sp.Atk, Sp.Def,Speed and named it as Total
#first input is going to colon which means all rows everything[:]
#then count the column here HP is the 2 column upto 8 column speed[:,2:8]
#then define the axis along which you want to add here axis=1 means column wise


df['Total']=df.iloc[:,2:8].sum(axis=1)
df

,Name,Type 1,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,Bulbasaur,Grass,45,49,49,65,65,45,1,False,318
1,Ivysaur,Grass,60,62,63,80,80,60,1,False,405
2,Venusaur,Grass,80,82,83,100,100,80,1,False,525
3,VenusaurMega Venusaur,Grass,80,100,123,122,120,80,1,False,625
4,Charmander,Fire,39,52,43,60,50,65,1,False,309
...,...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,50,100,150,100,150,50,6,True,600
796,DiancieMega Diancie,Rock,50,160,110,160,110,110,6,True,700
797,HoopaHoopa Confined,Psychic,80,110,60,150,130,70,6,True,600
798,HoopaHoopa Unbound,Psychic,80,160,60,170,130,80,6,True,680
799,Volcanion,Fire,80,110,120,130,90,70,6,True,600

In [170]:
col=list(df.columns)
col

['Name',
 'Type 1',
 'HP',
 'Attack',
 'Defense',
 'Sp. Atk',
 'Sp. Def',
 'Speed',
 'Generation',
 'Legendary',
 'Total']

In [174]:
df[col[0:5]+[col[-4]]+col[5:7]+col[8:]]

,Name,Type 1,HP,Attack,Defense,Speed,Sp. Atk,Sp. Def,Generation,Legendary,Total
0,bulbasaur,grass,45,49,49,45,65,65,1,False,318
1,ivysaur,grass,60,62,63,60,80,80,1,False,405
2,venusaur,grass,80,82,83,80,100,100,1,False,525
3,venusaurmega venusaur,grass,80,100,123,80,122,120,1,False,625
4,charmander,fire,39,52,43,65,60,50,1,False,309
...,...,...,...,...,...,...,...,...,...,...,...
795,diancie,rock,50,100,150,50,100,150,6,True,600
796,dianciemega diancie,rock,50,160,110,110,160,110,6,True,700
797,hoopahoopa confined,psychic,80,110,60,70,150,130,6,True,600
798,hoopahoopa unbound,psychic,80,160,60,80,170,130,6,True,680
799,volcanion,fire,80,110,120,70,130,90,6,True,600

In [211]:
marks=np.array([[50,80,90,45,33,78,92]])
marks

array([[50, 80, 90, 45, 33, 78, 92]])

In [217]:
marks>70

array([[False,  True,  True, False, False,  True,  True]])

In [215]:
marks[marks>70]

array([80, 90, 78, 92])

In [227]:
df['Type 1']=='Flying'

0      False
1      False
2      False
3      False
4      False
       ...
795    False
796    False
797    False
798    False
799    False
Name: Type 1, Length: 800, dtype: bool

In [9]:
df

,Name,Type 1,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,Bulbasaur,Grass,45,49,49,65,65,45,1,False,318
1,Ivysaur,Grass,60,62,63,80,80,60,1,False,405
2,Venusaur,Grass,80,82,83,100,100,80,1,False,525
3,VenusaurMega Venusaur,Grass,80,100,123,122,120,80,1,False,625
4,Charmander,Fire,39,52,43,60,50,65,1,False,309
...,...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,50,100,150,100,150,50,6,True,600
796,DiancieMega Diancie,Rock,50,160,110,160,110,110,6,True,700
797,HoopaHoopa Confined,Psychic,80,110,60,150,130,70,6,True,600
798,HoopaHoopa Unbound,Psychic,80,160,60,170,130,80,6,True,680
799,Volcanion,Fire,80,110,120,130,90,70,6,True,600

In [35]:
df.groupby(['Type 1'])['Attack'].max().sort_values(ascending=False)

Type 1
Psychic     190
Bug         185
Dragon      180
Ground      180
Ghost       165
Rock        165
Normal      160
Fire        160
Water       155
Dark        150
Steel       150
Fighting    145
Grass       132
Fairy       131
Ice         130
Electric    123
Flying      115
Poison      106
Name: Attack, dtype: int64

In [27]:
df.groupby(['Type 1'])['Attack'].sum().reset_index().sort_values(by='Attack',ascending=False)

      Type 1  Attack
17     Water    8305
12    Normal    7200
9      Grass    5125
0        Bug    4897
6       Fire    4408
15      Rock    4086
14   Psychic    4073
2     Dragon    3588
10    Ground    3064
3   Electric    3040
1       Dark    2740
5   Fighting    2613
16     Steel    2503
8      Ghost    2361
13    Poison    2091
11       Ice    1746
4      Fairy    1046
7     Flying     315

In [51]:
df.groupby(['Type 1'])['Attack'].agg(['sum','min','max','count','mean']).sort_values(by='max',ascending=False).head(1)

          sum  min  max  count      mean
Type 1
Psychic  4073   20  190     57  71.45614

In [55]:
df['Name'].nunique()

800

In [57]:
df.groupby(['Name'])['Attack'].sum()

Name
Abomasnow                   92
AbomasnowMega Abomasnow    132
Abra                        20
Absol                      130
AbsolMega Absol            150
                          ...
Zoroark                    105
Zorua                       65
Zubat                       45
Zweilous                    85
Zygarde50% Forme           100
Name: Attack, Length: 800, dtype: int64

In [53]:
df.groupby(['Type 1','Legendary'])['Attack'].sum()

Type 1    Legendary
Bug       False        4897
Dark      False        2519
          True          221
Dragon    False        2068
          True         1520
Electric  False        2645
          True          395
Fairy     False         915
          True          131
Fighting  False        2613
Fire      False        3863
          True          545
Flying    False         100
          True          215
Ghost     False        2141
          True          220
Grass     False        4832
          True          293
Ground    False        2464
          True          600
Ice       False        1611
          True          135
Normal    False        6920
          True          280
Poison    False        2091
Psychic   False        2363
          True         1710
Rock      False        3597
          True          489
Steel     False        2118
          True          385
Water     False        7860
          True          445
Name: Attack, dtype: int64

In [69]:
df.to_csv('Updated_pokemon.csv',index=False)

In [63]:
import os

In [67]:
os.getcwd()

'C:\\Users\\cipl\\Pandas'

In [241]:
df[df['Type 1']=='Grass']

,Name,Type 1,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,total
0,Bulbasaur,Grass,45,49,49,65,65,45,1,False,318
1,Ivysaur,Grass,60,62,63,80,80,60,1,False,405
2,Venusaur,Grass,80,82,83,100,100,80,1,False,525
3,VenusaurMega Venusaur,Grass,80,100,123,122,120,80,1,False,625
48,Oddish,Grass,45,50,55,75,65,30,1,False,320
...,...,...,...,...,...,...,...,...,...,...,...
718,Chespin,Grass,56,61,65,48,45,38,6,False,313
719,Quilladin,Grass,61,78,95,56,58,57,6,False,405
720,Chesnaught,Grass,88,107,122,74,75,64,6,False,530
740,Skiddo,Grass,66,65,48,62,57,52,6,False,350
741,Gogoat,Grass,123,100,62,97,81,68,6,False,531

In [239]:
df[df['Attack']>=180]

,Name,Type 1,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,total
163,MewtwoMega Mewtwo X,Psychic,106,190,100,154,100,130,1,True,780
232,HeracrossMega Heracross,Bug,80,185,115,40,105,75,2,False,600
424,GroudonPrimal Groudon,Ground,100,180,160,150,90,90,3,True,770
426,RayquazaMega Rayquaza,Dragon,105,180,100,180,100,115,3,True,780
429,DeoxysAttack Forme,Psychic,50,180,20,180,20,150,3,True,600

In [247]:
df[(df['Type 1']=='Grass') & (df['Attack']>120)]

,Name,Type 1,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,total
310,Breloom,Grass,60,130,80,60,60,70,3,False,460
511,AbomasnowMega Abomasnow,Grass,90,132,105,132,105,30,4,False,594

In [78]:
col=list(df.columns)
col

['Name',
 'Type 1',
 'HP',
 'Attack',
 'Defense',
 'Sp. Atk',
 'Sp. Def',
 'Speed',
 'Generation',
 'Legendary',
 'Total']

In [84]:
df[col[0:2]+[col[-1]]+col[2:10]]

,Name,Type 1,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,318,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,405,60,62,63,80,80,60,1,False
2,Venusaur,Grass,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,600,50,100,150,100,150,50,6,True
796,DiancieMega Diancie,Rock,700,50,160,110,160,110,110,6,True
797,HoopaHoopa Confined,Psychic,600,80,110,60,150,130,70,6,True
798,HoopaHoopa Unbound,Psychic,680,80,160,60,170,130,80,6,True
799,Volcanion,Fire,600,80,110,120,130,90,70,6,True

In [18]:
col=list(df.columns)
col

['Name',
 'Type 1',
 'HP',
 'Attack',
 'Defense',
 'Sp. Atk',
 'Sp. Def',
 'Speed',
 'Generation',
 'Legendary',
 'Total']

In [175]:
# Arranging the columns

df=df[col[0:2]+[col[-1]]+col[2:10]]
df

,Name,Type 1,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,bulbasaur,grass,318,45,49,49,65,65,45,1,False
1,ivysaur,grass,405,60,62,63,80,80,60,1,False
2,venusaur,grass,525,80,82,83,100,100,80,1,False
3,venusaurmega venusaur,grass,625,80,100,123,122,120,80,1,False
4,charmander,fire,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
795,diancie,rock,600,50,100,150,100,150,50,6,True
796,dianciemega diancie,rock,700,50,160,110,160,110,110,6,True
797,hoopahoopa confined,psychic,600,80,110,60,150,130,70,6,True
798,hoopahoopa unbound,psychic,680,80,160,60,170,130,80,6,True
799,volcanion,fire,600,80,110,120,130,90,70,6,True

In [178]:
m=np.array([[55,23,70,90,10,30,100]])
p=60

In [181]:
m>p

array([[False, False,  True,  True, False, False,  True]])

In [180]:
m[m>p]

array([ 70,  90, 100])

In [185]:
df

,Name,Type 1,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,bulbasaur,grass,318,45,49,49,65,65,45,1,False
1,ivysaur,grass,405,60,62,63,80,80,60,1,False
2,venusaur,grass,525,80,82,83,100,100,80,1,False
3,venusaurmega venusaur,grass,625,80,100,123,122,120,80,1,False
4,charmander,fire,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
795,diancie,rock,600,50,100,150,100,150,50,6,True
796,dianciemega diancie,rock,700,50,160,110,160,110,110,6,True
797,hoopahoopa confined,psychic,600,80,110,60,150,130,70,6,True
798,hoopahoopa unbound,psychic,680,80,160,60,170,130,80,6,True
799,volcanion,fire,600,80,110,120,130,90,70,6,True

In [197]:
df['Type 1']=='flying'

0      False
1      False
2      False
3      False
4      False
       ...
795    False
796    False
797    False
798    False
799    False
Name: Type 1, Length: 800, dtype: bool

In [204]:
df[df['Type 1']=='flying']

,Name,Type 1,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
702,tornadusincarnate forme,flying,580,79,115,70,125,80,111,5,True
703,tornadustherian forme,flying,580,79,100,80,110,90,121,5,True
790,noibat,flying,245,40,30,35,45,40,55,6,False
791,noivern,flying,535,85,70,80,97,80,123,6,False

In [196]:
df[df['Attack']>180]

,Name,Type 1,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
163,mewtwomega mewtwo x,psychic,780,106,190,100,154,100,130,1,True
232,heracrossmega heracross,bug,600,80,185,115,40,105,75,2,False

In [206]:
df[(df['Type 1']=='flying') & (df['Attack']<100)]

,Name,Type 1,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
790,noibat,flying,245,40,30,35,45,40,55,6,False
791,noivern,flying,535,85,70,80,97,80,123,6,False

In [45]:
df[(df['Type 1']=='Fairy') | (df['Legendary']==True)]

,Name,Type 1,total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
40,Clefairy,Fairy,323,70,45,48,60,65,35,1,False
41,Clefable,Fairy,483,95,70,73,95,90,60,1,False
156,Articuno,Ice,580,90,85,100,95,125,85,1,True
157,Zapdos,Electric,580,90,90,85,125,90,100,1,True
158,Moltres,Fire,580,90,100,90,125,85,90,1,True
...,...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,600,50,100,150,100,150,50,6,True
796,DiancieMega Diancie,Rock,700,50,160,110,160,110,110,6,True
797,HoopaHoopa Confined,Psychic,600,80,110,60,150,130,70,6,True
798,HoopaHoopa Unbound,Psychic,680,80,160,60,170,130,80,6,True
799,Volcanion,Fire,600,80,110,120,130,90,70,6,True

In [251]:
df[(df['Type 1']=='Fairy') | (df['Type 1']=='Flying')]

,Name,Type 1,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,total
40,Clefairy,Fairy,70,45,48,60,65,35,1,False,323
41,Clefable,Fairy,95,70,73,95,90,60,1,False,483
187,Cleffa,Fairy,50,25,28,45,55,15,2,False,218
189,Togepi,Fairy,35,20,65,40,65,20,2,False,245
190,Togetic,Fairy,55,40,85,80,105,40,2,False,405
225,Snubbull,Fairy,60,80,50,40,40,30,2,False,300
226,Granbull,Fairy,90,120,75,60,60,45,2,False,450
519,Togekiss,Fairy,85,50,95,120,115,80,4,False,545
702,TornadusIncarnate Forme,Flying,79,115,70,125,80,111,5,True,580
703,TornadusTherian Forme,Flying,79,100,80,110,90,121,5,True,580
737,Flabébé,Fairy,44,38,39,61,79,42,6,False,303
738,Floette,Fairy,54,45,47,75,98,52,6,False,371
739,Florges,Fairy,78,65,68,112,154,75,6,False,552
752,Spritzee,Fairy,78,52,60,63,65,23,6,False,341
753,Aromatisse,Fairy,101,72,72,99,89,29,6,False,462
754,Swirlix,Fairy,62,48,66,59,57,49,6,False,341
755,Slurpuff,Fairy,82,80,86,85,75,72,6,False,480
770,Sylveon,Fairy,95,65,65,110,130,60,6,False,525
790,Noibat,Flying,40,30,35,45,40,55,6,False,245
791,Noivern,Flying,85,70,80,97,80,123,6,False,535
792,Xerneas,Fairy,126,131,95,131,98,99,6,True,680

In [47]:
df[~(df["Legendary"]==True)]

,Name,Type 1,total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,318,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,405,60,62,63,80,80,60,1,False
2,Venusaur,Grass,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
787,GourgeistSuper Size,Ghost,494,85,100,122,58,75,54,6,False
788,Bergmite,Ice,304,55,69,85,32,35,28,6,False
789,Avalugg,Ice,514,95,117,184,44,46,28,6,False
790,Noibat,Flying,245,40,30,35,45,40,55,6,False
791,Noivern,Flying,535,85,70,80,97,80,123,6,False

In [217]:
df[df["Legendary"]!=True]

,Name,Type 1,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,bulbasaur,grass,318,45,49,49,65,65,45,1,False
1,ivysaur,grass,405,60,62,63,80,80,60,1,False
2,venusaur,grass,525,80,82,83,100,100,80,1,False
3,venusaurmega venusaur,grass,625,80,100,123,122,120,80,1,False
4,charmander,fire,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
787,gourgeistsuper size,ghost,494,85,100,122,58,75,54,6,False
788,bergmite,ice,304,55,69,85,32,35,28,6,False
789,avalugg,ice,514,95,117,184,44,46,28,6,False
790,noibat,flying,245,40,30,35,45,40,55,6,False
791,noivern,flying,535,85,70,80,97,80,123,6,False

In [219]:
df[~(df["Legendary"]==True)]

,Name,Type 1,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,bulbasaur,grass,318,45,49,49,65,65,45,1,False
1,ivysaur,grass,405,60,62,63,80,80,60,1,False
2,venusaur,grass,525,80,82,83,100,100,80,1,False
3,venusaurmega venusaur,grass,625,80,100,123,122,120,80,1,False
4,charmander,fire,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
787,gourgeistsuper size,ghost,494,85,100,122,58,75,54,6,False
788,bergmite,ice,304,55,69,85,32,35,28,6,False
789,avalugg,ice,514,95,117,184,44,46,28,6,False
790,noibat,flying,245,40,30,35,45,40,55,6,False
791,noivern,flying,535,85,70,80,97,80,123,6,False

In [60]:
df.groupby(['Type 1'])['Attack'].sum().sort_values(ascending=False).reset_index()

      Type 1  Attack
0      Water    8305
1     Normal    7200
2      Grass    5125
3        Bug    4897
4       Fire    4408
5       Rock    4086
6    Psychic    4073
7     Dragon    3588
8     Ground    3064
9   Electric    3040
10      Dark    2740
11  Fighting    2613
12     Steel    2503
13     Ghost    2361
14    Poison    2091
15       Ice    1746
16     Fairy    1046
17    Flying     315

In [61]:
df.groupby(['Type 1'])['Attack'].min().reset_index().sort_values(by='Attack',ascending=False)

      Type 1  Attack
2     Dragon      50
1       Dark      50
13    Poison      43
15      Rock      40
10    Ground      40
5   Fighting      35
3   Electric      30
6       Fire      30
7     Flying      30
8      Ghost      30
11       Ice      30
9      Grass      27
16     Steel      24
4      Fairy      20
14   Psychic      20
0        Bug      10
17     Water      10
12    Normal       5

In [62]:
df.groupby(['Type 1'])['Attack'].agg(['sum','mean','min','max','count'])

           sum        mean  min  max  count
Type 1
Bug       4897   70.971014   10  185     69
Dark      2740   88.387097   50  150     31
Dragon    3588  112.125000   50  180     32
Electric  3040   69.090909   30  123     44
Fairy     1046   61.529412   20  131     17
Fighting  2613   96.777778   35  145     27
Fire      4408   84.769231   30  160     52
Flying     315   78.750000   30  115      4
Ghost     2361   73.781250   30  165     32
Grass     5125   73.214286   27  132     70
Ground    3064   95.750000   40  180     32
Ice       1746   72.750000   30  130     24
Normal    7200   73.469388    5  160     98
Poison    2091   74.678571   43  106     28
Psychic   4073   71.456140   20  190     57
Rock      4086   92.863636   40  165     44
Steel     2503   92.703704   24  150     27
Water     8305   74.151786   10  155    112

In [63]:
df.groupby(['Type 1', 'Legendary'])['Attack'].sum()

Type 1    Legendary
Bug       False        4897
Dark      False        2519
          True          221
Dragon    False        2068
          True         1520
Electric  False        2645
          True          395
Fairy     False         915
          True          131
Fighting  False        2613
Fire      False        3863
          True          545
Flying    False         100
          True          215
Ghost     False        2141
          True          220
Grass     False        4832
          True          293
Ground    False        2464
          True          600
Ice       False        1611
          True          135
Normal    False        6920
          True          280
Poison    False        2091
Psychic   False        2363
          True         1710
Rock      False        3597
          True          489
Steel     False        2118
          True          385
Water     False        7860
          True          445
Name: Attack, dtype: int64

In [64]:
df.groupby(['Type 1', 'Legendary'])['Attack'].agg(['sum','max'])

                     sum  max
Type 1   Legendary
Bug      False      4897  185
Dark     False      2519  150
         True        221  131
Dragon   False      2068  170
         True       1520  180
Electric False      2645  123
         True        395  115
Fairy    False       915  120
         True        131  131
Fighting False      2613  145
Fire     False      3863  160
         True        545  130
Flying   False       100   70
         True        215  115
Ghost    False      2141  165
         True        220  120
Grass    False      4832  132
         True        293  103
Ground   False      2464  140
         True        600  180
Ice      False      1611  130
         True        135   85
Normal   False      6920  160
         True        280  160
Poison   False      2091  106
Psychic  False      2363  165
         True       1710  190
Rock     False      3597  165
         True        489  160
Steel    False      2118  150
         True        385  120
Water    False      7860  155
         True        445  150

In [66]:
df.to_csv('update_pokemon.csv',index=False)

In [238]:
df.groupby(['Type 1'])['Attack'].sum().sort_values()

Type 1
flying       315
fairy       1046
ice         1746
poison      2091
ghost       2361
steel       2503
fighting    2613
dark        2740
electric    3040
ground      3064
dragon      3588
psychic     4073
rock        4086
fire        4408
bug         4897
grass       5125
normal      7200
water       8305
Name: Attack, dtype: int64

In [240]:
df.groupby(['Type 1'])['Attack'].agg(['sum','mean','max','min','count']).sort_values(by='mean',ascending=False).reset_index()

      Type 1   sum        mean  max  min  count
0     dragon  3588  112.125000  180   50     32
1   fighting  2613   96.777778  145   35     27
2     ground  3064   95.750000  180   40     32
3       rock  4086   92.863636  165   40     44
4      steel  2503   92.703704  150   24     27
5       dark  2740   88.387097  150   50     31
6       fire  4408   84.769231  160   30     52
7     flying   315   78.750000  115   30      4
8     poison  2091   74.678571  106   43     28
9      water  8305   74.151786  155   10    112
10     ghost  2361   73.781250  165   30     32
11    normal  7200   73.469388  160    5     98
12     grass  5125   73.214286  132   27     70
13       ice  1746   72.750000  130   30     24
14   psychic  4073   71.456140  190   20     57
15       bug  4897   70.971014  185   10     69
16  electric  3040   69.090909  123   30     44
17     fairy  1046   61.529412  131   20     17

In [242]:
df.groupby(['Type 1','Legendary'])['Attack'].sum().reset_index()

      Type 1  Legendary  Attack
0        bug      False    4897
1       dark      False    2519
2       dark       True     221
3     dragon      False    2068
4     dragon       True    1520
5   electric      False    2645
6   electric       True     395
7      fairy      False     915
8      fairy       True     131
9   fighting      False    2613
10      fire      False    3863
11      fire       True     545
12    flying      False     100
13    flying       True     215
14     ghost      False    2141
15     ghost       True     220
16     grass      False    4832
17     grass       True     293
18    ground      False    2464
19    ground       True     600
20       ice      False    1611
21       ice       True     135
22    normal      False    6920
23    normal       True     280
24    poison      False    2091
25   psychic      False    2363
26   psychic       True    1710
27      rock      False    3597
28      rock       True     489
29     steel      False    2118
30     steel       True     385
31     water      False    7860
32     water       True     445

In [244]:
df.to_csv('UPDATED.csv',index=False)

In [246]:
df.describe(include='object')

             Name Type 1
count         800    800
unique        800     18
top     bulbasaur  water
freq            1    112

In [247]:
df['Type 1'].mode()

0    water
Name: Type 1, dtype: object

In [96]:
df.head()

,Name,Type 1,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,318,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,405,60,62,63,80,80,60,1,False
2,Venusaur,Grass,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,309,39,52,43,60,50,65,1,False

In [100]:
a=df[df['Type 1']=='Water']
a

,Name,Type 1,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
9,Squirtle,Water,314,44,48,65,50,64,43,1,False
10,Wartortle,Water,405,59,63,80,65,80,58,1,False
11,Blastoise,Water,530,79,83,100,85,105,78,1,False
12,BlastoiseMega Blastoise,Water,630,79,103,120,135,115,78,1,False
59,Psyduck,Water,320,50,52,48,65,50,55,1,False
...,...,...,...,...,...,...,...,...,...,...,...
724,Froakie,Water,314,41,56,40,62,44,71,6,False
725,Frogadier,Water,405,54,63,52,83,56,97,6,False
726,Greninja,Water,530,72,95,67,103,71,122,6,False
762,Clauncher,Water,330,50,53,62,58,63,44,6,False
763,Clawitzer,Water,500,71,73,88,120,89,59,6,False

In [104]:
a[a['Attack']>100]

,Name,Type 1,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
12,BlastoiseMega Blastoise,Water,630,79,103,120,135,115,78,1,False
106,Krabby,Water,325,30,105,90,25,25,50,1,False
107,Kingler,Water,475,55,130,115,50,50,75,1,False
140,Gyarados,Water,540,95,125,79,60,100,81,1,False
141,GyaradosMega Gyarados,Water,640,95,155,109,70,130,81,1,False
174,Feraligatr,Water,530,85,105,100,79,83,78,2,False
242,Octillery,Water,480,75,105,75,105,75,45,2,False
282,Swampert,Water,535,100,110,90,85,90,60,3,False
283,SwampertMega Swampert,Water,635,100,150,110,95,110,70,3,False
348,Sharpedo,Water,460,70,120,40,95,40,95,3,False
349,SharpedoMega Sharpedo,Water,560,70,140,70,110,65,105,3,False
374,Crawdaunt,Water,468,63,120,85,90,55,55,3,False
402,Huntail,Water,485,55,104,105,94,75,52,3,False
422,KyogrePrimal Kyogre,Water,770,100,150,90,180,160,90,3,True
466,Floatzel,Water,495,85,105,55,85,50,115,4,False
541,Palkia,Water,680,90,120,100,150,120,100,4,True
626,Carracosta,Water,495,74,108,133,83,65,32,5,False

In [62]:
df[(df['Type 1']=='Flying') | (df['Legendary']==False)]

,Name,Type 1,total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,318,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,405,60,62,63,80,80,60,1,False
2,Venusaur,Grass,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
787,GourgeistSuper Size,Ghost,494,85,100,122,58,75,54,6,False
788,Bergmite,Ice,304,55,69,85,32,35,28,6,False
789,Avalugg,Ice,514,95,117,184,44,46,28,6,False
790,Noibat,Flying,245,40,30,35,45,40,55,6,False
791,Noivern,Flying,535,85,70,80,97,80,123,6,False

In [253]:
df[(df['Type 1']=='Grass') | (df['Legendary']==False)]

,Name,Type 1,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,total
0,Bulbasaur,Grass,45,49,49,65,65,45,1,False,318
1,Ivysaur,Grass,60,62,63,80,80,60,1,False,405
2,Venusaur,Grass,80,82,83,100,100,80,1,False,525
3,VenusaurMega Venusaur,Grass,80,100,123,122,120,80,1,False,625
4,Charmander,Fire,39,52,43,60,50,65,1,False,309
...,...,...,...,...,...,...,...,...,...,...,...
787,GourgeistSuper Size,Ghost,85,100,122,58,75,54,6,False,494
788,Bergmite,Ice,55,69,85,32,35,28,6,False,304
789,Avalugg,Ice,95,117,184,44,46,28,6,False,514
790,Noibat,Flying,40,30,35,45,40,55,6,False,245
791,Noivern,Flying,85,70,80,97,80,123,6,False,535

In [124]:
df[df['Legendary']!=True]

,Name,Type 1,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,318,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,405,60,62,63,80,80,60,1,False
2,Venusaur,Grass,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
787,GourgeistSuper Size,Ghost,494,85,100,122,58,75,54,6,False
788,Bergmite,Ice,304,55,69,85,32,35,28,6,False
789,Avalugg,Ice,514,95,117,184,44,46,28,6,False
790,Noibat,Flying,245,40,30,35,45,40,55,6,False
791,Noivern,Flying,535,85,70,80,97,80,123,6,False

In [66]:
df[~(df['Legendary']==False)]

,Name,Type 1,total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
156,Articuno,Ice,580,90,85,100,95,125,85,1,True
157,Zapdos,Electric,580,90,90,85,125,90,100,1,True
158,Moltres,Fire,580,90,100,90,125,85,90,1,True
162,Mewtwo,Psychic,680,106,110,90,154,90,130,1,True
163,MewtwoMega Mewtwo X,Psychic,780,106,190,100,154,100,130,1,True
...,...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,600,50,100,150,100,150,50,6,True
796,DiancieMega Diancie,Rock,700,50,160,110,160,110,110,6,True
797,HoopaHoopa Confined,Psychic,600,80,110,60,150,130,70,6,True
798,HoopaHoopa Unbound,Psychic,680,80,160,60,170,130,80,6,True
799,Volcanion,Fire,600,80,110,120,130,90,70,6,True

In [69]:
df[(df['Type 1']=='Water') & (df['Attack']>110) &(df['Speed']>90)]

,Name,Type 1,total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
348,Sharpedo,Water,460,70,120,40,95,40,95,3,False
349,SharpedoMega Sharpedo,Water,560,70,140,70,110,65,105,3,False
541,Palkia,Water,680,90,120,100,150,120,100,4,True

In [126]:
df[~(df['Legendary']==True)]

,Name,Type 1,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,318,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,405,60,62,63,80,80,60,1,False
2,Venusaur,Grass,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
787,GourgeistSuper Size,Ghost,494,85,100,122,58,75,54,6,False
788,Bergmite,Ice,304,55,69,85,32,35,28,6,False
789,Avalugg,Ice,514,95,117,184,44,46,28,6,False
790,Noibat,Flying,245,40,30,35,45,40,55,6,False
791,Noivern,Flying,535,85,70,80,97,80,123,6,False

In [20]:
df

,Name,Type 1,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,318,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,405,60,62,63,80,80,60,1,False
2,Venusaur,Grass,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,600,50,100,150,100,150,50,6,True
796,DiancieMega Diancie,Rock,700,50,160,110,160,110,110,6,True
797,HoopaHoopa Confined,Psychic,600,80,110,60,150,130,70,6,True
798,HoopaHoopa Unbound,Psychic,680,80,160,60,170,130,80,6,True
799,Volcanion,Fire,600,80,110,120,130,90,70,6,True

In [21]:
a=np.array([[30,80,45,95,10,22,70]])
p=60

In [22]:
a>p

array([[False,  True, False,  True, False, False,  True]])

In [23]:
a[a>p]

array([80, 95, 70])

In [24]:
df['Type 1']=='Flying'

0      False
1      False
2      False
3      False
4      False
       ...
795    False
796    False
797    False
798    False
799    False
Name: Type 1, Length: 800, dtype: bool

In [25]:
df[df['Type 1']=='Flying']

,Name,Type 1,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
702,TornadusIncarnate Forme,Flying,580,79,115,70,125,80,111,5,True
703,TornadusTherian Forme,Flying,580,79,100,80,110,90,121,5,True
790,Noibat,Flying,245,40,30,35,45,40,55,6,False
791,Noivern,Flying,535,85,70,80,97,80,123,6,False

In [30]:
df[(df['Type 1']=='Fire') & (df['Attack']>100)]

,Name,Type 1,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
7,CharizardMega Charizard X,Fire,634,78,130,111,130,85,100,1,False
8,CharizardMega Charizard Y,Fire,634,78,104,78,159,115,100,1,False
64,Arcanine,Fire,555,90,110,80,100,80,95,1,False
147,Flareon,Fire,525,65,130,60,95,110,65,1,False
263,Entei,Fire,580,115,115,85,90,75,100,2,True
270,Ho-oh,Fire,680,106,130,90,110,154,90,2,True
278,Blaziken,Fire,530,80,120,70,110,70,80,3,False
279,BlazikenMega Blaziken,Fire,630,80,160,80,130,80,100,3,False
354,CameruptMega Camerupt,Fire,560,70,120,100,145,105,20,3,False
437,Infernape,Fire,534,76,104,71,104,71,108,4,False
559,Emboar,Fire,528,110,123,65,100,65,65,5,False
615,DarmanitanStandard Mode,Fire,480,105,140,55,30,55,95,5,False
799,Volcanion,Fire,600,80,110,120,130,90,70,6,True

In [31]:
df[(df['Type 1']=='Flying') | (df['Type 1']=='Fairy')]

,Name,Type 1,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
40,Clefairy,Fairy,323,70,45,48,60,65,35,1,False
41,Clefable,Fairy,483,95,70,73,95,90,60,1,False
187,Cleffa,Fairy,218,50,25,28,45,55,15,2,False
189,Togepi,Fairy,245,35,20,65,40,65,20,2,False
190,Togetic,Fairy,405,55,40,85,80,105,40,2,False
225,Snubbull,Fairy,300,60,80,50,40,40,30,2,False
226,Granbull,Fairy,450,90,120,75,60,60,45,2,False
519,Togekiss,Fairy,545,85,50,95,120,115,80,4,False
702,TornadusIncarnate Forme,Flying,580,79,115,70,125,80,111,5,True
703,TornadusTherian Forme,Flying,580,79,100,80,110,90,121,5,True
737,Flabébé,Fairy,303,44,38,39,61,79,42,6,False
738,Floette,Fairy,371,54,45,47,75,98,52,6,False
739,Florges,Fairy,552,78,65,68,112,154,75,6,False
752,Spritzee,Fairy,341,78,52,60,63,65,23,6,False
753,Aromatisse,Fairy,462,101,72,72,99,89,29,6,False
754,Swirlix,Fairy,341,62,48,66,59,57,49,6,False
755,Slurpuff,Fairy,480,82,80,86,85,75,72,6,False
770,Sylveon,Fairy,525,95,65,65,110,130,60,6,False
790,Noibat,Flying,245,40,30,35,45,40,55,6,False
791,Noivern,Flying,535,85,70,80,97,80,123,6,False
792,Xerneas,Fairy,680,126,131,95,131,98,99,6,True

In [34]:
df[(df['Type 1']=='Water') |(df['Legendary']=='False')]

,Name,Type 1,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
9,Squirtle,Water,314,44,48,65,50,64,43,1,False
10,Wartortle,Water,405,59,63,80,65,80,58,1,False
11,Blastoise,Water,530,79,83,100,85,105,78,1,False
12,BlastoiseMega Blastoise,Water,630,79,103,120,135,115,78,1,False
59,Psyduck,Water,320,50,52,48,65,50,55,1,False
...,...,...,...,...,...,...,...,...,...,...,...
724,Froakie,Water,314,41,56,40,62,44,71,6,False
725,Frogadier,Water,405,54,63,52,83,56,97,6,False
726,Greninja,Water,530,72,95,67,103,71,122,6,False
762,Clauncher,Water,330,50,53,62,58,63,44,6,False
763,Clawitzer,Water,500,71,73,88,120,89,59,6,False

In [85]:
df.groupby(['Type 1'])['Attack'].max().sort_values(ascending=False)

Type 1
Psychic     190
Bug         185
Dragon      180
Ground      180
Ghost       165
Rock        165
Normal      160
Fire        160
Water       155
Dark        150
Steel       150
Fighting    145
Grass       132
Fairy       131
Ice         130
Electric    123
Flying      115
Poison      106
Name: Attack, dtype: int64

In [84]:
df.groupby(['Type 1'])['Attack'].sum().reset_index().sort_values(by='Attack',ascending=False)

      Type 1  Attack
17     Water    8305
12    Normal    7200
9      Grass    5125
0        Bug    4897
6       Fire    4408
15      Rock    4086
14   Psychic    4073
2     Dragon    3588
10    Ground    3064
3   Electric    3040
1       Dark    2740
5   Fighting    2613
16     Steel    2503
8      Ghost    2361
13    Poison    2091
11       Ice    1746
4      Fairy    1046
7     Flying     315

In [87]:
df.groupby(['Type 1'])['Attack'].agg(['sum','min','max','mean','count']).sort_values(by='max',ascending=False)

           sum  min  max        mean  count
Type 1
Psychic   4073   20  190   71.456140     57
Bug       4897   10  185   70.971014     69
Dragon    3588   50  180  112.125000     32
Ground    3064   40  180   95.750000     32
Ghost     2361   30  165   73.781250     32
Rock      4086   40  165   92.863636     44
Normal    7200    5  160   73.469388     98
Fire      4408   30  160   84.769231     52
Water     8305   10  155   74.151786    112
Dark      2740   50  150   88.387097     31
Steel     2503   24  150   92.703704     27
Fighting  2613   35  145   96.777778     27
Grass     5125   27  132   73.214286     70
Fairy     1046   20  131   61.529412     17
Ice       1746   30  130   72.750000     24
Electric  3040   30  123   69.090909     44
Flying     315   30  115   78.750000      4
Poison    2091   43  106   74.678571     28

In [88]:
df

,Name,Type 1,total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,318,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,405,60,62,63,80,80,60,1,False
2,Venusaur,Grass,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,600,50,100,150,100,150,50,6,True
796,DiancieMega Diancie,Rock,700,50,160,110,160,110,110,6,True
797,HoopaHoopa Confined,Psychic,600,80,110,60,150,130,70,6,True
798,HoopaHoopa Unbound,Psychic,680,80,160,60,170,130,80,6,True
799,Volcanion,Fire,600,80,110,120,130,90,70,6,True

In [89]:
df

,Name,Type 1,total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,318,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,405,60,62,63,80,80,60,1,False
2,Venusaur,Grass,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,600,50,100,150,100,150,50,6,True
796,DiancieMega Diancie,Rock,700,50,160,110,160,110,110,6,True
797,HoopaHoopa Confined,Psychic,600,80,110,60,150,130,70,6,True
798,HoopaHoopa Unbound,Psychic,680,80,160,60,170,130,80,6,True
799,Volcanion,Fire,600,80,110,120,130,90,70,6,True

In [92]:
df.drop(columns=['total'],inplace=True)

C:\Users\cipl\AppData\Local\Temp\ipykernel_2792\1757500260.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=['total'],inplace=True)

In [94]:
df.to_excel('abcd.xlsx')

PermissionError: [Errno 13] Permission denied: 'abcd.xlsx'

In [93]:
df

,Name,Type 1,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,60,62,63,80,80,60,1,False
2,Venusaur,Grass,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,80,100,123,122,120,80,1,False
4,Charmander,Fire,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,50,100,150,100,150,50,6,True
796,DiancieMega Diancie,Rock,50,160,110,160,110,110,6,True
797,HoopaHoopa Confined,Psychic,80,110,60,150,130,70,6,True
798,HoopaHoopa Unbound,Psychic,80,160,60,170,130,80,6,True
799,Volcanion,Fire,80,110,120,130,90,70,6,True

In [90]:
df.to_csv('weekday4.csv',index=False)

## Saving our Data (Exporting into desired format)

## To save the dataset

In [43]:
pokemon.to_csv('updated_pokemon.csv',index=False) #here index=False to delete the extra indexes of csv format

In [44]:
# pokemon

In [58]:
df

,Name,Type 1,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,318,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,405,60,62,63,80,80,60,1,False
2,Venusaur,Grass,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,600,50,100,150,100,150,50,6,True
796,DiancieMega Diancie,Rock,700,50,160,110,160,110,110,6,True
797,HoopaHoopa Confined,Psychic,600,80,110,60,150,130,70,6,True
798,HoopaHoopa Unbound,Psychic,680,80,160,60,170,130,80,6,True
799,Volcanion,Fire,600,80,110,120,130,90,70,6,True

In [26]:
df[df['Attack']>160]

,Name,Type 1,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
163,MewtwoMega Mewtwo X,Psychic,780,106,190,100,154,100,130,1,True
232,HeracrossMega Heracross,Bug,600,80,185,115,40,105,75,2,False
268,TyranitarMega Tyranitar,Rock,700,100,164,150,95,120,71,2,False
387,BanetteMega Banette,Ghost,555,64,165,75,93,83,75,3,False
424,GroudonPrimal Groudon,Ground,770,100,180,160,150,90,90,3,True
426,RayquazaMega Rayquaza,Dragon,780,105,180,100,180,100,115,3,True
429,DeoxysAttack Forme,Psychic,600,50,180,20,180,20,150,3,True
454,Rampardos,Rock,495,97,165,60,65,50,58,4,False
494,GarchompMega Garchomp,Dragon,700,108,170,115,120,95,92,4,False
527,GalladeMega Gallade,Psychic,618,68,165,95,65,115,110,4,False
711,KyuremBlack Kyurem,Dragon,700,125,170,100,120,90,95,5,True

In [29]:
df[(df['Type 1']=='Rock') | (df['Attack']>160)]

,Name,Type 1,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
80,Geodude,Rock,300,40,80,100,30,30,20,1,False
81,Graveler,Rock,390,55,95,115,45,45,35,1,False
82,Golem,Rock,495,80,120,130,55,65,45,1,False
103,Onix,Rock,385,35,45,160,30,45,70,1,False
149,Omanyte,Rock,355,35,40,100,90,55,35,1,False
150,Omastar,Rock,495,70,60,125,115,70,55,1,False
151,Kabuto,Rock,355,30,80,90,55,45,55,1,False
152,Kabutops,Rock,495,60,115,105,65,70,80,1,False
153,Aerodactyl,Rock,515,80,105,65,60,75,130,1,False
154,AerodactylMega Aerodactyl,Rock,615,80,135,85,70,95,150,1,False
163,MewtwoMega Mewtwo X,Psychic,780,106,190,100,154,100,130,1,True
200,Sudowoodo,Rock,410,70,100,115,30,65,30,2,False
232,HeracrossMega Heracross,Bug,600,80,185,115,40,105,75,2,False
265,Larvitar,Rock,300,50,64,50,45,50,41,2,False
266,Pupitar,Rock,410,70,84,70,65,70,51,2,False
267,Tyranitar,Rock,600,100,134,110,95,100,61,2,False
268,TyranitarMega Tyranitar,Rock,700,100,164,150,95,120,71,2,False
323,Nosepass,Rock,375,30,45,135,45,90,30,3,False
369,Lunatone,Rock,440,70,55,65,95,85,70,3,False
370,Solrock,Rock,440,70,95,85,55,65,70,3,False
377,Lileep,Rock,355,66,41,77,61,87,23,3,False
378,Cradily,Rock,495,86,81,97,81,107,43,3,False
379,Anorith,Rock,355,45,95,50,40,50,75,3,False
380,Armaldo,Rock,495,75,125,100,70,80,45,3,False
387,BanetteMega Banette,Ghost,555,64,165,75,93,83,75,3,False
414,Regirock,Rock,580,80,100,200,50,100,50,3,True
424,GroudonPrimal Groudon,Ground,770,100,180,160,150,90,90,3,True
426,RayquazaMega Rayquaza,Dragon,780,105,180,100,180,100,115,3,True
429,DeoxysAttack Forme,Psychic,600,50,180,20,180,20,150,3,True
453,Cranidos,Rock,350,67,125,40,30,30,58,4,False
454,Rampardos,Rock,495,97,165,60,65,50,58,4,False
455,Shieldon,Rock,350,30,42,118,42,88,30,4,False
456,Bastiodon,Rock,495,60,52,168,47,138,30,4,False
486,Bonsly,Rock,290,50,80,95,10,45,10,4,False
494,GarchompMega Garchomp,Dragon,700,108,170,115,120,95,92,4,False
527,GalladeMega Gallade,Psychic,618,68,165,95,65,115,110,4,False
528,Probopass,Rock,525,60,55,145,75,150,40,4,False
583,Roggenrola,Rock,280,55,75,85,25,25,15,5,False
584,Boldore,Rock,390,70,105,105,50,40,20,5,False
585,Gigalith,Rock,515,85,135,130,60,80,25,5,False
627,Archen,Rock,401,55,112,45,74,45,70,5,False
628,Archeops,Rock,567,75,140,65,112,65,110,5,False
700,Terrakion,Rock,580,91,129,90,72,90,108,5,True
711,KyuremBlack Kyurem,Dragon,700,125,170,100,120,90,95,5,True
758,Binacle,Rock,306,42,52,67,39,56,50,6,False
759,Barbaracle,Rock,500,72,105,115,54,86,68,6,False
766,Tyrunt,Rock,362,58,89,77,45,45,48,6,False
767,Tyrantrum,Rock,521,82,121,119,69,59,71,6,False
768,Amaura,Rock,362,77,59,50,67,63,46,6,False
769,Aurorus,Rock,521,123,77,72,99,92,58,6,False
773,Carbink,Rock,500,50,50,150,50,150,50,6,False
795,Diancie,Rock,600,50,100,150,100,150,50,6,True
796,DiancieMega Diancie,Rock,700,50,160,110,160,110,110,6,True

## Filtering of data Or Condition in data

In [37]:
pd.set_option('display.max_rows',None)

In [38]:
df[(df['Type 1']=="Grass") | (df['Legendary']==True)]

,Name,Type 1,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,318,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,405,60,62,63,80,80,60,1,False
2,Venusaur,Grass,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,625,80,100,123,122,120,80,1,False
48,Oddish,Grass,320,45,50,55,75,65,30,1,False
49,Gloom,Grass,395,60,65,70,85,75,40,1,False
50,Vileplume,Grass,490,75,80,85,110,90,50,1,False
75,Bellsprout,Grass,300,50,75,35,70,30,40,1,False
76,Weepinbell,Grass,390,65,90,50,85,45,55,1,False
77,Victreebel,Grass,490,80,105,65,100,70,70,1,False
110,Exeggcute,Grass,325,60,40,80,60,45,40,1,False
111,Exeggutor,Grass,520,95,95,85,125,65,55,1,False
122,Tangela,Grass,435,65,55,115,100,40,60,1,False
156,Articuno,Ice,580,90,85,100,95,125,85,1,True
157,Zapdos,Electric,580,90,90,85,125,90,100,1,True
158,Moltres,Fire,580,90,100,90,125,85,90,1,True
162,Mewtwo,Psychic,680,106,110,90,154,90,130,1,True
163,MewtwoMega Mewtwo X,Psychic,780,106,190,100,154,100,130,1,True
164,MewtwoMega Mewtwo Y,Psychic,780,106,150,70,194,120,140,1,True
166,Chikorita,Grass,318,45,49,65,49,65,45,2,False
167,Bayleef,Grass,405,60,62,80,63,80,60,2,False
168,Meganium,Grass,525,80,82,100,83,100,80,2,False
197,Bellossom,Grass,490,75,80,95,90,100,50,2,False
202,Hoppip,Grass,250,35,35,40,35,55,50,2,False
203,Skiploom,Grass,340,55,45,50,45,65,80,2,False
204,Jumpluff,Grass,460,75,55,70,55,95,110,2,False
206,Sunkern,Grass,180,30,30,30,30,30,30,2,False
207,Sunflora,Grass,425,75,75,55,105,85,30,2,False
262,Raikou,Electric,580,90,85,75,115,100,115,2,True
263,Entei,Fire,580,115,115,85,90,75,100,2,True
264,Suicune,Water,580,100,75,115,90,115,85,2,True
269,Lugia,Psychic,680,106,90,130,90,154,110,2,True
270,Ho-oh,Fire,680,106,130,90,110,154,90,2,True
272,Treecko,Grass,310,40,45,35,65,55,70,3,False
273,Grovyle,Grass,405,50,65,45,85,65,95,3,False
274,Sceptile,Grass,530,70,85,65,105,85,120,3,False
275,SceptileMega Sceptile,Grass,630,70,110,75,145,85,145,3,False
296,Seedot,Grass,220,40,40,50,30,30,30,3,False
297,Nuzleaf,Grass,340,70,70,40,60,40,60,3,False
298,Shiftry,Grass,480,90,100,60,90,60,80,3,False
309,Shroomish,Grass,295,60,40,60,40,60,35,3,False
310,Breloom,Grass,460,60,130,80,60,60,70,3,False
344,Roselia,Grass,400,50,60,45,100,80,65,3,False
362,Cacnea,Grass,335,50,85,40,85,40,35,3,False
363,Cacturne,Grass,475,70,115,60,115,60,55,3,False
390,Tropius,Grass,460,99,68,83,72,87,51,3,False
414,Regirock,Rock,580,80,100,200,50,100,50,3,True
415,Regice,Ice,580,80,50,100,100,200,50,3,True
416,Registeel,Steel,580,80,75,150,75,150,50,3,True
417,Latias,Dragon,600,80,80,90,110,130,110,3,True
418,LatiasMega Latias,Dragon,700,80,100,120,140,150,110,3,True
419,Latios,Dragon,600,80,90,80,130,110,110,3,True
420,LatiosMega Latios,Dragon,700,80,130,100,160,120,110,3,True
421,Kyogre,Water,670,100,100,90,150,140,90,3,True
422,KyogrePrimal Kyogre,Water,770,100,150,90,180,160,90,3,True
423,Groudon,Ground,670,100,150,140,100,90,90,3,True
424,GroudonPrimal Groudon,Ground,770,100,180,160,150,90,90,3,True
425,Rayquaza,Dragon,680,105,150,90,150,90,95,3,True
426,RayquazaMega Rayquaza,Dragon,780,105,180,100,180,100,115,3,True
427,Jirachi,Steel,600,100,100,100,100,100,100,3,True
428,DeoxysNormal Forme,Psychic,600,50,150,50,150,50,150,3,True
429,DeoxysAttack Forme,Psychic,600,50,180,20,180,20,150,3,True
430,DeoxysDefense Forme,Psychic,600,50,70,160,70,160,90,3,True
431,DeoxysSpeed Forme,Psychic,600,50,95,90,95,90,180,3,True
432,Turtwig,Grass,318,55,68,64,45,55,31,4,False
433,Grotle,Grass,405,75,89,85,55,65,36,4,False
434,Torterra,Grass,525,95,109,105,75,85,56,4,False
451,Budew,Grass,280,40,30,35,50,70,55,4,False
452,Roserade,Grass,515,60,70,65,125,105,90,4,False
467,Cherubi,Grass,275,45,35,45,62,53,35,4,False
468,Cherrim,Grass,450,70,60,70,87,78,85,4,False
505,Carnivine,Grass,454,74,100,72,90,72,46,4,False
509,Snover,Grass,334,60,62,50,62,60,40,4,False
510,Abomasnow,Grass,494,90,92,75,92,85,60,4,False
511,AbomasnowMega Abomasnow,Grass,594,90,132,105,132,105,30,4,False
516,Tangrowth,Grass,535,100,100,125,110,50,50,4,False
521,Leafeon,Grass,525,65,110,130,60,65,95,4,False
537,Uxie,Psychic,580,75,75,130,75,130,95,4,True
538,Mesprit,Psychic,580,80,105,105,105,105,80,4,True
539,Azelf,Psychic,580,75,125,70,125,70,115,4,True
540,Dialga,Steel,680,100,120,120,150,100,90,4,True
541,Palkia,Water,680,90,120,100,150,120,100,4,True
542,Heatran,Fire,600,91,90,106,130,106,77,4,True
543,Regigigas,Normal,670,110,160,110,80,110,100,4,True
544,GiratinaAltered Forme,Ghost,680,150,100,120,100,120,90,4,True
545,GiratinaOrigin Forme,Ghost,680,150,120,100,120,100,90,4,True
549,Darkrai,Dark,600,70,90,90,135,90,125,4,True
550,ShayminLand Forme,Grass,600,100,100,100,100,100,100,4,True
551,ShayminSky Forme,Grass,600,100,103,75,120,75,127,4,True
552,Arceus,Normal,720,120,120,120,120,120,120,4,True
553,Victini,Psychic,600,100,100,100,100,100,100,5,True
554,Snivy,Grass,308,45,45,55,45,55,63,5,False
555,Servine,Grass,413,60,60,75,60,75,83,5,False
556,Serperior,Grass,528,75,75,95,75,95,113,5,False
570,Pansage,Grass,316,50,53,48,53,48,64,5,False
571,Simisage,Grass,498,75,98,63,98,63,101,5,False
606,Cottonee,Grass,280,40,27,60,37,50,66,5,False
607,Whimsicott,Grass,480,60,67,85,77,75,116,5,False
608,Petilil,Grass,280,45,35,50,70,50,30,5,False
609,Lilligant,Grass,480,70,60,75,110,75,90,5,False
617,Maractus,Grass,461,75,86,67,106,67,60,5,False
651,Foongus,Grass,294,69,55,45,55,55,15,5,False
652,Amoonguss,Grass,464,114,85,70,85,80,30,5,False
658,Ferroseed,Grass,305,44,50,91,24,86,10,5,False
659,Ferrothorn,Grass,489,74,94,131,54,116,20,5,False
699,Cobalion,Steel,580,91,90,129,90,72,108,5,True
700,Terrakion,Rock,580,91,129,90,72,90,108,5,True
701,Virizion,Grass,580,91,90,72,90,129,108,5,True
702,TornadusIncarnate Forme,Flying,580,79,115,70,125,80,111,5,True
703,TornadusTherian Forme,Flying,580,79,100,80,110,90,121,5,True
704,ThundurusIncarnate Forme,Electric,580,79,115,70,125,80,111,5,True
705,ThundurusTherian Forme,Electric,580,79,105,70,145,80,101,5,True
706,Reshiram,Dragon,680,100,120,100,150,120,90,5,True
707,Zekrom,Dragon,680,100,150,120,120,100,90,5,True
708,LandorusIncarnate Forme,Ground,600,89,125,90,115,80,101,5,True
709,LandorusTherian Forme,Ground,600,89,145,90,105,80,91,5,True
710,Kyurem,Dragon,660,125,130,90,130,90,95,5,True
711,KyuremBlack Kyurem,Dragon,700,125,170,100,120,90,95,5,True
712,KyuremWhite Kyurem,Dragon,700,125,120,90,170,100,95,5,True
718,Chespin,Grass,313,56,61,65,48,45,38,6,False
719,Quilladin,Grass,405,61,78,95,56,58,57,6,False
720,Chesnaught,Grass,530,88,107,122,74,75,64,6,False
740,Skiddo,Grass,350,66,65,48,62,57,52,6,False
741,Gogoat,Grass,531,123,100,62,97,81,68,6,False
792,Xerneas,Fairy,680,126,131,95,131,98,99,6,True
793,Yveltal,Dark,680,126,131,95,131,98,99,6,True
794,Zygarde50% Forme,Dragon,600,108,100,121,81,95,95,6,True
795,Diancie,Rock,600,50,100,150,100,150,50,6,True
796,DiancieMega Diancie,Rock,700,50,160,110,160,110,110,6,True
797,HoopaHoopa Confined,Psychic,600,80,110,60,150,130,70,6,True
798,HoopaHoopa Unbound,Psychic,680,80,160,60,170,130,80,6,True
799,Volcanion,Fire,600,80,110,120,130,90,70,6,True

In [31]:
# df[(df['Type 1']=="Dragon") & (df['Type 2']=='Fire')]

In [47]:
df[(df['Type 1']=="Grass") | (df['Legendary']==True)]

,Name,Type 1,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,318,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,405,60,62,63,80,80,60,1,False
2,Venusaur,Grass,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,625,80,100,123,122,120,80,1,False
48,Oddish,Grass,320,45,50,55,75,65,30,1,False
...,...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,600,50,100,150,100,150,50,6,True
796,DiancieMega Diancie,Rock,700,50,160,110,160,110,110,6,True
797,HoopaHoopa Confined,Psychic,600,80,110,60,150,130,70,6,True
798,HoopaHoopa Unbound,Psychic,680,80,160,60,170,130,80,6,True
799,Volcanion,Fire,600,80,110,120,130,90,70,6,True

In [45]:
df[df['Type 1']!='Water']

,Name,Type 1,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,318,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,405,60,62,63,80,80,60,1,False
2,Venusaur,Grass,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,309,39,52,43,60,50,65,1,False
5,Charmeleon,Fire,405,58,64,58,80,65,80,1,False
6,Charizard,Fire,534,78,84,78,109,85,100,1,False
7,CharizardMega Charizard X,Fire,634,78,130,111,130,85,100,1,False
8,CharizardMega Charizard Y,Fire,634,78,104,78,159,115,100,1,False
13,Caterpie,Bug,195,45,30,35,20,20,45,1,False
14,Metapod,Bug,205,50,20,55,25,25,30,1,False
15,Butterfree,Bug,395,60,45,50,90,80,70,1,False
16,Weedle,Bug,195,40,35,30,20,20,50,1,False
17,Kakuna,Bug,205,45,25,50,25,25,35,1,False
18,Beedrill,Bug,395,65,90,40,45,80,75,1,False
19,BeedrillMega Beedrill,Bug,495,65,150,40,15,80,145,1,False
20,Pidgey,Normal,251,40,45,40,35,35,56,1,False
21,Pidgeotto,Normal,349,63,60,55,50,50,71,1,False
22,Pidgeot,Normal,479,83,80,75,70,70,101,1,False
23,PidgeotMega Pidgeot,Normal,579,83,80,80,135,80,121,1,False
24,Rattata,Normal,253,30,56,35,25,35,72,1,False
25,Raticate,Normal,413,55,81,60,50,70,97,1,False
26,Spearow,Normal,262,40,60,30,31,31,70,1,False
27,Fearow,Normal,442,65,90,65,61,61,100,1,False
28,Ekans,Poison,288,35,60,44,40,54,55,1,False
29,Arbok,Poison,438,60,85,69,65,79,80,1,False
30,Pikachu,Electric,320,35,55,40,50,50,90,1,False
31,Raichu,Electric,485,60,90,55,90,80,110,1,False
32,Sandshrew,Ground,300,50,75,85,20,30,40,1,False
33,Sandslash,Ground,450,75,100,110,45,55,65,1,False
34,Nidoran (Female),Poison,275,55,47,52,40,40,41,1,False
35,Nidorina,Poison,365,70,62,67,55,55,56,1,False
36,Nidoqueen,Poison,505,90,92,87,75,85,76,1,False
37,Nidoran (Male),Poison,273,46,57,40,40,40,50,1,False
38,Nidorino,Poison,365,61,72,57,55,55,65,1,False
39,Nidoking,Poison,505,81,102,77,85,75,85,1,False
40,Clefairy,Fairy,323,70,45,48,60,65,35,1,False
41,Clefable,Fairy,483,95,70,73,95,90,60,1,False
42,Vulpix,Fire,299,38,41,40,50,65,65,1,False
43,Ninetales,Fire,505,73,76,75,81,100,100,1,False
44,Jigglypuff,Normal,270,115,45,20,45,25,20,1,False
45,Wigglytuff,Normal,435,140,70,45,85,50,45,1,False
46,Zubat,Poison,245,40,45,35,30,40,55,1,False
47,Golbat,Poison,455,75,80,70,65,75,90,1,False
48,Oddish,Grass,320,45,50,55,75,65,30,1,False
49,Gloom,Grass,395,60,65,70,85,75,40,1,False
50,Vileplume,Grass,490,75,80,85,110,90,50,1,False
51,Paras,Bug,285,35,70,55,45,55,25,1,False
52,Parasect,Bug,405,60,95,80,60,80,30,1,False
53,Venonat,Bug,305,60,55,50,40,55,45,1,False
54,Venomoth,Bug,450,70,65,60,90,75,90,1,False
55,Diglett,Ground,265,10,55,25,35,45,95,1,False
56,Dugtrio,Ground,405,35,80,50,50,70,120,1,False
57,Meowth,Normal,290,40,45,35,40,40,90,1,False
58,Persian,Normal,440,65,70,60,65,65,115,1,False
61,Mankey,Fighting,305,40,80,35,35,45,70,1,False
62,Primeape,Fighting,455,65,105,60,60,70,95,1,False
63,Growlithe,Fire,350,55,70,45,70,50,60,1,False
64,Arcanine,Fire,555,90,110,80,100,80,95,1,False
68,Abra,Psychic,310,25,20,15,105,55,90,1,False
69,Kadabra,Psychic,400,40,35,30,120,70,105,1,False
70,Alakazam,Psychic,500,55,50,45,135,95,120,1,False
71,AlakazamMega Alakazam,Psychic,590,55,50,65,175,95,150,1,False
72,Machop,Fighting,305,70,80,50,35,35,35,1,False
73,Machoke,Fighting,405,80,100,70,50,60,45,1,False
74,Machamp,Fighting,505,90,130,80,65,85,55,1,False
75,Bellsprout,Grass,300,50,75,35,70,30,40,1,False
76,Weepinbell,Grass,390,65,90,50,85,45,55,1,False
77,Victreebel,Grass,490,80,105,65,100,70,70,1,False
80,Geodude,Rock,300,40,80,100,30,30,20,1,False
81,Graveler,Rock,390,55,95,115,45,45,35,1,False
82,Golem,Rock,495,80,120,130,55,65,45,1,False
83,Ponyta,Fire,410,50,85,55,65,65,90,1,False
84,Rapidash,Fire,500,65,100,70,80,80,105,1,False
88,Magnemite,Electric,325,25,35,70,95,55,45,1,False
89,Magneton,Electric,465,50,60,95,120,70,70,1,False
90,Farfetch'd,Normal,352,52,65,55,58,62,60,1,False
91,Doduo,Normal,310,35,85,45,35,35,75,1,False
92,Dodrio,Normal,460,60,110,70,60,60,100,1,False
95,Grimer,Poison,325,80,80,50,40,50,25,1,False
96,Muk,Poison,500,105,105,75,65,100,50,1,False
99,Gastly,Ghost,310,30,35,30,100,35,80,1,False
100,Haunter,Ghost,405,45,50,45,115,55,95,1,False
101,Gengar,Ghost,500,60,65,60,130,75,110,1,False
102,GengarMega Gengar,Ghost,600,60,65,80,170,95,130,1,False
103,Onix,Rock,385,35,45,160,30,45,70,1,False
104,Drowzee,Psychic,328,60,48,45,43,90,42,1,False
105,Hypno,Psychic,483,85,73,70,73,115,67,1,False
108,Voltorb,Electric,330,40,30,50,55,55,100,1,False
109,Electrode,Electric,480,60,50,70,80,80,140,1,False
110,Exeggcute,Grass,325,60,40,80,60,45,40,1,False
111,Exeggutor,Grass,520,95,95,85,125,65,55,1,False
112,Cubone,Ground,320,50,50,95,40,50,35,1,False
113,Marowak,Ground,425,60,80,110,50,80,45,1,False
114,Hitmonlee,Fighting,455,50,120,53,35,110,87,1,False
115,Hitmonchan,Fighting,455,50,105,79,35,110,76,1,False
116,Lickitung,Normal,385,90,55,75,60,75,30,1,False
117,Koffing,Poison,340,40,65,95,60,45,35,1,False
118,Weezing,Poison,490,65,90,120,85,70,60,1,False
119,Rhyhorn,Ground,345,80,85,95,30,30,25,1,False
120,Rhydon,Ground,485,105,130,120,45,45,40,1,False
121,Chansey,Normal,450,250,5,5,35,105,50,1,False
122,Tangela,Grass,435,65,55,115,100,40,60,1,False
123,Kangaskhan,Normal,490,105,95,80,40,80,90,1,False
124,KangaskhanMega Kangaskhan,Normal,590,105,125,100,60,100,100,1,False
131,Mr. Mime,Psychic,460,40,45,65,100,120,90,1,False
132,Scyther,Bug,500,70,110,80,55,80,105,1,False
133,Jynx,Ice,455,65,50,35,115,95,95,1,False
134,Electabuzz,Electric,490,65,83,57,95,85,105,1,False
135,Magmar,Fire,495,65,95,57,100,85,93,1,False
136,Pinsir,Bug,500,65,125,100,55,70,85,1,False
137,PinsirMega Pinsir,Bug,600,65,155,120,65,90,105,1,False
138,Tauros,Normal,490,75,100,95,40,70,110,1,False
143,Ditto,Normal,288,48,48,48,48,48,48,1,False
144,Eevee,Normal,325,55,55,50,45,65,55,1,False
146,Jolteon,Electric,525,65,65,60,110,95,130,1,False
147,Flareon,Fire,525,65,130,60,95,110,65,1,False
148,Porygon,Normal,395,65,60,70,85,75,40,1,False
149,Omanyte,Rock,355,35,40,100,90,55,35,1,False
150,Omastar,Rock,495,70,60,125,115,70,55,1,False
151,Kabuto,Rock,355,30,80,90,55,45,55,1,False
152,Kabutops,Rock,495,60,115,105,65,70,80,1,False
153,Aerodactyl,Rock,515,80,105,65,60,75,130,1,False
154,AerodactylMega Aerodactyl,Rock,615,80,135,85,70,95,150,1,False
155,Snorlax,Normal,540,160,110,65,65,110,30,1,False
156,Articuno,Ice,580,90,85,100,95,125,85,1,True
157,Zapdos,Electric,580,90,90,85,125,90,100,1,True
158,Moltres,Fire,580,90,100,90,125,85,90,1,True
159,Dratini,Dragon,300,41,64,45,50,50,50,1,False
160,Dragonair,Dragon,420,61,84,65,70,70,70,1,False
161,Dragonite,Dragon,600,91,134,95,100,100,80,1,False
162,Mewtwo,Psychic,680,106,110,90,154,90,130,1,True
163,MewtwoMega Mewtwo X,Psychic,780,106,190,100,154,100,130,1,True
164,MewtwoMega Mewtwo Y,Psychic,780,106,150,70,194,120,140,1,True
165,Mew,Psychic,600,100,100,100,100,100,100,1,False
166,Chikorita,Grass,318,45,49,65,49,65,45,2,False
167,Bayleef,Grass,405,60,62,80,63,80,60,2,False
168,Meganium,Grass,525,80,82,100,83,100,80,2,False
169,Cyndaquil,Fire,309,39,52,43,60,50,65,2,False
170,Quilava,Fire,405,58,64,58,80,65,80,2,False
171,Typhlosion,Fire,534,78,84,78,109,85,100,2,False
175,Sentret,Normal,215,35,46,34,35,45,20,2,False
176,Furret,Normal,415,85,76,64,45,55,90,2,False
177,Hoothoot,Normal,262,60,30,30,36,56,50,2,False
178,Noctowl,Normal,442,100,50,50,76,96,70,2,False
179,Ledyba,Bug,265,40,20,30,40,80,55,2,False
180,Ledian,Bug,390,55,35,50,55,110,85,2,False
181,Spinarak,Bug,250,40,60,40,40,40,30,2,False
182,Ariados,Bug,390,70,90,70,60,60,40,2,False
183,Crobat,Poison,535,85,90,80,70,80,130,2,False
186,Pichu,Electric,205,20,40,15,35,35,60,2,False
187,Cleffa,Fairy,218,50,25,28,45,55,15,2,False
188,Igglybuff,Normal,210,90,30,15,40,20,15,2,False
189,Togepi,Fairy,245,35,20,65,40,65,20,2,False
190,Togetic,Fairy,405,55,40,85,80,105,40,2,False
191,Natu,Psychic,320,40,50,45,70,45,70,2,False
192,Xatu,Psychic,470,65,75,70,95,70,95,2,False
193,Mareep,Electric,280,55,40,40,65,45,35,2,False
194,Flaaffy,Electric,365,70,55,55,80,60,45,2,False
195,Ampharos,Electric,510,90,75,85,115,90,55,2,False
196,AmpharosMega Ampharos,Electric,610,90,95,105,165,110,45,2,False
197,Bellossom,Grass,490,75,80,95,90,100,50,2,False
200,Sudowoodo,Rock,410,70,100,115,30,65,30,2,False
202,Hoppip,Grass,250,35,35,40,35,55,50,2,False
203,Skiploom,Grass,340,55,45,50,45,65,80,2,False
204,Jumpluff,Grass,460,75,55,70,55,95,110,2,False
205,Aipom,Normal,360,55,70,55,40,55,85,2,False
206,Sunkern,Grass,180,30,30,30,30,30,30,2,False
207,Sunflora,Grass,425,75,75,55,105,85,30,2,False
208,Yanma,Bug,390,65,65,45,75,45,95,2,False
211,Espeon,Psychic,525,65,65,60,130,95,110,2,False
212,Umbreon,Dark,525,95,65,110,60,130,65,2,False
213,Murkrow,Dark,405,60,85,42,85,42,91,2,False
215,Misdreavus,Ghost,435,60,60,60,85,85,85,2,False
216,Unown,Psychic,336,48,72,48,72,48,48,2,False
217,Wobbuffet,Psychic,405,190,33,58,33,58,33,2,False
218,Girafarig,Normal,455,70,80,65,90,65,85,2,False
219,Pineco,Bug,290,50,65,90,35,35,15,2,False
220,Forretress,Bug,465,75,90,140,60,60,40,2,False
221,Dunsparce,Normal,415,100,70,70,65,65,45,2,False
222,Gligar,Ground,430,65,75,105,35,65,85,2,False
223,Steelix,Steel,510,75,85,200,55,65,30,2,False
224,SteelixMega Steelix,Steel,610,75,125,230,55,95,30,2,False
225,Snubbull,Fairy,300,60,80,50,40,40,30,2,False
226,Granbull,Fairy,450,90,120,75,60,60,45,2,False
228,Scizor,Bug,500,70,130,100,55,80,65,2,False
229,ScizorMega Scizor,Bug,600,70,150,140,65,100,75,2,False
230,Shuckle,Bug,505,20,10,230,10,230,5,2,False
231,Heracross,Bug,500,80,125,75,40,95,85,2,False
232,HeracrossMega Heracross,Bug,600,80,185,115,40,105,75,2,False
233,Sneasel,Dark,430,55,95,55,35,75,115,2,False
234,Teddiursa,Normal,330,60,80,50,50,50,40,2,False
235,Ursaring,Normal,500,90,130,75,75,75,55,2,False
236,Slugma,Fire,250,40,40,40,70,40,20,2,False
237,Magcargo,Fire,410,50,50,120,80,80,30,2,False
238,Swinub,Ice,250,50,50,40,30,30,50,2,False
239,Piloswine,Ice,450,100,100,80,60,60,50,2,False
243,Delibird,Ice,330,45,55,45,65,45,75,2,False
245,Skarmory,Steel,465,65,80,140,40,70,70,2,False
246,Houndour,Dark,330,45,60,30,80,50,65,2,False
247,Houndoom,Dark,500,75,90,50,110,80,95,2,False
248,HoundoomMega Houndoom,Dark,600,75,90,90,140,90,115,2,False
250,Phanpy,Ground,330,90,60,60,40,40,40,2,False
251,Donphan,Ground,500,90,120,120,60,60,50,2,False
252,Porygon2,Normal,515,85,80,90,105,95,60,2,False
253,Stantler,Normal,465,73,95,62,85,65,85,2,False
254,Smeargle,Normal,250,55,20,35,20,45,75,2,False
255,Tyrogue,Fighting,210,35,35,35,35,35,35,2,False
256,Hitmontop,Fighting,455,50,95,95,35,110,70,2,False
257,Smoochum,Ice,305,45,30,15,85,65,65,2,False
258,Elekid,Electric,360,45,63,37,65,55,95,2,False
259,Magby,Fire,365,45,75,37,70,55,83,2,False
260,Miltank,Normal,490,95,80,105,40,70,100,2,False
261,Blissey,Normal,540,255,10,10,75,135,55,2,False
262,Raikou,Electric,580,90,85,75,115,100,115,2,True
263,Entei,Fire,580,115,115,85,90,75,100,2,True
265,Larvitar,Rock,300,50,64,50,45,50,41,2,False
266,Pupitar,Rock,410,70,84,70,65,70,51,2,False
267,Tyranitar,Rock,600,100,134,110,95,100,61,2,False
268,TyranitarMega Tyranitar,Rock,700,100,164,150,95,120,71,2,False
269,Lugia,Psychic,680,106,90,130,90,154,110,2,True
270,Ho-oh,Fire,680,106,130,90,110,154,90,2,True
271,Celebi,Psychic,600,100,100,100,100,100,100,2,False
272,Treecko,Grass,310,40,45,35,65,55,70,3,False
273,Grovyle,Grass,405,50,65,45,85,65,95,3,False
274,Sceptile,Grass,530,70,85,65,105,85,120,3,False
275,SceptileMega Sceptile,Grass,630,70,110,75,145,85,145,3,False
276,Torchic,Fire,310,45,60,40,70,50,45,3,False
277,Combusken,Fire,405,60,85,60,85,60,55,3,False
278,Blaziken,Fire,530,80,120,70,110,70,80,3,False
279,BlazikenMega Blaziken,Fire,630,80,160,80,130,80,100,3,False
284,Poochyena,Dark,220,35,55,35,30,30,35,3,False
285,Mightyena,Dark,420,70,90,70,60,60,70,3,False
286,Zigzagoon,Normal,240,38,30,41,30,41,60,3,False
287,Linoone,Normal,420,78,70,61,50,61,100,3,False
288,Wurmple,Bug,195,45,45,35,20,30,20,3,False
289,Silcoon,Bug,205,50,35,55,25,25,15,3,False
290,Beautifly,Bug,395,60,70,50,100,50,65,3,False
291,Cascoon,Bug,205,50,35,55,25,25,15,3,False
292,Dustox,Bug,385,60,50,70,50,90,65,3,False
296,Seedot,Grass,220,40,40,50,30,30,30,3,False
297,Nuzleaf,Grass,340,70,70,40,60,40,60,3,False
298,Shiftry,Grass,480,90,100,60,90,60,80,3,False
299,Taillow,Normal,270,40,55,30,30,30,85,3,False
300,Swellow,Normal,430,60,85,60,50,50,125,3,False
303,Ralts,Psychic,198,28,25,25,45,35,40,3,False
304,Kirlia,Psychic,278,38,35,35,65,55,50,3,False
305,Gardevoir,Psychic,518,68,65,65,125,115,80,3,False
306,GardevoirMega Gardevoir,Psychic,618,68,85,65,165,135,100,3,False
307,Surskit,Bug,269,40,30,32,50,52,65,3,False
308,Masquerain,Bug,414,70,60,62,80,82,60,3,False
309,Shroomish,Grass,295,60,40,60,40,60,35,3,False
310,Breloom,Grass,460,60,130,80,60,60,70,3,False
311,Slakoth,Normal,280,60,60,60,35,35,30,3,False
312,Vigoroth,Normal,440,80,80,80,55,55,90,3,False
313,Slaking,Normal,670,150,160,100,95,65,100,3,False
314,Nincada,Bug,266,31,45,90,30,30,40,3,False
315,Ninjask,Bug,456,61,90,45,50,50,160,3,False
316,Shedinja,Bug,236,1,90,45,30,30,40,3,False
317,Whismur,Normal,240,64,51,23,51,23,28,3,False
318,Loudred,Normal,360,84,71,43,71,43,48,3,False
319,Exploud,Normal,490,104,91,63,91,73,68,3,False
320,Makuhita,Fighting,237,72,60,30,20,30,25,3,False
321,Hariyama,Fighting,474,144,120,60,40,60,50,3,False
322,Azurill,Normal,190,50,20,40,20,40,20,3,False
323,Nosepass,Rock,375,30,45,135,45,90,30,3,False
324,Skitty,Normal,260,50,45,45,35,35,50,3,False
325,Delcatty,Normal,380,70,65,65,55,55,70,3,False
326,Sableye,Dark,380,50,75,75,65,65,50,3,False
327,SableyeMega Sableye,Dark,480,50,85,125,85,115,20,3,False
328,Mawile,Steel,380,50,85,85,55,55,50,3,False
329,MawileMega Mawile,Steel,480,50,105,125,55,95,50,3,False
330,Aron,Steel,330,50,70,100,40,40,30,3,False
331,Lairon,Steel,430,60,90,140,50,50,40,3,False
332,Aggron,Steel,530,70,110,180,60,60,50,3,False
333,AggronMega Aggron,Steel,630,70,140,230,60,80,50,3,False
334,Meditite,Fighting,280,30,40,55,40,55,60,3,False
335,Medicham,Fighting,410,60,60,75,60,75,80,3,False
336,MedichamMega Medicham,Fighting,510,60,100,85,80,85,100,3,False
337,Electrike,Electric,295,40,45,40,65,40,65,3,False
338,Manectric,Electric,475,70,75,60,105,60,105,3,False
339,ManectricMega Manectric,Electric,575,70,75,80,135,80,135,3,False
340,Plusle,Electric,405,60,50,40,85,75,95,3,False
341,Minun,Electric,405,60,40,50,75,85,95,3,False
342,Volbeat,Bug,400,65,73,55,47,75,85,3,False
343,Illumise,Bug,400,65,47,55,73,75,85,3,False
344,Roselia,Grass,400,50,60,45,100,80,65,3,False
345,Gulpin,Poison,302,70,43,53,43,53,40,3,False
346,Swalot,Poison,467,100,73,83,73,83,55,3,False
352,Numel,Fire,305,60,60,40,65,45,35,3,False
353,Camerupt,Fire,460,70,100,70,105,75,40,3,False
354,CameruptMega Camerupt,Fire,560,70,120,100,145,105,20,3,False
355,Torkoal,Fire,470,70,85,140,85,70,20,3,False
356,Spoink,Psychic,330,60,25,35,70,80,60,3,False
357,Grumpig,Psychic,470,80,45,65,90,110,80,3,False
358,Spinda,Normal,360,60,60,60,60,60,60,3,False
359,Trapinch,Ground,290,45,100,45,45,45,10,3,False
360,Vibrava,Ground,340,50,70,50,50,50,70,3,False
361,Flygon,Ground,520,80,100,80,80,80,100,3,False
362,Cacnea,Grass,335,50,85,40,85,40,35,3,False
363,Cacturne,Grass,475,70,115,60,115,60,55,3,False
364,Swablu,Normal,310,45,40,60,40,75,50,3,False
365,Altaria,Dragon,490,75,70,90,70,105,80,3,False
366,AltariaMega Altaria,Dragon,590,75,110,110,110,105,80,3,False
367,Zangoose,Normal,458,73,115,60,60,60,90,3,False
368,Seviper,Poison,458,73,100,60,100,60,65,3,False
369,Lunatone,Rock,440,70,55,65,95,85,70,3,False
370,Solrock,Rock,440,70,95,85,55,65,70,3,False
375,Baltoy,Ground,300,40,40,55,40,70,55,3,False
376,Claydol,Ground,500,60,70,105,70,120,75,3,False
377,Lileep,Rock,355,66,41,77,61,87,23,3,False
378,Cradily,Rock,495,86,81,97,81,107,43,3,False
379,Anorith,Rock,355,45,95,50,40,50,75,3,False
380,Armaldo,Rock,495,75,125,100,70,80,45,3,False
383,Castform,Normal,420,70,70,70,70,70,70,3,False
384,Kecleon,Normal,440,60,90,70,60,120,40,3,False
385,Shuppet,Ghost,295,44,75,35,63,33,45,3,False
386,Banette,Ghost,455,64,115,65,83,63,65,3,False
387,BanetteMega Banette,Ghost,555,64,165,75,93,83,75,3,False
388,Duskull,Ghost,295,20,40,90,30,90,25,3,False
389,Dusclops,Ghost,455,40,70,130,60,130,25,3,False
390,Tropius,Grass,460,99,68,83,72,87,51,3,False
391,Chimecho,Psychic,425,65,50,70,95,80,65,3,False
392,Absol,Dark,465,65,130,60,75,60,75,3,False
393,AbsolMega Absol,Dark,565,65,150,60,115,60,115,3,False
394,Wynaut,Psychic,260,95,23,48,23,48,23,3,False
395,Snorunt,Ice,300,50,50,50,50,50,50,3,False
396,Glalie,Ice,480,80,80,80,80,80,80,3,False
397,GlalieMega Glalie,Ice,580,80,120,80,120,80,100,3,False
398,Spheal,Ice,290,70,40,50,55,50,25,3,False
399,Sealeo,Ice,410,90,60,70,75,70,45,3,False
400,Walrein,Ice,530,110,80,90,95,90,65,3,False
406,Bagon,Dragon,300,45,75,60,40,30,50,3,False
407,Shelgon,Dragon,420,65,95,100,60,50,50,3,False
408,Salamence,Dragon,600,95,135,80,110,80,100,3,False
409,SalamenceMega Salamence,Dragon,700,95,145,130,120,90,120,3,False
410,Beldum,Steel,300,40,55,80,35,60,30,3,False
411,Metang,Steel,420,60,75,100,55,80,50,3,False
412,Metagross,Steel,600,80,135,130,95,90,70,3,False
413,MetagrossMega Metagross,Steel,700,80,145,150,105,110,110,3,False
414,Regirock,Rock,580,80,100,200,50,100,50,3,True
415,Regice,Ice,580,80,50,100,100,200,50,3,True
416,Registeel,Steel,580,80,75,150,75,150,50,3,True
417,Latias,Dragon,600,80,80,90,110,130,110,3,True
418,LatiasMega Latias,Dragon,700,80,100,120,140,150,110,3,True
419,Latios,Dragon,600,80,90,80,130,110,110,3,True
420,LatiosMega Latios,Dragon,700,80,130,100,160,120,110,3,True
423,Groudon,Ground,670,100,150,140,100,90,90,3,True
424,GroudonPrimal Groudon,Ground,770,100,180,160,150,90,90,3,True
425,Rayquaza,Dragon,680,105,150,90,150,90,95,3,True
426,RayquazaMega Rayquaza,Dragon,780,105,180,100,180,100,115,3,True
427,Jirachi,Steel,600,100,100,100,100,100,100,3,True
428,DeoxysNormal Forme,Psychic,600,50,150,50,150,50,150,3,True
429,DeoxysAttack Forme,Psychic,600,50,180,20,180,20,150,3,True
430,DeoxysDefense Forme,Psychic,600,50,70,160,70,160,90,3,True
431,DeoxysSpeed Forme,Psychic,600,50,95,90,95,90,180,3,True
432,Turtwig,Grass,318,55,68,64,45,55,31,4,False
433,Grotle,Grass,405,75,89,85,55,65,36,4,False
434,Torterra,Grass,525,95,109,105,75,85,56,4,False
435,Chimchar,Fire,309,44,58,44,58,44,61,4,False
436,Monferno,Fire,405,64,78,52,78,52,81,4,False
437,Infernape,Fire,534,76,104,71,104,71,108,4,False
441,Starly,Normal,245,40,55,30,30,30,60,4,False
442,Staravia,Normal,340,55,75,50,40,40,80,4,False
443,Staraptor,Normal,485,85,120,70,50,60,100,4,False
444,Bidoof,Normal,250,59,45,40,35,40,31,4,False
445,Bibarel,Normal,410,79,85,60,55,60,71,4,False
446,Kricketot,Bug,194,37,25,41,25,41,25,4,False
447,Kricketune,Bug,384,77,85,51,55,51,65,4,False
448,Shinx,Electric,263,45,65,34,40,34,45,4,False
449,Luxio,Electric,363,60,85,49,60,49,60,4,False
450,Luxray,Electric,523,80,120,79,95,79,70,4,False
451,Budew,Grass,280,40,30,35,50,70,55,4,False
452,Roserade,Grass,515,60,70,65,125,105,90,4,False
453,Cranidos,Rock,350,67,125,40,30,30,58,4,False
454,Rampardos,Rock,495,97,165,60,65,50,58,4,False
455,Shieldon,Rock,350,30,42,118,42,88,30,4,False
456,Bastiodon,Rock,495,60,52,168,47,138,30,4,False
457,Burmy,Bug,224,40,29,45,29,45,36,4,False
458,WormadamPlant Cloak,Bug,424,60,59,85,79,105,36,4,False
459,WormadamSandy Cloak,Bug,424,60,79,105,59,85,36,4,False
460,WormadamTrash Cloak,Bug,424,60,69,95,69,95,36,4,False
461,Mothim,Bug,424,70,94,50,94,50,66,4,False
462,Combee,Bug,244,30,30,42,30,42,70,4,False
463,Vespiquen,Bug,474,70,80,102,80,102,40,4,False
464,Pachirisu,Electric,405,60,45,70,45,90,95,4,False
467,Cherubi,Grass,275,45,35,45,62,53,35,4,False
468,Cherrim,Grass,450,70,60,70,87,78,85,4,False
471,Ambipom,Normal,482,75,100,66,60,66,115,4,False
472,Drifloon,Ghost,348,90,50,34,60,44,70,4,False
473,Drifblim,Ghost,498,150,80,44,90,54,80,4,False
474,Buneary,Normal,350,55,66,44,44,56,85,4,False
475,Lopunny,Normal,480,65,76,84,54,96,105,4,False

In [54]:
df[~(df['Legendary']==True)]

,Name,Type 1,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,318,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,405,60,62,63,80,80,60,1,False
2,Venusaur,Grass,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,309,39,52,43,60,50,65,1,False
5,Charmeleon,Fire,405,58,64,58,80,65,80,1,False
6,Charizard,Fire,534,78,84,78,109,85,100,1,False
7,CharizardMega Charizard X,Fire,634,78,130,111,130,85,100,1,False
8,CharizardMega Charizard Y,Fire,634,78,104,78,159,115,100,1,False
9,Squirtle,Water,314,44,48,65,50,64,43,1,False
10,Wartortle,Water,405,59,63,80,65,80,58,1,False
11,Blastoise,Water,530,79,83,100,85,105,78,1,False
12,BlastoiseMega Blastoise,Water,630,79,103,120,135,115,78,1,False
13,Caterpie,Bug,195,45,30,35,20,20,45,1,False
14,Metapod,Bug,205,50,20,55,25,25,30,1,False
15,Butterfree,Bug,395,60,45,50,90,80,70,1,False
16,Weedle,Bug,195,40,35,30,20,20,50,1,False
17,Kakuna,Bug,205,45,25,50,25,25,35,1,False
18,Beedrill,Bug,395,65,90,40,45,80,75,1,False
19,BeedrillMega Beedrill,Bug,495,65,150,40,15,80,145,1,False
20,Pidgey,Normal,251,40,45,40,35,35,56,1,False
21,Pidgeotto,Normal,349,63,60,55,50,50,71,1,False
22,Pidgeot,Normal,479,83,80,75,70,70,101,1,False
23,PidgeotMega Pidgeot,Normal,579,83,80,80,135,80,121,1,False
24,Rattata,Normal,253,30,56,35,25,35,72,1,False
25,Raticate,Normal,413,55,81,60,50,70,97,1,False
26,Spearow,Normal,262,40,60,30,31,31,70,1,False
27,Fearow,Normal,442,65,90,65,61,61,100,1,False
28,Ekans,Poison,288,35,60,44,40,54,55,1,False
29,Arbok,Poison,438,60,85,69,65,79,80,1,False
30,Pikachu,Electric,320,35,55,40,50,50,90,1,False
31,Raichu,Electric,485,60,90,55,90,80,110,1,False
32,Sandshrew,Ground,300,50,75,85,20,30,40,1,False
33,Sandslash,Ground,450,75,100,110,45,55,65,1,False
34,Nidoran (Female),Poison,275,55,47,52,40,40,41,1,False
35,Nidorina,Poison,365,70,62,67,55,55,56,1,False
36,Nidoqueen,Poison,505,90,92,87,75,85,76,1,False
37,Nidoran (Male),Poison,273,46,57,40,40,40,50,1,False
38,Nidorino,Poison,365,61,72,57,55,55,65,1,False
39,Nidoking,Poison,505,81,102,77,85,75,85,1,False
40,Clefairy,Fairy,323,70,45,48,60,65,35,1,False
41,Clefable,Fairy,483,95,70,73,95,90,60,1,False
42,Vulpix,Fire,299,38,41,40,50,65,65,1,False
43,Ninetales,Fire,505,73,76,75,81,100,100,1,False
44,Jigglypuff,Normal,270,115,45,20,45,25,20,1,False
45,Wigglytuff,Normal,435,140,70,45,85,50,45,1,False
46,Zubat,Poison,245,40,45,35,30,40,55,1,False
47,Golbat,Poison,455,75,80,70,65,75,90,1,False
48,Oddish,Grass,320,45,50,55,75,65,30,1,False
49,Gloom,Grass,395,60,65,70,85,75,40,1,False
50,Vileplume,Grass,490,75,80,85,110,90,50,1,False
51,Paras,Bug,285,35,70,55,45,55,25,1,False
52,Parasect,Bug,405,60,95,80,60,80,30,1,False
53,Venonat,Bug,305,60,55,50,40,55,45,1,False
54,Venomoth,Bug,450,70,65,60,90,75,90,1,False
55,Diglett,Ground,265,10,55,25,35,45,95,1,False
56,Dugtrio,Ground,405,35,80,50,50,70,120,1,False
57,Meowth,Normal,290,40,45,35,40,40,90,1,False
58,Persian,Normal,440,65,70,60,65,65,115,1,False
59,Psyduck,Water,320,50,52,48,65,50,55,1,False
60,Golduck,Water,500,80,82,78,95,80,85,1,False
61,Mankey,Fighting,305,40,80,35,35,45,70,1,False
62,Primeape,Fighting,455,65,105,60,60,70,95,1,False
63,Growlithe,Fire,350,55,70,45,70,50,60,1,False
64,Arcanine,Fire,555,90,110,80,100,80,95,1,False
65,Poliwag,Water,300,40,50,40,40,40,90,1,False
66,Poliwhirl,Water,385,65,65,65,50,50,90,1,False
67,Poliwrath,Water,510,90,95,95,70,90,70,1,False
68,Abra,Psychic,310,25,20,15,105,55,90,1,False
69,Kadabra,Psychic,400,40,35,30,120,70,105,1,False
70,Alakazam,Psychic,500,55,50,45,135,95,120,1,False
71,AlakazamMega Alakazam,Psychic,590,55,50,65,175,95,150,1,False
72,Machop,Fighting,305,70,80,50,35,35,35,1,False
73,Machoke,Fighting,405,80,100,70,50,60,45,1,False
74,Machamp,Fighting,505,90,130,80,65,85,55,1,False
75,Bellsprout,Grass,300,50,75,35,70,30,40,1,False
76,Weepinbell,Grass,390,65,90,50,85,45,55,1,False
77,Victreebel,Grass,490,80,105,65,100,70,70,1,False
78,Tentacool,Water,335,40,40,35,50,100,70,1,False
79,Tentacruel,Water,515,80,70,65,80,120,100,1,False
80,Geodude,Rock,300,40,80,100,30,30,20,1,False
81,Graveler,Rock,390,55,95,115,45,45,35,1,False
82,Golem,Rock,495,80,120,130,55,65,45,1,False
83,Ponyta,Fire,410,50,85,55,65,65,90,1,False
84,Rapidash,Fire,500,65,100,70,80,80,105,1,False
85,Slowpoke,Water,315,90,65,65,40,40,15,1,False
86,Slowbro,Water,490,95,75,110,100,80,30,1,False
87,SlowbroMega Slowbro,Water,590,95,75,180,130,80,30,1,False
88,Magnemite,Electric,325,25,35,70,95,55,45,1,False
89,Magneton,Electric,465,50,60,95,120,70,70,1,False
90,Farfetch'd,Normal,352,52,65,55,58,62,60,1,False
91,Doduo,Normal,310,35,85,45,35,35,75,1,False
92,Dodrio,Normal,460,60,110,70,60,60,100,1,False
93,Seel,Water,325,65,45,55,45,70,45,1,False
94,Dewgong,Water,475,90,70,80,70,95,70,1,False
95,Grimer,Poison,325,80,80,50,40,50,25,1,False
96,Muk,Poison,500,105,105,75,65,100,50,1,False
97,Shellder,Water,305,30,65,100,45,25,40,1,False
98,Cloyster,Water,525,50,95,180,85,45,70,1,False
99,Gastly,Ghost,310,30,35,30,100,35,80,1,False
100,Haunter,Ghost,405,45,50,45,115,55,95,1,False
101,Gengar,Ghost,500,60,65,60,130,75,110,1,False
102,GengarMega Gengar,Ghost,600,60,65,80,170,95,130,1,False
103,Onix,Rock,385,35,45,160,30,45,70,1,False
104,Drowzee,Psychic,328,60,48,45,43,90,42,1,False
105,Hypno,Psychic,483,85,73,70,73,115,67,1,False
106,Krabby,Water,325,30,105,90,25,25,50,1,False
107,Kingler,Water,475,55,130,115,50,50,75,1,False
108,Voltorb,Electric,330,40,30,50,55,55,100,1,False
109,Electrode,Electric,480,60,50,70,80,80,140,1,False
110,Exeggcute,Grass,325,60,40,80,60,45,40,1,False
111,Exeggutor,Grass,520,95,95,85,125,65,55,1,False
112,Cubone,Ground,320,50,50,95,40,50,35,1,False
113,Marowak,Ground,425,60,80,110,50,80,45,1,False
114,Hitmonlee,Fighting,455,50,120,53,35,110,87,1,False
115,Hitmonchan,Fighting,455,50,105,79,35,110,76,1,False
116,Lickitung,Normal,385,90,55,75,60,75,30,1,False
117,Koffing,Poison,340,40,65,95,60,45,35,1,False
118,Weezing,Poison,490,65,90,120,85,70,60,1,False
119,Rhyhorn,Ground,345,80,85,95,30,30,25,1,False
120,Rhydon,Ground,485,105,130,120,45,45,40,1,False
121,Chansey,Normal,450,250,5,5,35,105,50,1,False
122,Tangela,Grass,435,65,55,115,100,40,60,1,False
123,Kangaskhan,Normal,490,105,95,80,40,80,90,1,False
124,KangaskhanMega Kangaskhan,Normal,590,105,125,100,60,100,100,1,False
125,Horsea,Water,295,30,40,70,70,25,60,1,False
126,Seadra,Water,440,55,65,95,95,45,85,1,False
127,Goldeen,Water,320,45,67,60,35,50,63,1,False
128,Seaking,Water,450,80,92,65,65,80,68,1,False
129,Staryu,Water,340,30,45,55,70,55,85,1,False
130,Starmie,Water,520,60,75,85,100,85,115,1,False
131,Mr. Mime,Psychic,460,40,45,65,100,120,90,1,False
132,Scyther,Bug,500,70,110,80,55,80,105,1,False
133,Jynx,Ice,455,65,50,35,115,95,95,1,False
134,Electabuzz,Electric,490,65,83,57,95,85,105,1,False
135,Magmar,Fire,495,65,95,57,100,85,93,1,False
136,Pinsir,Bug,500,65,125,100,55,70,85,1,False
137,PinsirMega Pinsir,Bug,600,65,155,120,65,90,105,1,False
138,Tauros,Normal,490,75,100,95,40,70,110,1,False
139,Magikarp,Water,200,20,10,55,15,20,80,1,False
140,Gyarados,Water,540,95,125,79,60,100,81,1,False
141,GyaradosMega Gyarados,Water,640,95,155,109,70,130,81,1,False
142,Lapras,Water,535,130,85,80,85,95,60,1,False
143,Ditto,Normal,288,48,48,48,48,48,48,1,False
144,Eevee,Normal,325,55,55,50,45,65,55,1,False
145,Vaporeon,Water,525,130,65,60,110,95,65,1,False
146,Jolteon,Electric,525,65,65,60,110,95,130,1,False
147,Flareon,Fire,525,65,130,60,95,110,65,1,False
148,Porygon,Normal,395,65,60,70,85,75,40,1,False
149,Omanyte,Rock,355,35,40,100,90,55,35,1,False
150,Omastar,Rock,495,70,60,125,115,70,55,1,False
151,Kabuto,Rock,355,30,80,90,55,45,55,1,False
152,Kabutops,Rock,495,60,115,105,65,70,80,1,False
153,Aerodactyl,Rock,515,80,105,65,60,75,130,1,False
154,AerodactylMega Aerodactyl,Rock,615,80,135,85,70,95,150,1,False
155,Snorlax,Normal,540,160,110,65,65,110,30,1,False
159,Dratini,Dragon,300,41,64,45,50,50,50,1,False
160,Dragonair,Dragon,420,61,84,65,70,70,70,1,False
161,Dragonite,Dragon,600,91,134,95,100,100,80,1,False
165,Mew,Psychic,600,100,100,100,100,100,100,1,False
166,Chikorita,Grass,318,45,49,65,49,65,45,2,False
167,Bayleef,Grass,405,60,62,80,63,80,60,2,False
168,Meganium,Grass,525,80,82,100,83,100,80,2,False
169,Cyndaquil,Fire,309,39,52,43,60,50,65,2,False
170,Quilava,Fire,405,58,64,58,80,65,80,2,False
171,Typhlosion,Fire,534,78,84,78,109,85,100,2,False
172,Totodile,Water,314,50,65,64,44,48,43,2,False
173,Croconaw,Water,405,65,80,80,59,63,58,2,False
174,Feraligatr,Water,530,85,105,100,79,83,78,2,False
175,Sentret,Normal,215,35,46,34,35,45,20,2,False
176,Furret,Normal,415,85,76,64,45,55,90,2,False
177,Hoothoot,Normal,262,60,30,30,36,56,50,2,False
178,Noctowl,Normal,442,100,50,50,76,96,70,2,False
179,Ledyba,Bug,265,40,20,30,40,80,55,2,False
180,Ledian,Bug,390,55,35,50,55,110,85,2,False
181,Spinarak,Bug,250,40,60,40,40,40,30,2,False
182,Ariados,Bug,390,70,90,70,60,60,40,2,False
183,Crobat,Poison,535,85,90,80,70,80,130,2,False
184,Chinchou,Water,330,75,38,38,56,56,67,2,False
185,Lanturn,Water,460,125,58,58,76,76,67,2,False
186,Pichu,Electric,205,20,40,15,35,35,60,2,False
187,Cleffa,Fairy,218,50,25,28,45,55,15,2,False
188,Igglybuff,Normal,210,90,30,15,40,20,15,2,False
189,Togepi,Fairy,245,35,20,65,40,65,20,2,False
190,Togetic,Fairy,405,55,40,85,80,105,40,2,False
191,Natu,Psychic,320,40,50,45,70,45,70,2,False
192,Xatu,Psychic,470,65,75,70,95,70,95,2,False
193,Mareep,Electric,280,55,40,40,65,45,35,2,False
194,Flaaffy,Electric,365,70,55,55,80,60,45,2,False
195,Ampharos,Electric,510,90,75,85,115,90,55,2,False
196,AmpharosMega Ampharos,Electric,610,90,95,105,165,110,45,2,False
197,Bellossom,Grass,490,75,80,95,90,100,50,2,False
198,Marill,Water,250,70,20,50,20,50,40,2,False
199,Azumarill,Water,420,100,50,80,60,80,50,2,False
200,Sudowoodo,Rock,410,70,100,115,30,65,30,2,False
201,Politoed,Water,500,90,75,75,90,100,70,2,False
202,Hoppip,Grass,250,35,35,40,35,55,50,2,False
203,Skiploom,Grass,340,55,45,50,45,65,80,2,False
204,Jumpluff,Grass,460,75,55,70,55,95,110,2,False
205,Aipom,Normal,360,55,70,55,40,55,85,2,False
206,Sunkern,Grass,180,30,30,30,30,30,30,2,False
207,Sunflora,Grass,425,75,75,55,105,85,30,2,False
208,Yanma,Bug,390,65,65,45,75,45,95,2,False
209,Wooper,Water,210,55,45,45,25,25,15,2,False
210,Quagsire,Water,430,95,85,85,65,65,35,2,False
211,Espeon,Psychic,525,65,65,60,130,95,110,2,False
212,Umbreon,Dark,525,95,65,110,60,130,65,2,False
213,Murkrow,Dark,405,60,85,42,85,42,91,2,False
214,Slowking,Water,490,95,75,80,100,110,30,2,False
215,Misdreavus,Ghost,435,60,60,60,85,85,85,2,False
216,Unown,Psychic,336,48,72,48,72,48,48,2,False
217,Wobbuffet,Psychic,405,190,33,58,33,58,33,2,False
218,Girafarig,Normal,455,70,80,65,90,65,85,2,False
219,Pineco,Bug,290,50,65,90,35,35,15,2,False
220,Forretress,Bug,465,75,90,140,60,60,40,2,False
221,Dunsparce,Normal,415,100,70,70,65,65,45,2,False
222,Gligar,Ground,430,65,75,105,35,65,85,2,False
223,Steelix,Steel,510,75,85,200,55,65,30,2,False
224,SteelixMega Steelix,Steel,610,75,125,230,55,95,30,2,False
225,Snubbull,Fairy,300,60,80,50,40,40,30,2,False
226,Granbull,Fairy,450,90,120,75,60,60,45,2,False
227,Qwilfish,Water,430,65,95,75,55,55,85,2,False
228,Scizor,Bug,500,70,130,100,55,80,65,2,False
229,ScizorMega Scizor,Bug,600,70,150,140,65,100,75,2,False
230,Shuckle,Bug,505,20,10,230,10,230,5,2,False
231,Heracross,Bug,500,80,125,75,40,95,85,2,False
232,HeracrossMega Heracross,Bug,600,80,185,115,40,105,75,2,False
233,Sneasel,Dark,430,55,95,55,35,75,115,2,False
234,Teddiursa,Normal,330,60,80,50,50,50,40,2,False
235,Ursaring,Normal,500,90,130,75,75,75,55,2,False
236,Slugma,Fire,250,40,40,40,70,40,20,2,False
237,Magcargo,Fire,410,50,50,120,80,80,30,2,False
238,Swinub,Ice,250,50,50,40,30,30,50,2,False
239,Piloswine,Ice,450,100,100,80,60,60,50,2,False
240,Corsola,Water,380,55,55,85,65,85,35,2,False
241,Remoraid,Water,300,35,65,35,65,35,65,2,False
242,Octillery,Water,480,75,105,75,105,75,45,2,False
243,Delibird,Ice,330,45,55,45,65,45,75,2,False
244,Mantine,Water,465,65,40,70,80,140,70,2,False
245,Skarmory,Steel,465,65,80,140,40,70,70,2,False
246,Houndour,Dark,330,45,60,30,80,50,65,2,False
247,Houndoom,Dark,500,75,90,50,110,80,95,2,False
248,HoundoomMega Houndoom,Dark,600,75,90,90,140,90,115,2,False
249,Kingdra,Water,540,75,95,95,95,95,85,2,False
250,Phanpy,Ground,330,90,60,60,40,40,40,2,False
251,Donphan,Ground,500,90,120,120,60,60,50,2,False
252,Porygon2,Normal,515,85,80,90,105,95,60,2,False
253,Stantler,Normal,465,73,95,62,85,65,85,2,False
254,Smeargle,Normal,250,55,20,35,20,45,75,2,False
255,Tyrogue,Fighting,210,35,35,35,35,35,35,2,False
256,Hitmontop,Fighting,455,50,95,95,35,110,70,2,False
257,Smoochum,Ice,305,45,30,15,85,65,65,2,False
258,Elekid,Electric,360,45,63,37,65,55,95,2,False
259,Magby,Fire,365,45,75,37,70,55,83,2,False
260,Miltank,Normal,490,95,80,105,40,70,100,2,False
261,Blissey,Normal,540,255,10,10,75,135,55,2,False
265,Larvitar,Rock,300,50,64,50,45,50,41,2,False
266,Pupitar,Rock,410,70,84,70,65,70,51,2,False
267,Tyranitar,Rock,600,100,134,110,95,100,61,2,False
268,TyranitarMega Tyranitar,Rock,700,100,164,150,95,120,71,2,False
271,Celebi,Psychic,600,100,100,100,100,100,100,2,False
272,Treecko,Grass,310,40,45,35,65,55,70,3,False
273,Grovyle,Grass,405,50,65,45,85,65,95,3,False
274,Sceptile,Grass,530,70,85,65,105,85,120,3,False
275,SceptileMega Sceptile,Grass,630,70,110,75,145,85,145,3,False
276,Torchic,Fire,310,45,60,40,70,50,45,3,False
277,Combusken,Fire,405,60,85,60,85,60,55,3,False
278,Blaziken,Fire,530,80,120,70,110,70,80,3,False
279,BlazikenMega Blaziken,Fire,630,80,160,80,130,80,100,3,False
280,Mudkip,Water,310,50,70,50,50,50,40,3,False
281,Marshtomp,Water,405,70,85,70,60,70,50,3,False
282,Swampert,Water,535,100,110,90,85,90,60,3,False
283,SwampertMega Swampert,Water,635,100,150,110,95,110,70,3,False
284,Poochyena,Dark,220,35,55,35,30,30,35,3,False
285,Mightyena,Dark,420,70,90,70,60,60,70,3,False
286,Zigzagoon,Normal,240,38,30,41,30,41,60,3,False
287,Linoone,Normal,420,78,70,61,50,61,100,3,False
288,Wurmple,Bug,195,45,45,35,20,30,20,3,False
289,Silcoon,Bug,205,50,35,55,25,25,15,3,False
290,Beautifly,Bug,395,60,70,50,100,50,65,3,False
291,Cascoon,Bug,205,50,35,55,25,25,15,3,False
292,Dustox,Bug,385,60,50,70,50,90,65,3,False
293,Lotad,Water,220,40,30,30,40,50,30,3,False
294,Lombre,Water,340,60,50,50,60,70,50,3,False
295,Ludicolo,Water,480,80,70,70,90,100,70,3,False
296,Seedot,Grass,220,40,40,50,30,30,30,3,False
297,Nuzleaf,Grass,340,70,70,40,60,40,60,3,False
298,Shiftry,Grass,480,90,100,60,90,60,80,3,False
299,Taillow,Normal,270,40,55,30,30,30,85,3,False
300,Swellow,Normal,430,60,85,60,50,50,125,3,False
301,Wingull,Water,270,40,30,30,55,30,85,3,False
302,Pelipper,Water,430,60,50,100,85,70,65,3,False
303,Ralts,Psychic,198,28,25,25,45,35,40,3,False
304,Kirlia,Psychic,278,38,35,35,65,55,50,3,False
305,Gardevoir,Psychic,518,68,65,65,125,115,80,3,False
306,GardevoirMega Gardevoir,Psychic,618,68,85,65,165,135,100,3,False
307,Surskit,Bug,269,40,30,32,50,52,65,3,False
308,Masquerain,Bug,414,70,60,62,80,82,60,3,False
309,Shroomish,Grass,295,60,40,60,40,60,35,3,False
310,Breloom,Grass,460,60,130,80,60,60,70,3,False
311,Slakoth,Normal,280,60,60,60,35,35,30,3,False
312,Vigoroth,Normal,440,80,80,80,55,55,90,3,False
313,Slaking,Normal,670,150,160,100,95,65,100,3,False
314,Nincada,Bug,266,31,45,90,30,30,40,3,False
315,Ninjask,Bug,456,61,90,45,50,50,160,3,False
316,Shedinja,Bug,236,1,90,45,30,30,40,3,False
317,Whismur,Normal,240,64,51,23,51,23,28,3,False
318,Loudred,Normal,360,84,71,43,71,43,48,3,False
319,Exploud,Normal,490,104,91,63,91,73,68,3,False
320,Makuhita,Fighting,237,72,60,30,20,30,25,3,False
321,Hariyama,Fighting,474,144,120,60,40,60,50,3,False
322,Azurill,Normal,190,50,20,40,20,40,20,3,False
323,Nosepass,Rock,375,30,45,135,45,90,30,3,False
324,Skitty,Normal,260,50,45,45,35,35,50,3,False
325,Delcatty,Normal,380,70,65,65,55,55,70,3,False
326,Sableye,Dark,380,50,75,75,65,65,50,3,False
327,SableyeMega Sableye,Dark,480,50,85,125,85,115,20,3,False
328,Mawile,Steel,380,50,85,85,55,55,50,3,False
329,MawileMega Mawile,Steel,480,50,105,125,55,95,50,3,False
330,Aron,Steel,330,50,70,100,40,40,30,3,False
331,Lairon,Steel,430,60,90,140,50,50,40,3,False
332,Aggron,Steel,530,70,110,180,60,60,50,3,False
333,AggronMega Aggron,Steel,630,70,140,230,60,80,50,3,False
334,Meditite,Fighting,280,30,40,55,40,55,60,3,False
335,Medicham,Fighting,410,60,60,75,60,75,80,3,False
336,MedichamMega Medicham,Fighting,510,60,100,85,80,85,100,3,False
337,Electrike,Electric,295,40,45,40,65,40,65,3,False
338,Manectric,Electric,475,70,75,60,105,60,105,3,False
339,ManectricMega Manectric,Electric,575,70,75,80,135,80,135,3,False
340,Plusle,Electric,405,60,50,40,85,75,95,3,False
341,Minun,Electric,405,60,40,50,75,85,95,3,False
342,Volbeat,Bug,400,65,73,55,47,75,85,3,False
343,Illumise,Bug,400,65,47,55,73,75,85,3,False
344,Roselia,Grass,400,50,60,45,100,80,65,3,False
345,Gulpin,Poison,302,70,43,53,43,53,40,3,False
346,Swalot,Poison,467,100,73,83,73,83,55,3,False
347,Carvanha,Water,305,45,90,20,65,20,65,3,False
348,Sharpedo,Water,460,70,120,40,95,40,95,3,False
349,SharpedoMega Sharpedo,Water,560,70,140,70,110,65,105,3,False
350,Wailmer,Water,400,130,70,35,70,35,60,3,False
351,Wailord,Water,500,170,90,45,90,45,60,3,False
352,Numel,Fire,305,60,60,40,65,45,35,3,False
353,Camerupt,Fire,460,70,100,70,105,75,40,3,False
354,CameruptMega Camerupt,Fire,560,70,120,100,145,105,20,3,False
355,Torkoal,Fire,470,70,85,140,85,70,20,3,False
356,Spoink,Psychic,330,60,25,35,70,80,60,3,False
357,Grumpig,Psychic,470,80,45,65,90,110,80,3,False
358,Spinda,Normal,360,60,60,60,60,60,60,3,False
359,Trapinch,Ground,290,45,100,45,45,45,10,3,False
360,Vibrava,Ground,340,50,70,50,50,50,70,3,False
361,Flygon,Ground,520,80,100,80,80,80,100,3,False
362,Cacnea,Grass,335,50,85,40,85,40,35,3,False
363,Cacturne,Grass,475,70,115,60,115,60,55,3,False
364,Swablu,Normal,310,45,40,60,40,75,50,3,False
365,Altaria,Dragon,490,75,70,90,70,105,80,3,False
366,AltariaMega Altaria,Dragon,590,75,110,110,110,105,80,3,False
367,Zangoose,Normal,458,73,115,60,60,60,90,3,False
368,Seviper,Poison,458,73,100,60,100,60,65,3,False
369,Lunatone,Rock,440,70,55,65,95,85,70,3,False
370,Solrock,Rock,440,70,95,85,55,65,70,3,False
371,Barboach,Water,288,50,48,43,46,41,60,3,False
372,Whiscash,Water,468,110,78,73,76,71,60,3,False
373,Corphish,Water,308,43,80,65,50,35,35,3,False
374,Crawdaunt,Water,468,63,120,85,90,55,55,3,False
375,Baltoy,Ground,300,40,40,55,40,70,55,3,False
376,Claydol,Ground,500,60,70,105,70,120,75,3,False
377,Lileep,Rock,355,66,41,77,61,87,23,3,False
378,Cradily,Rock,495,86,81,97,81,107,43,3,False
379,Anorith,Rock,355,45,95,50,40,50,75,3,False
380,Armaldo,Rock,495,75,125,100,70,80,45,3,False
381,Feebas,Water,200,20,15,20,10,55,80,3,False
382,Milotic,Water,540,95,60,79,100,125,81,3,False
383,Castform,Normal,420,70,70,70,70,70,70,3,False
384,Kecleon,Normal,440,60,90,70,60,120,40,3,False
385,Shuppet,Ghost,295,44,75,35,63,33,45,3,False
386,Banette,Ghost,455,64,115,65,83,63,65,3,False
387,BanetteMega Banette,Ghost,555,64,165,75,93,83,75,3,False
388,Duskull,Ghost,295,20,40,90,30,90,25,3,False
389,Dusclops,Ghost,455,40,70,130,60,130,25,3,False
390,Tropius,Grass,460,99,68,83,72,87,51,3,False
391,Chimecho,Psychic,425,65,50,70,95,80,65,3,False
392,Absol,Dark,465,65,130,60,75,60,75,3,False
393,AbsolMega Absol,Dark,565,65,150,60,115,60,115,3,False
394,Wynaut,Psychic,260,95,23,48,23,48,23,3,False
395,Snorunt,Ice,300,50,50,50,50,50,50,3,False
396,Glalie,Ice,480,80,80,80,80,80,80,3,False
397,GlalieMega Glalie,Ice,580,80,120,80,120,80,100,3,False
398,Spheal,Ice,290,70,40,50,55,50,25,3,False
399,Sealeo,Ice,410,90,60,70,75,70,45,3,False
400,Walrein,Ice,530,110,80,90,95,90,65,3,False
401,Clamperl,Water,345,35,64,85,74,55,32,3,False
402,Huntail,Water,485,55,104,105,94,75,52,3,False
403,Gorebyss,Water,485,55,84,105,114,75,52,3,False
404,Relicanth,Water,485,100,90,130,45,65,55,3,False
405,Luvdisc,Water,330,43,30,55,40,65,97,3,False
406,Bagon,Dragon,300,45,75,60,40,30,50,3,False

In [49]:
df[df['Name']=='Pikachu']#To find the any name in the data

,Name,Type 1,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
30,Pikachu,Electric,320,35,55,40,50,50,90,1,False