In [1]:
import numpy as np
import pandas as pd

In [2]:
d={
    'Name':['abc','xyz'],
    'Age':[50,30],
    'Marks':[150.5,175]
}

In [3]:
df= pd.DataFrame(d)
df

  Name  Age  Marks
0  abc   50  150.5
1  xyz   30  175.0

In [4]:
df.shape

(2, 3)

In [5]:
df['Marks'].dtype

dtype('float64')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      object
 1   Age     2 non-null      int64
 2   Marks   2 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 180.0+ bytes

In [7]:
df.set_index('Age', inplace=True) # making row to coloumn indexing------inplace-true for permanent change

In [8]:
df

    Name  Marks
Age
50   abc  150.5
30   xyz  175.0

In [9]:
df=df.reset_index(drop=True) #drop is for permanet change

In [10]:
df

  Name  Marks
0  abc  150.5
1  xyz  175.0

In [11]:
L=[1,2]

In [12]:
df['Roll_no.']=L # for adding new column

In [13]:
df

  Name  Marks  Roll_no.
0  abc  150.5         1
1  xyz  175.0         2

In [14]:
# one more way to add multiple at ones using loop
l=[i for i in range(1,3)]
df['roll-no']=l
df

  Name  Marks  Roll_no.  roll-no
0  abc  150.5         1        1
1  xyz  175.0         2        2

In [15]:
# using np.array
df['roll']=np.random.randint(10,20,2) ## any random betwwen 10-20 and only 2
df

  Name  Marks  Roll_no.  roll-no  roll
0  abc  150.5         1        1    11
1  xyz  175.0         2        2    19

In [16]:
# deletion of row
df.drop(columns = ['roll-no','roll'], inplace=True)

In [17]:
df

  Name  Marks  Roll_no.
0  abc  150.5         1
1  xyz  175.0         2

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      2 non-null      object
 1   Marks     2 non-null      float64
 2   Roll_no.  2 non-null      int64
dtypes: float64(1), int64(1), object(1)
memory usage: 180.0+ bytes

In [19]:
df['Age']=df['Age'].astype(float)

KeyError: 'Age'

In [ ]:
df

In [ ]:
df['Marks']=df['Marks'].astype(int)
df

In [ ]:
## indexing slicing 
df6=pd.read_csv('ex6.csv')

In [ ]:
df6

In [ ]:
df6.iloc[500:526, 2:4]

In [ ]:
a=[12,np.nan,14,np.nan,26,12,13,24,12,23]
h=[130,np.nan,550,145,123,np.nan,np.nan,np.nan,145,121]
g=['Male',np.nan,'Female','Female','Male','Female','Female',np.nan,'Male','Male']
print(len(a),len(h),len(g))

In [ ]:
df2 = pd.DataFrame({
    'Age': a,
    'Height': h,
    'Gender': g
})
df2

In [ ]:
df2.isnull().sum() ## for cal missing value for perticular column

In [ ]:
df2.isna().sum()/df2.shape[0]*100

In [ ]:
type(df2)

In [ ]:
import warnings 
warnings.filterwarnings('ignore')

In [ ]:
df2['Age']=df2['Age'].mean()

In [ ]:
df2

In [ ]:
df2['Age'].mean()

In [ ]:
df2['Age'].median()

In [ ]:
df2['Height'].mean()

In [ ]:
df2['Height'].median()

In [ ]:
df2['Gender'].fillna(df2['Gender'].mode()[1],inplace=True)

In [ ]:
df2

In [ ]:
df2['Gender'].nunique()

In [ ]:
df2['Gender'].unique()

In [ ]:
#rename column name
df2.rename(columns={'Age':'A','Height':'H','Gender':'G'}, inplace=True)

In [ ]:
df2

In [ ]:
df2.columns

In [ ]:
# make a dataframe with 2 rows 
# weight height name
data={
    "Name":['Ram','Shyam','Ganshyam'],
    "Height":['135.02cm','136.06cm','120.09cm'],
    "Weight":['35kg','50kg','60kg']
}

In [ ]:
df= pd.DataFrame(data)

In [ ]:
df

In [ ]:
df.info()

In [ ]:
for i in df['Weight']:
    Weight= i.replace('kg','')
    print(float(Weight))

In [ ]:
import pandas as pd
data=pd.DataFrame({'company':["Google","ebay",'gartner','Exl','concentrix','Max'],
                  'Person':['Deepanshu','Dereck','Roman','Aman','verma','sam'],
                  'Sales':[200,1000,340,550,0,225]})

In [ ]:
data['num_char'] = data['company'].apply(lambda y : len(y))

In [ ]:
data

In [ ]:
for i in data['company']:
    print(len(i))

In [ ]:
data['num_char'] = data['company'].apply(lambda y : len(y))

In [ ]:
data['target'] = data['Sales'].apply(lambda i :'yes' if i>225 else 'no') 
data
# data['target']=[high_sal = data['']>225]]

In [ ]:
data['initial'] = data['Person'].apply(lambda k :k.ca if i>225 else 'no')

In [ ]:
data['inital'] = data['Person'].apply(lambda x: x[0].swapcase() + x[1:])
data

In [ ]:
new_person = []
for person in data['Person']:
    new_person.append(person[0].swapcase() + person[1:])

data['Person'] = new_person
data['New_Col'] = 'New'

In [ ]:
data['Person'].apply(lambda z : z.swapcase() if z[0].isupper() else z.upper() if len(z)>4 else z[0:-1]+z[-1].upper())

In [ ]:
df1=pd.DataFrame({'A':['A0','A1','A2','A3'],
             'B':['B0','B1','B2','B3'],
             'C':['C0','C1','C2','C3'],
             'D':['D0','D1','D2','D3']},index=[0,1,2,3])
df1

In [ ]:
pd.concat([df1,df3],axis =0)# .reset_index(drop=True) # when col are common

In [ ]:
pd.concat([df1,df4],axis =1)# .reset_index(drop=True) # when row are common

In [ ]:
df3=pd.DataFrame({'A':['A8','A9','A10','A11'],
             'B':['B8','B9','B10','B11'],
             'C':['C8','C9','C10','C11'],
             'D':['D8','D9','D10','D11']},index=[8,9,10,11])
df3

In [ ]:
df2=pd.DataFrame({'A':['A4','A5','A6','A7'],
             'B':['B4','B5','B6','B7'],
             'C':['C4','C5','C6','C7'],
             'D':['D4','D5','D6','D7']},index=[4,5,6,7])
df2

In [ ]:
df4=pd.DataFrame({'E':['E0','E1','E2','E3'],
             'F':['F0','F1','F2','F3'],
             'G':['G0','G1','G2','G3'],
             'H':['H0','H1','H2','H3']})
df4

In [ ]:
import pandas as pd
X=pd.DataFrame({'Key':['k0','k8','k2','k3'],
      'A':['A0','A1','A2','A3'],
      'B':['B0','B1','B2','B3']})


Y=pd.DataFrame({'Key':['k0','k1','k2','k3'],
       'C':['C0','C1','C2','C3'],
       'D':['D0','D1','D2','D3']})

In [ ]:
X

In [ ]:
Y

In [ ]:
pd.merge(X,Y,how='right',on='Key')

In [ ]:
pd.merge(X,Y,how='left',on='Key')

In [ ]:
pd.merge(X,Y,how='inner',on='Key') # common

In [ ]:
pd.merge(X,Y,how='outer',on='Key') #

In [ ]:
data

In [ ]:
# data['company'].apply(lambda a: ''

# Date time

In [21]:
d= pd.date_range('1-1-2020', periods=367)

In [22]:
d

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10',
               ...
               '2020-12-23', '2020-12-24', '2020-12-25', '2020-12-26',
               '2020-12-27', '2020-12-28', '2020-12-29', '2020-12-30',
               '2020-12-31', '2021-01-01'],
              dtype='datetime64[ns]', length=367, freq='D')

In [24]:
df = pd.DataFrame(d,columns=['Date'])

In [25]:
df

          Date
0   2020-01-01
1   2020-01-02
2   2020-01-03
3   2020-01-04
4   2020-01-05
..         ...
362 2020-12-28
363 2020-12-29
364 2020-12-30
365 2020-12-31
366 2021-01-01

[367 rows x 1 columns]

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 367 entries, 0 to 366
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    367 non-null    datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 3.0 KB

In [28]:
df['Year']= df['Date'].dt.year
df['month']= df['Date'].dt.month
df['day']= df['Date'].dt.day

In [29]:
df

          Date  Year  month  day
0   2020-01-01  2020      1    1
1   2020-01-02  2020      1    2
2   2020-01-03  2020      1    3
3   2020-01-04  2020      1    4
4   2020-01-05  2020      1    5
..         ...   ...    ...  ...
362 2020-12-28  2020     12   28
363 2020-12-29  2020     12   29
364 2020-12-30  2020     12   30
365 2020-12-31  2020     12   31
366 2021-01-01  2021      1    1

[367 rows x 4 columns]

In [31]:
df['Day1']=df['Date'].dt.day_name()
df['mon']=df['Date'].dt.month_name()

In [32]:
df

          Date  Year  month  day       Day1       mon
0   2020-01-01  2020      1    1  Wednesday   January
1   2020-01-02  2020      1    2   Thursday   January
2   2020-01-03  2020      1    3     Friday   January
3   2020-01-04  2020      1    4   Saturday   January
4   2020-01-05  2020      1    5     Sunday   January
..         ...   ...    ...  ...        ...       ...
362 2020-12-28  2020     12   28     Monday  December
363 2020-12-29  2020     12   29    Tuesday  December
364 2020-12-30  2020     12   30  Wednesday  December
365 2020-12-31  2020     12   31   Thursday  December
366 2021-01-01  2021      1    1     Friday   January

[367 rows x 6 columns]

In [33]:
df['Sales']= np.random.randint(100,10000,df.shape[0])

In [34]:
df

          Date  Year  month  day       Day1       mon  Sales
0   2020-01-01  2020      1    1  Wednesday   January   6309
1   2020-01-02  2020      1    2   Thursday   January   9261
2   2020-01-03  2020      1    3     Friday   January   1460
3   2020-01-04  2020      1    4   Saturday   January   6547
4   2020-01-05  2020      1    5     Sunday   January   2391
..         ...   ...    ...  ...        ...       ...    ...
362 2020-12-28  2020     12   28     Monday  December    729
363 2020-12-29  2020     12   29    Tuesday  December   4726
364 2020-12-30  2020     12   30  Wednesday  December   7487
365 2020-12-31  2020     12   31   Thursday  December   5616
366 2021-01-01  2021      1    1     Friday   January   1580

[367 rows x 7 columns]