In [1]:
import pandas as pd

In [4]:
df=pd.read_csv('ex1.csv')

In [6]:
df

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [8]:
df.ndim

2

In [9]:
type(df)

pandas.core.frame.DataFrame

In [10]:
df['c']

0     3
1     7
2    11
Name: c, dtype: int64

In [11]:
df['c'].ndim

1

In [12]:
type(df['c'])

pandas.core.series.Series

In [13]:
df[['a','b','message']]

   a   b message
0  1   2   hello
1  5   6   world
2  9  10     foo

In [14]:
pd.read_csv('ex2.csv')

   1   2   3   4  hello
0  5   6   7   8  world
1  9  10  11  12    foo

In [18]:
df2 = pd.read_csv('ex2.csv', header =None, names=['abc','123','%&&^','col4','abc12'])

In [19]:
df2

   abc  123  %&&^  col4  abc12
0    1    2     3     4  hello
1    5    6     7     8  world
2    9   10    11    12    foo

In [30]:
df3= pd.read_excel('ex1.xlsx', index_col=[0])

In [29]:
df3

    Unnamed: 0  a   c   d message
b
2            0  1   3   4   hello
6            1  5   7   8   world
10           2  9  11  12     foo

In [37]:
df4= pd.read_csv('csv_mindex.csv', index_col=['key2','value2'])
df4

            key1  value1
key2 value2
a    2       one       1
b    4       one       3
c    6       one       5
d    8       one       7
a    10      two       9
b    12      two      11
c    14      two      13
d    16      two      15

In [38]:
df4['value1']

key2  value2
a     2          1
b     4          3
c     6          5
d     8          7
a     10         9
b     12        11
c     14        13
d     16        15
Name: value1, dtype: int64

In [41]:
df5= pd.read_csv('ex5.csv')
df5

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [42]:
df5.isnull()

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False   True  False    False
2      False  False  False  False  False    False

In [43]:
df5.isnull().sum() # for column

something    0
a            0
b            0
c            1
d            0
message      1
dtype: int64

In [45]:
df5.isnull().sum().sum() # for intire table

2

In [47]:
df6=pd.read_csv('ex6.csv')
df6

           one       two     three      four key
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
2    -0.501840  0.659254 -0.421691 -0.057688   G
3     0.204886  1.074134  1.388361 -0.982404   R
4     0.354628 -0.133116  0.283763 -0.837063   Q
...        ...       ...       ...       ...  ..
9995  2.311896 -0.417070 -1.409599 -0.515821   L
9996 -0.479893 -0.650419  0.745152 -0.646038   E
9997  0.523331  0.787112  0.486066  1.093156   K
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[10000 rows x 5 columns]

In [49]:
df6.isnull().sum()

one      0
two      0
three    0
four     0
key      0
dtype: int64

In [50]:
df6.head()

        one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R
4  0.354628 -0.133116  0.283763 -0.837063   Q

In [51]:
df6.head(20)

         one       two     three      four key
0   0.467976 -0.038649 -0.295344 -1.824726   L
1  -0.358893  1.404453  0.704965 -0.200638   B
2  -0.501840  0.659254 -0.421691 -0.057688   G
3   0.204886  1.074134  1.388361 -0.982404   R
4   0.354628 -0.133116  0.283763 -0.837063   Q
5   1.817480  0.742273  0.419395 -2.251035   Q
6  -0.776764  0.935518 -0.332872 -1.875641   U
7  -0.913135  1.530624 -0.572657  0.477252   K
8   0.358480 -0.497572 -0.367016  0.507702   S
9  -1.740877 -1.160417 -1.637830  2.172201   G
10  0.240564 -0.328249  1.252155  1.072796   8
11  0.764018  1.165476 -0.639544  1.495258   R
12  0.571035 -0.310537  0.582437 -0.298765   1
13  2.317658  0.430710 -1.334216  0.199679   P
14  1.547771 -1.119753 -2.277634  0.329586   J
15 -1.310608  0.401719 -1.000987  1.156708   E
16 -0.088496  0.634712  0.153324  0.415335   B
17 -0.018663 -0.247487 -1.446522  0.750938   A
18 -0.070127 -1.579097  0.120892  0.671432   F
19 -0.194678 -0.492039  2.359605  0.319810   H

In [52]:
df6.tail()

           one       two     three      four key
9995  2.311896 -0.417070 -1.409599 -0.515821   L
9996 -0.479893 -0.650419  0.745152 -0.646038   E
9997  0.523331  0.787112  0.486066  1.093156   K
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

In [53]:
df6.tail(20)

           one       two     three      four key
9980 -0.595349  0.001781 -1.423355 -1.458477   M
9981  1.392170 -1.396560 -1.425306 -0.847535   H
9982 -0.896029 -0.152287  1.924483  0.365184   6
9983 -2.274642 -0.901874  1.500352  0.996541   N
9984 -0.301898  1.019906  1.102160  2.624526   I
9985 -2.548389 -0.585374  1.496201 -0.718815   D
9986 -0.064588  0.759292 -1.568415 -0.420933   E
9987 -0.143365 -1.111760 -1.815581  0.435274   2
9988 -0.070412 -1.055921  0.338017 -0.440763   X
9989  0.649148  0.994273 -1.384227  0.485120   Q
9990 -0.370769  0.404356 -1.051628 -1.050899   8
9991 -0.409980  0.155627 -0.818990  1.277350   W
9992  0.301214 -1.111203  0.668258  0.671922   A
9993  1.821117  0.416445  0.173874  0.505118   X
9994  0.068804  1.322759  0.802346  0.223618   H
9995  2.311896 -0.417070 -1.409599 -0.515821   L
9996 -0.479893 -0.650419  0.745152 -0.646038   E
9997  0.523331  0.787112  0.486066  1.093156   K
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

In [58]:
df6.head(1501).tail(500)

           one       two     three      four key
1001 -0.358893  1.404453  0.704965 -0.200638   J
1002 -0.501840  0.659254 -0.421691 -0.057688   R
1003  0.204886  1.074134  1.388361 -0.982404   S
1004  0.354628 -0.133116  0.283763 -0.837063   B
1005  1.817480  0.742273  0.419395 -2.251035   Q
...        ...       ...       ...       ...  ..
1496  0.173217 -0.116329  0.373466  0.381805   M
1497 -0.289274  1.439352 -0.799853 -1.208543   9
1498  1.094008  0.049683 -1.445820  0.540209   C
1499  0.290745  0.590175  0.895260 -0.025518   D
1500 -0.264040 -1.204051  0.504199  0.602873   O

[500 rows x 5 columns]