# Pokemon

### Introduction:

This time you will create the data.



### Step 1. Import the necessary libraries (pandas, numpy etc)

In [1]:
import numpy as np
import pandas as pd

### Step 2. Run the below line of code to create a dictionary

In [2]:
raw_data = {"name": ['Bulbasaur', 'Charmander','Squirtle','Caterpie'],
            "evolution": ['Ivysaur','Charmeleon','Wartortle','Metapod'],
            "type": ['grass', 'fire', 'water', 'bug'],
            "hp": [45, 39, 44, 45],
            "pokedex": ['yes', 'no','yes','no']                        
            }

### Step 3. Assign it to a variable called pokemon and it should be a pandas DataFrame.

In [4]:
pokemon = pd.DataFrame(raw_data)
pokemon

         name   evolution   type  hp pokedex
0   Bulbasaur     Ivysaur  grass  45     yes
1  Charmander  Charmeleon   fire  39      no
2    Squirtle   Wartortle  water  44     yes
3    Caterpie     Metapod    bug  45      no

### Step 4. change the order of the columns arrange it ascending order & their values to

In [27]:
# pokemon.columns
sorted_poke = sorted(pokemon.columns)
# print(pokemon)
print(sorted_poke)

['evolution', 'hp', 'name', 'pokedex', 'type']

In [28]:
pokemon[sorted_poke].sort_values(sorted_poke)

    evolution  hp        name pokedex   type
1  Charmeleon  39  Charmander      no   fire
0     Ivysaur  45   Bulbasaur     yes  grass
3     Metapod  45    Caterpie      no    bug
2   Wartortle  44    Squirtle     yes  water

In [8]:
# pokemon[sorted(pokemon.columns)].sort_values(sorted(pokemon.columns))

    evolution  hp        name pokedex   type
1  Charmeleon  39  Charmander      no   fire
0     Ivysaur  45   Bulbasaur     yes  grass
3     Metapod  45    Caterpie      no    bug
2   Wartortle  44    Squirtle     yes  water

In [9]:
# pokemon[sorted(pokemon.columns)].sort_values(by=[['evolution', 'hp', 'name', 'pokedex', 'type']])

### Step 5. Add another column called place, and insert places (lakes, parks, hills etc) of your choice.

In [15]:
# pokemon['place'] = ['Lake', ' Parks', ' Hills', 'Rainforest']
L=[]
for i in range(pokemon.shape[0]):
    a = input(f'enter value for row {i}')
    L.append(a)

pokemon[input('enter columns name')]=L

pokemon

enter value for row 0 hills
enter value for row 1 snow
enter value for row 2 parks
enter value for row 3 sky
enter columns name place

         name   evolution   type  hp pokedex  place
0   Bulbasaur     Ivysaur  grass  45     yes  hills
1  Charmander  Charmeleon   fire  39      no   snow
2    Squirtle   Wartortle  water  44     yes  parks
3    Caterpie     Metapod    bug  45      no   sky

### Step 6. Display the data type of each column

In [18]:
pokemon.info

<bound method DataFrame.info of          name   evolution   type  hp pokedex  place
0   Bulbasaur     Ivysaur  grass  45     yes  hills
1  Charmander  Charmeleon   fire  39      no   snow
2    Squirtle   Wartortle  water  44     yes  parks
3    Caterpie     Metapod    bug  45      no   sky >