### Missing Values and Deleting Data points



### Step 1. Import the necessary libraries numpy, pandas etc

### Step 2. Import the dataset *wine.txt* from this [address](https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data) or from the folder

In [21]:
import numpy as np
import pandas as pd

In [22]:
wine = pd.read_csv('Copy of wine.data', header=None)

In [23]:
wine

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,3,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
174,3,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
175,3,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
176,3,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
177,3,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

### Step 3. Assign it to a variable called wine

Please note that the original data text file doesn't contain any header. Please ensure that when you import the data, you should use a suitable argument so as to avoid data getting imported as header.

In [24]:
wine

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,3,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
174,3,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
175,3,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
176,3,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
177,3,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

### Step 4. Delete the first, fourth, seventh, nineth, eleventh, thirteenth and fourteenth columns

In [25]:
col=[0,3,6,8,10,12,13]
wine = wine.drop(columns=col)

In [26]:
wine

        1     2     4    5     7     9     11
0    14.23  1.71  15.6  127  3.06  2.29  1.04
1    13.20  1.78  11.2  100  2.76  1.28  1.05
2    13.16  2.36  18.6  101  3.24  2.81  1.03
3    14.37  1.95  16.8  113  3.49  2.18  0.86
4    13.24  2.59  21.0  118  2.69  1.82  1.04
..     ...   ...   ...  ...   ...   ...   ...
173  13.71  5.65  20.5   95  0.61  1.06  0.64
174  13.40  3.91  23.0  102  0.75  1.41  0.70
175  13.27  4.28  20.0  120  0.69  1.35  0.59
176  13.17  2.59  20.0  120  0.68  1.46  0.60
177  14.13  4.10  24.5   96  0.76  1.35  0.61

[178 rows x 7 columns]

### Step 5. Assign the columns as below:

The attributes are (dontated by Riccardo Leardi, riclea '@' anchem.unige.it):  
1) alcohol  
2) malic_acid  
3) alcalinity_of_ash  
4) magnesium  
5) flavanoids  
6) proanthocyanins  
7) hue

In [7]:
names=['alcohol','malic_acid','alcalinity_of_ash','magnesium','flavanoids','proanthocyanins','hue']
names

['alcohol',
 'malic_acid',
 'alcalinity_of_ash',
 'magnesium',
 'flavanoids',
 'proanthocyanins',
 'hue']

In [27]:
wine.columns

Index([1, 2, 4, 5, 7, 9, 11], dtype='int64')

In [28]:
wine.columns=names
wine

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
0,14.23,1.71,15.6,127,3.06,2.29,1.04
1,13.20,1.78,11.2,100,2.76,1.28,1.05
2,13.16,2.36,18.6,101,3.24,2.81,1.03
3,14.37,1.95,16.8,113,3.49,2.18,0.86
4,13.24,2.59,21.0,118,2.69,1.82,1.04
...,...,...,...,...,...,...,...
173,13.71,5.65,20.5,95,0.61,1.06,0.64
174,13.40,3.91,23.0,102,0.75,1.41,0.70
175,13.27,4.28,20.0,120,0.69,1.35,0.59
176,13.17,2.59,20.0,120,0.68,1.46,0.60
177,14.13,4.10,24.5,96,0.76,1.35,0.61

In [10]:
wine.iloc[0:3,0]=np.nan

### Step 6. Set the values of the first 3 values from alcohol column as NaN

In [29]:
wine.iloc[0:3,0]=np.nan
wine

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
0,NaN,1.71,15.6,127,3.06,2.29,1.04
1,NaN,1.78,11.2,100,2.76,1.28,1.05
2,NaN,2.36,18.6,101,3.24,2.81,1.03
3,14.37,1.95,16.8,113,3.49,2.18,0.86
4,13.24,2.59,21.0,118,2.69,1.82,1.04
...,...,...,...,...,...,...,...
173,13.71,5.65,20.5,95,0.61,1.06,0.64
174,13.40,3.91,23.0,102,0.75,1.41,0.70
175,13.27,4.28,20.0,120,0.69,1.35,0.59
176,13.17,2.59,20.0,120,0.68,1.46,0.60
177,14.13,4.10,24.5,96,0.76,1.35,0.61

### Step 7. Now set the value of the rows 3 and 4 of magnesium as NaN

In [30]:
wine.iloc[2:4,3]=np.nan

In [31]:
wine

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
0,NaN,1.71,15.6,127.0,3.06,2.29,1.04
1,NaN,1.78,11.2,100.0,2.76,1.28,1.05
2,NaN,2.36,18.6,NaN,3.24,2.81,1.03
3,14.37,1.95,16.8,NaN,3.49,2.18,0.86
4,13.24,2.59,21.0,118.0,2.69,1.82,1.04
...,...,...,...,...,...,...,...
173,13.71,5.65,20.5,95.0,0.61,1.06,0.64
174,13.40,3.91,23.0,102.0,0.75,1.41,0.70
175,13.27,4.28,20.0,120.0,0.69,1.35,0.59
176,13.17,2.59,20.0,120.0,0.68,1.46,0.60
177,14.13,4.10,24.5,96.0,0.76,1.35,0.61

In [32]:
wine.head(15)

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
0,NaN,1.71,15.6,127.0,3.06,2.29,1.04
1,NaN,1.78,11.2,100.0,2.76,1.28,1.05
2,NaN,2.36,18.6,NaN,3.24,2.81,1.03
3,14.37,1.95,16.8,NaN,3.49,2.18,0.86
4,13.24,2.59,21.0,118.0,2.69,1.82,1.04
5,14.20,1.76,15.2,112.0,3.39,1.97,1.05
6,14.39,1.87,14.6,96.0,2.52,1.98,1.02
7,14.06,2.15,17.6,121.0,2.51,1.25,1.06
8,14.83,1.64,14.0,97.0,2.98,1.98,1.08
9,13.86,1.35,16.0,98.0,3.15,1.85,1.01
10,14.10,2.16,18.0,105.0,3.32,2.38,1.25
11,14.12,1.48,16.8,95.0,2.43,1.57,1.17
12,13.75,1.73,16.0,89.0,2.76,1.81,1.15
13,14.75,1.73,11.4,91.0,3.69,2.81,1.25
14,14.38,1.87,12.0,102.0,3.64,2.96,1.20

### Step 8. Fill the value of NaN with the number 10 in alcohol and 100 in magnesium

In [15]:

wine.loc[wine['alcohol']==10,'alcohol'] = np.nan

In [16]:
wine.head(15)

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
0,NaN,1.71,15.6,127.0,3.06,2.29,1.04
1,NaN,1.78,11.2,100.0,2.76,1.28,1.05
2,NaN,2.36,18.6,101.0,3.24,2.81,1.03
3,14.37,1.95,16.8,NaN,3.49,2.18,0.86
4,13.24,2.59,21.0,NaN,2.69,1.82,1.04
5,14.20,1.76,15.2,112.0,3.39,1.97,1.05
6,14.39,1.87,14.6,96.0,2.52,1.98,1.02
7,14.06,2.15,17.6,121.0,2.51,1.25,1.06
8,14.83,1.64,14.0,97.0,2.98,1.98,1.08
9,13.86,1.35,16.0,98.0,3.15,1.85,1.01
10,14.10,2.16,18.0,105.0,3.32,2.38,1.25
11,14.12,1.48,16.8,95.0,2.43,1.57,1.17
12,13.75,1.73,16.0,89.0,2.76,1.81,1.15
13,14.75,1.73,11.4,91.0,3.69,2.81,1.25
14,14.38,1.87,12.0,102.0,3.64,2.96,1.20

### Step 9. Count the number of missing values in all columns.

In [17]:
wine.isnull().sum()

alcohol              3
malic_acid           0
alcalinity_of_ash    0
magnesium            2
flavanoids           0
proanthocyanins      0
hue                  0
dtype: int64

### Step 11.  Set the rows Alternate rows of alcohol column to the  NaN

### Step 12.  How many missing values do we have now?

# Q13. Display only those rows which have missing in alcohol

### Step 13. Delete the rows that contain missing values

In [18]:
wine

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
0,NaN,1.71,15.6,127.0,3.06,2.29,1.04
1,NaN,1.78,11.2,100.0,2.76,1.28,1.05
2,NaN,2.36,18.6,101.0,3.24,2.81,1.03
3,14.37,1.95,16.8,NaN,3.49,2.18,0.86
4,13.24,2.59,21.0,NaN,2.69,1.82,1.04
...,...,...,...,...,...,...,...
173,13.71,5.65,20.5,95.0,0.61,1.06,0.64
174,13.40,3.91,23.0,102.0,0.75,1.41,0.70
175,13.27,4.28,20.0,120.0,0.69,1.35,0.59
176,13.17,2.59,20.0,120.0,0.68,1.46,0.60
177,14.13,4.10,24.5,96.0,0.76,1.35,0.61

### Step 14.  Reset the index, so it starts with 0 again